// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package agent

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/abundo/portitor/internal/fwconfig"
	"github.com/abundo/portitor/internal/render"
)

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readTestFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// A default instance that ran from etc_dir/instances/<name> moves to the
// standard directories: Kea's leases lose the instance's name, named's
// keys and zones move up, dnsmgr2 starts over and the old files go.
func TestMoveDefaultInstance(t *testing.T) {
	a, _ := testAgent(t)
	a.cfg.DryRun = false // file moves only; commands still go to the dry runner
	p := a.cfg.Paths
	p.BindCacheDir = filepath.Join(t.TempDir(), "cache")
	p.BindZonesDir = filepath.Join(t.TempDir(), "zones")
	p.BindRunDir = filepath.Join(t.TempDir(), "run")
	a.cfg.Paths = p
	in := &fwconfig.Instance{Name: "main", Default: true}
	old := p.Files(&fwconfig.Instance{Name: "main"})

	writeTestFile(t, filepath.Join(p.InstanceEtc("main"), "named.conf"), "old")
	writeTestFile(t, filepath.Join(old.KeaData, "kea-leases4-main.csv"), "lease4")
	writeTestFile(t, filepath.Join(old.KeaData, "kea-leases6-main.csv.1"), "lease6")
	writeTestFile(t, filepath.Join(old.BindCache, "Kexample.com.+013+1.key"), "key")
	writeTestFile(t, filepath.Join(old.BindZones, "example.com"), "zone")
	writeTestFile(t, filepath.Join(p.InstanceState("main"), "dnsmgr2.sqlite"), "db")
	writeTestFile(t, filepath.Join(old.KeaData, "kea-dhcp6-serverid"), "duid")
	writeTestFile(t, filepath.Join(p.KeaDataDir, "kea-dhcp6-serverid"), "duid")
	writeTestFile(t, filepath.Join(old.BindCache, "managed-keys.bind"), "old anchors")
	writeTestFile(t, filepath.Join(p.BindCacheDir, "managed-keys.bind"), "anchors")

	if err := a.moveDefaultInstance(context.Background(), in); err != nil {
		t.Fatal(err)
	}
	for path, want := range map[string]string{
		filepath.Join(p.KeaDataDir, "kea-leases4.csv"):           "lease4",
		filepath.Join(p.KeaDataDir, "kea-leases6.csv.1"):         "lease6",
		filepath.Join(p.BindCacheDir, "Kexample.com.+013+1.key"): "key",
		filepath.Join(p.BindZonesDir, "example.com"):             "zone",
	} {
		if got := readTestFile(t, path); got != want {
			t.Errorf("%s = %q, want %q", path, got, want)
		}
	}
	for _, gone := range []string{p.InstanceEtc("main"), old.KeaData, old.BindCache, old.BindZones, filepath.Join(p.InstanceState("main"), "dnsmgr2.sqlite")} {
		if _, err := os.Stat(gone); err == nil {
			t.Errorf("%s is still there", gone)
		}
	}
	// Done once: a second call changes nothing.
	if err := a.moveDefaultInstance(context.Background(), in); err != nil {
		t.Fatal(err)
	}
}

// The first file of the distribution (or the sysadmin) that a default
// instance's file replaces is kept; later ones and our own are not.
func TestWriteFileKeepsOriginal(t *testing.T) {
	a, _ := testAgent(t)
	a.cfg.DryRun = false
	path := a.cfg.Paths.RadvdConf
	writeTestFile(t, path, "interface eth0 { };\n")
	ours := "# Generated by portitor-agent, instance main. Do not edit.\n"
	if _, err := a.writeFile(render.File{Path: path, Content: ours, Mode: 0o644}); err != nil {
		t.Fatal(err)
	}
	if got := readTestFile(t, path+".portitor-orig"); got != "interface eth0 { };\n" {
		t.Errorf("kept %q", got)
	}
	writeTestFile(t, path, "hand edit\n")
	if _, err := a.writeFile(render.File{Path: path, Content: ours, Mode: 0o644}); err != nil {
		t.Fatal(err)
	}
	if got := readTestFile(t, path+".portitor-orig"); got != "interface eth0 { };\n" {
		t.Errorf("the first original was replaced by %q", got)
	}
	if got := readTestFile(t, path); got != ours {
		t.Errorf("wrote %q", got)
	}
}
