// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"fmt"
	"strings"

	"github.com/abundo/portitor/internal/fwconfig"
)

// ChronyConf renders chrony.conf for an instance with NTP. The default
// instance's chronyd sets the host's clock and keeps the distribution's
// drift and NTS files; a virtual firewall's runs with -x
// (portitor-chrony@.service), its PID file in the unit's private /tmp and
// its command socket at files.ChronySocket, as /run/chrony is the host's.
// The agent reads the sources and statistics through the socket; the UDP
// command port is off.
func ChronyConf(in *fwconfig.Instance, files InstanceFiles) string {
	b := &strings.Builder{}
	b.WriteString("# Generated by portitor-agent. Do not edit.\n\n")
	for _, s := range in.NTP.Servers {
		kind := "server"
		if s.Pool {
			kind = "pool"
		}
		b.WriteString(kind + " " + s.Address)
		if s.IBurst {
			b.WriteString(" iburst")
		}
		if s.NTS {
			b.WriteString(" nts")
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
	if in.Default {
		b.WriteString("driftfile /var/lib/chrony/chrony.drift\n")
		b.WriteString("ntsdumpdir /var/lib/chrony\n")
		b.WriteString("makestep 1 3\n")
		b.WriteString("rtcsync\n")
	} else {
		b.WriteString("pidfile /tmp/chronyd.pid\n")
		fmt.Fprintf(b, "bindcmdaddress %s\n", files.ChronySocket)
	}
	b.WriteString("cmdport 0\n")
	if len(in.NTP.Interfaces) > 0 {
		// The ruleset lets clients in on the interfaces only.
		b.WriteString("\n")
		if len(in.NTP.Allow) == 0 {
			b.WriteString("allow all\n")
		}
		for _, a := range in.NTP.Allow {
			fmt.Fprintf(b, "allow %s\n", a)
		}
	}
	return b.String()
}
