// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"encoding/json"
	"fmt"
	"maps"
	"net/netip"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"

	dnsmgr "github.com/abundo/dnsmgr2/dnsmgr"

	"github.com/abundo/portitor/internal/fwconfig"
)

// dnsmgr2 template names. There is one dnsmgr2 config per instance, so a
// single fixed name per template kind is enough. The SOA and zone
// templates named here are for zones without a template of their own;
// fwconfig templates get a prefix so they can't collide with them.
const (
	dnsmgrHostTemplate = "firewall"
	dnsmgrSOATemplate  = "firewall"
	dnsmgrZoneTemplate = "firewall"
	dnsmgrSOAPrefix    = "soa-"
	dnsmgrZonePrefix   = "tpl-"
)

// fqdn adds the trailing dot zone files need for an absolute name.
func fqdn(name string) string {
	return strings.TrimSuffix(name, ".") + "."
}

// dnssecPolicies renders the BIND dnssec-policy statements that zone
// templates refer to (dnsmgr2 writes only the reference).
func dnssecPolicies(b *strings.Builder, policies []fwconfig.DNSSECPolicy) {
	for _, k := range policies {
		lifetime := func(s string) string {
			if s == "" {
				return "unlimited"
			}
			return s
		}
		fmt.Fprintf(b, "dnssec-policy %q {\n", k.Name)
		b.WriteString("\tkeys {\n")
		fmt.Fprintf(b, "\t\tksk lifetime %s algorithm %s;\n", lifetime(k.KSKLifetime), k.KSKAlgorithm)
		fmt.Fprintf(b, "\t\tzsk lifetime %s algorithm %s;\n", lifetime(k.ZSKLifetime), k.ZSKAlgorithm)
		b.WriteString("\t};\n")
		for _, o := range []struct{ name, value string }{
			{"purge-keys", k.PurgeKeys},
			{"signatures-validity", k.SignaturesValidity},
			{"signatures-validity-dnskey", k.SignaturesValidityDNSKEY},
			{"signatures-refresh", k.SignaturesRefresh},
		} {
			if o.value != "" {
				fmt.Fprintf(b, "\t%s %s;\n", o.name, o.value)
			}
		}
		b.WriteString("};\n\n")
	}
}

// NamedConf renders BIND's main config for an instance. Zones come from
// dnsmgr2 through named.conf.dnsmgr2; this file carries the resolver
// options (listen addresses, recursion ACL, forwarders). dhcpDNS holds the
// DNS servers of the instance's DHCP leases by interface.
func NamedConf(in *fwconfig.Instance, p Paths, dhcpDNS map[string][]string) string {
	listen4, listen6 := []string{"127.0.0.1"}, []string{"::1"}
	var recursion []string
	for _, name := range in.DNS.ListenInterfaces {
		ifc := in.Interface(name)
		if ifc == nil {
			continue
		}
		for _, a := range ifc.Addresses {
			pfx, err := netip.ParsePrefix(a)
			if err != nil {
				continue
			}
			if pfx.Addr().Is4() {
				listen4 = append(listen4, pfx.Addr().String())
			} else if !pfx.Addr().IsLinkLocalUnicast() {
				listen6 = append(listen6, pfx.Addr().String())
			}
			recursion = append(recursion, pfx.Masked().String())
		}
	}
	if len(in.DNS.AllowRecursion) > 0 {
		recursion = append([]string(nil), in.DNS.AllowRecursion...)
	}
	recursion = append([]string{"localhost"}, recursion...)

	var forwarders []string
	switch {
	case in.DNS.Upstream == fwconfig.UpstreamRoot || in.DNS.ForwardMode == fwconfig.ForwardOff:
	case in.DNS.Upstream == fwconfig.UpstreamDHCP:
		forwarders = append(forwarders, dhcpDNS[in.DNS.DHCPInterface]...)
	default:
		forwarders = append(forwarders, in.DNS.Forwarders...)
		if in.DNS.ForwardFromDHCP {
			ifaces := slices.Sorted(maps.Keys(dhcpDNS))
			for _, name := range ifaces {
				for _, a := range dhcpDNS[name] {
					forwarders = appendUnique(forwarders, a)
				}
			}
		}
	}
	validation := fwconfig.DNSSECValidationAuto
	if in.DNS.DNSSECValidation == fwconfig.DNSSECValidationNo {
		validation = fwconfig.DNSSECValidationNo
	}
	forward := "first"
	if in.DNS.ForwardMode == fwconfig.ForwardOnly {
		forward = "only"
	}

	b := &strings.Builder{}
	fmt.Fprintf(b, "// Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	b.WriteString("options {\n")
	// named's view: a virtual firewall's unit mounts its own directories
	// (InstanceFiles) over BindCacheDir and BindRunDir.
	fmt.Fprintf(b, "\tdirectory %q;\n", p.BindCacheDir)
	fmt.Fprintf(b, "\tpid-file %q;\n", filepath.Join(p.BindRunDir, "named.pid"))
	fmt.Fprintf(b, "\tsession-keyfile %q;\n", filepath.Join(p.BindRunDir, "session.key"))
	fmt.Fprintf(b, "\tlisten-on port 53 { %s; };\n", strings.Join(listen4, "; "))
	fmt.Fprintf(b, "\tlisten-on-v6 port 53 { %s; };\n", strings.Join(listen6, "; "))
	fmt.Fprintf(b, "\tallow-query { %s; };\n", strings.Join(recursion, "; "))
	fmt.Fprintf(b, "\tallow-recursion { %s; };\n", strings.Join(recursion, "; "))
	b.WriteString("\trecursion yes;\n")
	if len(forwarders) > 0 {
		fmt.Fprintf(b, "\tforwarders { %s; };\n", strings.Join(forwarders, "; "))
		fmt.Fprintf(b, "\tforward %s;\n", forward)
	}
	fmt.Fprintf(b, "\tdnssec-validation %s;\n", validation)
	if in.DNS.DNS64 != "" {
		// Recursion is already limited to allow-recursion's clients.
		fmt.Fprintf(b, "\tdns64 %s {\n\t};\n", in.DNS.DNS64)
	}
	var forwardOnly []fwconfig.DNSZone
	for _, z := range in.DNS.Zones {
		if z.Type == fwconfig.ZoneForwardOnly {
			forwardOnly = append(forwardOnly, z)
		}
	}
	if len(forwardOnly) > 0 && validation != fwconfig.DNSSECValidationNo {
		// Typically internal names under a signed public domain: their
		// answers can't be validated.
		names := make([]string, len(forwardOnly))
		for i, z := range forwardOnly {
			names[i] = fmt.Sprintf("%q", z.Name)
		}
		fmt.Fprintf(b, "\tvalidate-except { %s; };\n", strings.Join(names, "; "))
	}
	b.WriteString("\tallow-transfer { none; };\n")
	b.WriteString("\tversion none;\n")
	if in.DNS.QueryLog != nil {
		b.WriteString("\tquerylog yes;\n")
	}
	b.WriteString("};\n\n")
	if in.DNS.QueryLog != nil {
		// To the journal, under the instance's named unit, where the
		// agent reads them (see agent.queryLog); the filters are its.
		b.WriteString("logging {\n")
		b.WriteString("\tchannel portitor_queries { syslog daemon; severity info; };\n")
		b.WriteString("\tcategory queries { portitor_queries; };\n")
		b.WriteString("};\n\n")
	}
	if in.Default {
		// The distribution's unit reloads with rndc: named's default
		// control channel, on loopback with its rndc.key.
		b.WriteString("// rndc: the default control channel (loopback, rndc.key).\n\n")
	} else {
		// Reload is SIGHUP from systemd; no rndc channel to secure.
		b.WriteString("controls { };\n\n")
	}
	dnssecPolicies(b, in.DNS.DNSSECPolicies)
	for _, z := range forwardOnly {
		fmt.Fprintf(b, "zone %q {\n\ttype forward;\n\tforward only;\n", z.Name)
		fmt.Fprintf(b, "\tforwarders { %s; };\n};\n\n", strings.Join(z.Forwarders, "; "))
	}
	fmt.Fprintf(b, "include %q;\n", p.Files(in).NamedInclude)
	return b.String()
}

// DnsmgrConfig builds the dnsmgr2 configuration for an instance: its DNS
// zones (Kea's configs are rendered in full, see kea.go). Returns ok=false
// when the instance runs no DNS server.
func DnsmgrConfig(in *fwconfig.Instance, p Paths, u Units) (dnsmgr.ConfigRoot, bool) {
	if !in.DNS.Enabled {
		return dnsmgr.ConfigRoot{}, false
	}
	f := p.Files(in)
	etc := f.DnsmgrDir
	state := p.InstanceState(in.Name)
	tmp := filepath.Join(state, "tmp")

	cfg := dnsmgr.ConfigRoot{
		Dbfile:    filepath.Join(state, "dnsmgr2.sqlite"),
		Sources:   dnsmgr.ConfigSources{{Type: "json", Name: filepath.Join(etc, "records.json")}},
		ConfigDir: etc,
	}
	group := dnsmgr.ConfigDataType{}

	named := u.Named(in)
	cfg.DNS = dnsmgr.ConfigDNS{
		HostTemplates: map[string]dnsmgr.ConfigDNS_HostTemplate{
			dnsmgrHostTemplate: {
				Type:          "isc_bind",
				Configdir:     filepath.Dir(f.NamedInclude),
				IncludeFile:   "named.conf.dnsmgr2",
				ZonesDir:      f.BindZones,
				Zonesfile:     "{zone}",
				Tmpdir:        tmp,
				CmdReloadAll:  "systemctl reload-or-restart " + named,
				CmdReloadZone: "systemctl reload-or-restart " + named,
				CmdRestart:    "systemctl restart " + named,
				CmdStatus:     "systemctl is-active " + named,
			},
		},
		SOATemplates: map[string]dnsmgr.ConfigDNS_SOA_template{
			dnsmgrSOATemplate: {
				Mname:        "localhost.",
				Rname:        "hostmaster.localhost.",
				SerialFormat: "date_serial",
				Refresh:      3600,
				Retry:        600,
				Expire:       604800,
				Minimum:      300,
			},
		},
		ZoneTemplates: map[string]dnsmgr.ConfigDNS_ZoneTemplate{
			dnsmgrZoneTemplate: {
				SOA:        dnsmgrSOATemplate,
				DefaultTTL: "300",
				NS:         []dnsmgr.ConfigDNS_TemplateNS{{Name: "@", Type: "NS", Value: "localhost."}},
			},
		},
	}
	for _, s := range in.DNS.SOATemplates {
		cfg.DNS.SOATemplates[dnsmgrSOAPrefix+s.Name] = dnsmgr.ConfigDNS_SOA_template{
			Mname:        fqdn(s.MName),
			Rname:        fqdn(s.RName),
			SerialFormat: "date_serial",
			Refresh:      int(s.Refresh),
			Retry:        int(s.Retry),
			Expire:       int(s.Expire),
			Minimum:      int(s.Minimum),
		}
	}
	for _, t := range in.DNS.ZoneTemplates {
		zt := dnsmgr.ConfigDNS_ZoneTemplate{
			SOA:          dnsmgrSOAPrefix + t.SOA,
			DefaultTTL:   strconv.FormatInt(t.DefaultTTL, 10),
			DNSSECpolicy: t.DNSSECPolicy,
		}
		for _, ns := range t.Nameservers {
			zt.NS = append(zt.NS, dnsmgr.ConfigDNS_TemplateNS{Name: "@", Type: "NS", Value: fqdn(ns)})
		}
		cfg.DNS.ZoneTemplates[dnsmgrZonePrefix+t.Name] = zt
	}
	group.HostDnsTemplate = dnsmgrHostTemplate
	for _, z := range in.DNS.Zones {
		if z.Type == fwconfig.ZoneForwardOnly {
			continue // in named.conf
		}
		tmpl := dnsmgrZoneTemplate
		if z.Template != "" {
			tmpl = dnsmgrZonePrefix + z.Template
		}
		group.Zones = append(group.Zones, dnsmgr.ConfigZone{Name: z.Name, Type: z.Type, DnsTemplate: tmpl})
	}

	cfg.Dnsmgr2 = dnsmgr.ConfigDataGroups{group}
	return cfg, true
}

type recordsJSON struct {
	Version int                 `json:"version"`
	Domains []recordsJSONDomain `json:"domains"`
}

type recordsJSONDomain struct {
	Name    string              `json:"name"`
	Records []recordsJSONRecord `json:"records"`
}

type recordsJSONRecord struct {
	Name  string `json:"name"`
	TTL   int64  `json:"ttl,omitempty"`
	Type  string `json:"type"`
	Value string `json:"value"`
	MAC   string `json:"mac,omitempty"`
}

// RecordsJSON renders the dnsmgr2 JSON source for an instance. Reverse
// zones get PTRs from A/AAAA records automatically.
func RecordsJSON(in *fwconfig.Instance) string {
	out := recordsJSON{Version: 1, Domains: []recordsJSONDomain{}}
	if in.DNS.Enabled {
		for _, z := range in.DNS.Zones {
			if z.Type != fwconfig.ZoneForward {
				continue
			}
			d := recordsJSONDomain{Name: z.Name, Records: []recordsJSONRecord{}}
			for _, r := range z.Records {
				d.Records = append(d.Records, recordsJSONRecord{Name: r.Name, TTL: r.TTL, Type: r.Type, Value: r.Value, MAC: r.MAC})
			}
			sort.SliceStable(d.Records, func(i, j int) bool { return d.Records[i].Name < d.Records[j].Name })
			out.Domains = append(out.Domains, d)
		}
	}
	data, _ := json.MarshalIndent(out, "", "  ")
	return string(data) + "\n"
}
