// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"encoding/json"
	"fmt"
	"net/netip"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	dnsmgr "github.com/abundo/dnsmgr2/dnsmgr"

	"github.com/abundo/portitor/internal/fwconfig"
)

// dnsmgr2 template names. There is one dnsmgr2 config per instance, so a
// single fixed name per template kind is enough. The SOA and zone
// templates named here are for zones without a template of their own;
// fwconfig templates get a prefix so they can't collide with them.
const (
	dnsmgrHostTemplate = "firewall"
	dnsmgrSOATemplate  = "firewall"
	dnsmgrZoneTemplate = "firewall"
	dnsmgrSOAPrefix    = "soa-"
	dnsmgrZonePrefix   = "tpl-"
)

// fqdn adds the trailing dot zone files need for an absolute name.
func fqdn(name string) string {
	return strings.TrimSuffix(name, ".") + "."
}

// dnssecPolicies renders the BIND dnssec-policy statements that zone
// templates refer to (dnsmgr2 writes only the reference).
func dnssecPolicies(b *strings.Builder, policies []fwconfig.DNSSECPolicy) {
	for _, k := range policies {
		lifetime := func(s string) string {
			if s == "" {
				return "unlimited"
			}
			return s
		}
		fmt.Fprintf(b, "dnssec-policy %q {\n", k.Name)
		b.WriteString("\tkeys {\n")
		fmt.Fprintf(b, "\t\tksk lifetime %s algorithm %s;\n", lifetime(k.KSKLifetime), k.KSKAlgorithm)
		fmt.Fprintf(b, "\t\tzsk lifetime %s algorithm %s;\n", lifetime(k.ZSKLifetime), k.ZSKAlgorithm)
		b.WriteString("\t};\n")
		for _, o := range []struct{ name, value string }{
			{"purge-keys", k.PurgeKeys},
			{"signatures-validity", k.SignaturesValidity},
			{"signatures-validity-dnskey", k.SignaturesValidityDNSKEY},
			{"signatures-refresh", k.SignaturesRefresh},
		} {
			if o.value != "" {
				fmt.Fprintf(b, "\t%s %s;\n", o.name, o.value)
			}
		}
		b.WriteString("};\n\n")
	}
}

// NamedConf renders BIND's main config for an instance. Zones come from
// dnsmgr2 through named.conf.dnsmgr2; this file carries the resolver
// options (listen addresses, recursion ACL, forwarders).
func NamedConf(in *fwconfig.Instance, p Paths, dhcpDNS []string) string {
	listen4, listen6 := []string{"127.0.0.1"}, []string{"::1"}
	var recursion []string
	for _, name := range in.DNS.ListenInterfaces {
		ifc := in.Interface(name)
		if ifc == nil {
			continue
		}
		for _, a := range ifc.Addresses {
			pfx, err := netip.ParsePrefix(a)
			if err != nil {
				continue
			}
			if pfx.Addr().Is4() {
				listen4 = append(listen4, pfx.Addr().String())
			} else if !pfx.Addr().IsLinkLocalUnicast() {
				listen6 = append(listen6, pfx.Addr().String())
			}
			recursion = append(recursion, pfx.Masked().String())
		}
	}
	if len(in.DNS.AllowRecursion) > 0 {
		recursion = append([]string(nil), in.DNS.AllowRecursion...)
	}
	recursion = append([]string{"localhost"}, recursion...)

	forwarders := append([]string(nil), in.DNS.Forwarders...)
	if in.DNS.ForwardFromDHCP {
		for _, a := range dhcpDNS {
			forwarders = appendUnique(forwarders, a)
		}
	}

	dir := p.InstanceState(in.Name)
	b := &strings.Builder{}
	fmt.Fprintf(b, "// Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	b.WriteString("options {\n")
	fmt.Fprintf(b, "\tdirectory %q;\n", filepath.Join(dir, "bind"))
	fmt.Fprintf(b, "\tpid-file %q;\n", filepath.Join(p.RunDir, "named-"+in.Name+".pid"))
	fmt.Fprintf(b, "\tsession-keyfile %q;\n", filepath.Join(dir, "bind", "session.key"))
	fmt.Fprintf(b, "\tlisten-on port 53 { %s; };\n", strings.Join(listen4, "; "))
	fmt.Fprintf(b, "\tlisten-on-v6 port 53 { %s; };\n", strings.Join(listen6, "; "))
	fmt.Fprintf(b, "\tallow-query { %s; };\n", strings.Join(recursion, "; "))
	fmt.Fprintf(b, "\tallow-recursion { %s; };\n", strings.Join(recursion, "; "))
	b.WriteString("\trecursion yes;\n")
	if len(forwarders) > 0 {
		fmt.Fprintf(b, "\tforwarders { %s; };\n", strings.Join(forwarders, "; "))
		b.WriteString("\tforward first;\n")
	}
	b.WriteString("\tdnssec-validation auto;\n")
	b.WriteString("\tallow-transfer { none; };\n")
	b.WriteString("\tversion none;\n")
	b.WriteString("};\n\n")
	// Reload is SIGHUP from systemd; no rndc channel to secure.
	b.WriteString("controls { };\n\n")
	dnssecPolicies(b, in.DNS.DNSSECPolicies)
	fmt.Fprintf(b, "include %q;\n", filepath.Join(p.InstanceEtc(in.Name), "named.conf.dnsmgr2"))
	return b.String()
}

// DnsmgrConfig builds the dnsmgr2 configuration for an instance. Returns
// ok=false when the instance runs neither DNS nor DHCP.
func DnsmgrConfig(in *fwconfig.Instance, p Paths, u Units) (dnsmgr.ConfigRoot, bool) {
	if !in.DNS.Enabled && !in.DHCP.Enabled {
		return dnsmgr.ConfigRoot{}, false
	}
	etc := p.InstanceEtc(in.Name)
	state := p.InstanceState(in.Name)
	tmp := filepath.Join(state, "tmp")

	cfg := dnsmgr.ConfigRoot{
		Dbfile:    filepath.Join(state, "dnsmgr2.sqlite"),
		Sources:   dnsmgr.ConfigSources{{Type: "json", Name: filepath.Join(etc, "records.json")}},
		ConfigDir: etc,
	}
	group := dnsmgr.ConfigDataType{}

	if in.DNS.Enabled {
		named := u.Named(in.Name)
		cfg.DNS = dnsmgr.ConfigDNS{
			HostTemplates: map[string]dnsmgr.ConfigDNS_HostTemplate{
				dnsmgrHostTemplate: {
					Type:          "isc_bind",
					Configdir:     etc,
					IncludeFile:   "named.conf.dnsmgr2",
					ZonesDir:      filepath.Join(state, "zones"),
					Zonesfile:     "{zone}",
					Tmpdir:        tmp,
					CmdReloadAll:  "systemctl reload-or-restart " + named,
					CmdReloadZone: "systemctl reload-or-restart " + named,
					CmdRestart:    "systemctl restart " + named,
					CmdStatus:     "systemctl is-active " + named,
				},
			},
			SOATemplates: map[string]dnsmgr.ConfigDNS_SOA_template{
				dnsmgrSOATemplate: {
					Mname:        "localhost.",
					Rname:        "hostmaster.localhost.",
					SerialFormat: "date_serial",
					Refresh:      3600,
					Retry:        600,
					Expire:       604800,
					Minimum:      300,
				},
			},
			ZoneTemplates: map[string]dnsmgr.ConfigDNS_ZoneTemplate{
				dnsmgrZoneTemplate: {
					SOA:        dnsmgrSOATemplate,
					DefaultTTL: "300",
					NS:         []dnsmgr.ConfigDNS_TemplateNS{{Name: "@", Type: "NS", Value: "localhost."}},
				},
			},
		}
		for _, s := range in.DNS.SOATemplates {
			cfg.DNS.SOATemplates[dnsmgrSOAPrefix+s.Name] = dnsmgr.ConfigDNS_SOA_template{
				Mname:        fqdn(s.MName),
				Rname:        fqdn(s.RName),
				SerialFormat: "date_serial",
				Refresh:      int(s.Refresh),
				Retry:        int(s.Retry),
				Expire:       int(s.Expire),
				Minimum:      int(s.Minimum),
			}
		}
		for _, t := range in.DNS.ZoneTemplates {
			zt := dnsmgr.ConfigDNS_ZoneTemplate{
				SOA:          dnsmgrSOAPrefix + t.SOA,
				DefaultTTL:   strconv.FormatInt(t.DefaultTTL, 10),
				DNSSECpolicy: t.DNSSECPolicy,
			}
			for _, ns := range t.Nameservers {
				zt.NS = append(zt.NS, dnsmgr.ConfigDNS_TemplateNS{Name: "@", Type: "NS", Value: fqdn(ns)})
			}
			cfg.DNS.ZoneTemplates[dnsmgrZonePrefix+t.Name] = zt
		}
		group.HostDnsTemplate = dnsmgrHostTemplate
		for _, z := range in.DNS.Zones {
			tmpl := dnsmgrZoneTemplate
			if z.Template != "" {
				tmpl = dnsmgrZonePrefix + z.Template
			}
			group.Zones = append(group.Zones, dnsmgr.ConfigZone{Name: z.Name, Type: z.Type, DnsTemplate: tmpl})
		}
	}

	if in.DHCP.Enabled {
		kea := u.Kea4(in.Name)
		cfg.DHCP = dnsmgr.ConfigDHCP{
			DomainName: in.DHCP.DomainName,
			HostTemplates: map[string]dnsmgr.ConfigHostDHCPtemplate{
				dnsmgrHostTemplate: {
					Type: "isc_kea",
					IPv4: dnsmgr.ConfigDHCPtemplateProtocol{
						Enable:      true,
						Configdir:   etc,
						IncludeFile: "kea-dhcp4.dnsmgr2.json",
						Tmpdir:      tmp,
						CmdRestart:  "systemctl restart " + kea,
						CmdStatus:   "systemctl is-active " + kea,
					},
				},
			},
		}
		group.HostDhcpTemplate = dnsmgrHostTemplate
		for _, s := range in.DHCP.Subnets {
			pfx, err := netip.ParsePrefix(s.Prefix)
			if err != nil || !pfx.Addr().Is4() {
				continue // DHCPv6: see KeaDhcp6Conf
			}
			cp := dnsmgr.ConfigPrefix{Name: pfx.Masked().String(), Gateway: s.Gateway, DNSServers: s.DNSServers}
			if s.RangeStart != "" {
				cp.Range = s.RangeStart + "-" + s.RangeEnd
			}
			group.Prefixes = append(group.Prefixes, cp)
		}
	}

	cfg.Dnsmgr2 = dnsmgr.ConfigDataGroups{group}
	return cfg, true
}

type recordsJSON struct {
	Version int                 `json:"version"`
	Domains []recordsJSONDomain `json:"domains"`
}

type recordsJSONDomain struct {
	Name    string              `json:"name"`
	Records []recordsJSONRecord `json:"records"`
}

type recordsJSONRecord struct {
	Name  string `json:"name"`
	TTL   int64  `json:"ttl,omitempty"`
	Type  string `json:"type"`
	Value string `json:"value"`
	MAC   string `json:"mac,omitempty"`
}

// RecordsJSON renders the dnsmgr2 JSON source for an instance. Reverse
// zones get PTRs from A/AAAA records automatically.
func RecordsJSON(in *fwconfig.Instance) string {
	out := recordsJSON{Version: 1, Domains: []recordsJSONDomain{}}
	if in.DNS.Enabled {
		for _, z := range in.DNS.Zones {
			if z.Type != fwconfig.ZoneForward {
				continue
			}
			d := recordsJSONDomain{Name: z.Name, Records: []recordsJSONRecord{}}
			for _, r := range z.Records {
				d.Records = append(d.Records, recordsJSONRecord{Name: r.Name, TTL: r.TTL, Type: r.Type, Value: r.Value, MAC: r.MAC})
			}
			sort.SliceStable(d.Records, func(i, j int) bool { return d.Records[i].Name < d.Records[j].Name })
			out.Domains = append(out.Domains, d)
		}
	}
	data, _ := json.MarshalIndent(out, "", "  ")
	return string(data) + "\n"
}

// KeaDhcp4Conf renders Kea's main DHCPv4 config. The subnet list is
// dnsmgr2's include file, so pools and reservations stay dnsmgr2's job.
func KeaDhcp4Conf(in *fwconfig.Instance, p Paths) string {
	var ifaces []string
	for _, s := range in.DHCP.Subnets {
		if pfx, err := netip.ParsePrefix(s.Prefix); err == nil && pfx.Addr().Is4() {
			ifaces = appendUnique(ifaces, s.Interface)
		}
	}
	sort.Strings(ifaces)
	lease := in.DHCP.LeaseTime
	if lease <= 0 {
		lease = 86400
	}
	ifJSON, _ := json.Marshal(ifaces)
	b := &strings.Builder{}
	fmt.Fprintf(b, "// Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	fmt.Fprintf(b, `{
  "Dhcp4": {
    "interfaces-config": { "interfaces": %s },
    "control-socket": { "socket-type": "unix", "socket-name": %q },
    "lease-database": { "type": "memfile", "persist": true, "lfc-interval": 3600, "name": %q },
    "valid-lifetime": %d,
    "renew-timer": %d,
    "rebind-timer": %d,
    "subnet4": <?include %q?>,
    "loggers": [ { "name": "kea-dhcp4", "output-options": [ { "output": "stdout" } ], "severity": "INFO" } ]
  }
}
`, ifJSON,
		filepath.Join(p.KeaSocketDir, "kea4-"+in.Name+".sock"),
		KeaLeaseFile(in.Name, p),
		lease, lease/2, lease*7/8,
		filepath.Join(p.InstanceEtc(in.Name), "kea-dhcp4.dnsmgr2.json"))
	return b.String()
}

// KeaLeaseFile is where Kea keeps an instance's v4 leases. Kea 2.6+
// refuses lease files outside its data directory, hence KeaDataDir.
func KeaLeaseFile(instance string, p Paths) string {
	return filepath.Join(p.KeaDataDir, "kea-leases4-"+instance+".csv")
}
