// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"fmt"
	"net/netip"
	"slices"
	"sort"
	"strings"

	"github.com/abundo/portitor/internal/fwconfig"
)

// FRRDaemons renders FRR's daemons file: zebra (always on) and bgpd.
func FRRDaemons(in *fwconfig.Instance) string {
	b := &strings.Builder{}
	fmt.Fprintf(b, "# Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	b.WriteString("bgpd=yes\nospfd=no\nospf6d=no\nripd=no\nripngd=no\nisisd=no\npimd=no\npim6d=no\nldpd=no\nnhrpd=no\neigrpd=no\nbabeld=no\nsharpd=no\npbrd=no\nbfdd=no\nfabricd=no\nvrrpd=no\npathd=no\n")
	b.WriteString("vtysh_enable=yes\n")
	b.WriteString("zebra_options=\"  -A 127.0.0.1 -s 90000000\"\n")
	b.WriteString("mgmtd_options=\"  -A 127.0.0.1\"\n")
	b.WriteString("bgpd_options=\"   -A 127.0.0.1\"\n")
	b.WriteString("staticd_options=\"-A 127.0.0.1\"\n")
	return b.String()
}

// FRRVtyshConf renders vtysh.conf: the integrated config (frr.conf), which
// frr-reload.py needs to reload.
func FRRVtyshConf(in *fwconfig.Instance) string {
	return fmt.Sprintf("! Generated by portitor-agent, instance %s. Do not edit.\nservice integrated-vtysh-config\n", in.Name)
}

// frrPasswordWord comes before a neighbour's password in frr.conf;
// Bundle.Redacted masks what follows it.
const frrPasswordWord = " password "

// FRRConf renders FRR's integrated config (frr.conf) for an instance's
// routing policy and BGP. Static routes stay the agent's (kernel routes,
// proto 99): "redistribute static" is FRR's redistribute kernel.
func FRRConf(in *fwconfig.Instance) string {
	b := &strings.Builder{}
	fmt.Fprintf(b, "! Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	b.WriteString("frr defaults traditional\n")
	b.WriteString("log syslog informational\n")
	b.WriteString("!\n")
	writeRoutingPolicy(b, &in.RoutingPolicy)
	if in.BGPRunning() {
		writeBGP(b, in.BGP)
	}
	b.WriteString("end\n")
	return b.String()
}

func writeRoutingPolicy(b *strings.Builder, rp *fwconfig.RoutingPolicy) {
	for _, pl := range rp.PrefixLists {
		kw := "ip"
		if pl.Family == "ipv6" {
			kw = "ipv6"
		}
		if pl.Description != "" {
			fmt.Fprintf(b, "%s prefix-list %s description %s\n", kw, pl.Name, pl.Description)
		}
		entries := slices.Clone(pl.Entries)
		sort.SliceStable(entries, func(i, j int) bool { return entries[i].Seq < entries[j].Seq })
		for _, e := range entries {
			fmt.Fprintf(b, "%s prefix-list %s seq %d %s %s", kw, pl.Name, e.Seq, e.Action, e.Prefix)
			if e.GE != 0 {
				fmt.Fprintf(b, " ge %d", e.GE)
			}
			if e.LE != 0 {
				fmt.Fprintf(b, " le %d", e.LE)
			}
			b.WriteString("\n")
		}
		if len(entries) == 0 {
			// An empty list must exist, and deny everything.
			fmt.Fprintf(b, "%s prefix-list %s seq 65535 deny any\n", kw, pl.Name)
		}
		b.WriteString("!\n")
	}
	for _, l := range rp.ASPathLists {
		for i, e := range l.Entries {
			fmt.Fprintf(b, "bgp as-path access-list %s seq %d %s %s\n", l.Name, (i+1)*5, e.Action, e.Regex)
		}
		if len(l.Entries) == 0 {
			fmt.Fprintf(b, "bgp as-path access-list %s seq 5 deny .*\n", l.Name)
		}
		b.WriteString("!\n")
	}
	for _, l := range rp.CommunityLists {
		kw, kind := "community-list", l.Kind
		if l.Large() {
			kw, kind = "large-community-list", strings.TrimPrefix(l.Kind, "large-")
		}
		for i, e := range l.Entries {
			fmt.Fprintf(b, "bgp %s %s %s seq %d %s %s\n", kw, kind, l.Name, (i+1)*5, e.Action, e.Value)
		}
		if len(l.Entries) == 0 {
			// An expanded list that matches nothing listed, as a list
			// can't be empty.
			fmt.Fprintf(b, "bgp %s expanded %s seq 5 deny .*\n", kw, l.Name)
		}
		b.WriteString("!\n")
	}
	families := map[string]string{}
	for _, pl := range rp.PrefixLists {
		families[pl.Name] = pl.Family
	}
	large := map[string]bool{}
	for _, l := range rp.CommunityLists {
		large[l.Name] = l.Large()
	}
	for _, m := range rp.RouteMaps {
		entries := slices.Clone(m.Entries)
		sort.SliceStable(entries, func(i, j int) bool { return entries[i].Seq < entries[j].Seq })
		if len(entries) == 0 {
			// A route map without entries denies everything.
			fmt.Fprintf(b, "route-map %s deny 65535\n", m.Name)
			if m.Description != "" {
				fmt.Fprintf(b, " description %s\n", m.Description)
			}
			b.WriteString("exit\n!\n")
		}
		for i, e := range entries {
			fmt.Fprintf(b, "route-map %s %s %d\n", m.Name, e.Action, e.Seq)
			desc := e.Description
			if desc == "" && i == 0 {
				desc = m.Description
			}
			if desc != "" {
				fmt.Fprintf(b, " description %s\n", desc)
			}
			ipKw := func(list string) string {
				if families[list] == "ipv6" {
					return "ipv6"
				}
				return "ip"
			}
			if e.MatchPrefixList != "" {
				fmt.Fprintf(b, " match %s address prefix-list %s\n", ipKw(e.MatchPrefixList), e.MatchPrefixList)
			}
			if e.MatchNextHop != "" {
				fmt.Fprintf(b, " match %s next-hop prefix-list %s\n", ipKw(e.MatchNextHop), e.MatchNextHop)
			}
			if e.MatchASPath != "" {
				fmt.Fprintf(b, " match as-path %s\n", e.MatchASPath)
			}
			if e.MatchCommunity != "" {
				if large[e.MatchCommunity] {
					fmt.Fprintf(b, " match large-community %s\n", e.MatchCommunity)
				} else {
					fmt.Fprintf(b, " match community %s\n", e.MatchCommunity)
				}
			}
			if e.MatchMetric != nil {
				fmt.Fprintf(b, " match metric %d\n", *e.MatchMetric)
			}
			if e.MatchTag != nil {
				fmt.Fprintf(b, " match tag %d\n", *e.MatchTag)
			}
			if e.SetLocalPreference != nil {
				fmt.Fprintf(b, " set local-preference %d\n", *e.SetLocalPreference)
			}
			if e.SetMetric != nil {
				fmt.Fprintf(b, " set metric %d\n", *e.SetMetric)
			}
			if e.SetWeight != nil {
				fmt.Fprintf(b, " set weight %d\n", *e.SetWeight)
			}
			if e.SetASPathPrepend != "" {
				fmt.Fprintf(b, " set as-path prepend %s\n", strings.Join(strings.Fields(e.SetASPathPrepend), " "))
			}
			if e.SetCommunity != "" {
				fmt.Fprintf(b, " set community %s", strings.Join(strings.Fields(e.SetCommunity), " "))
				if e.SetCommunityAdditive {
					b.WriteString(" additive")
				}
				b.WriteString("\n")
			}
			if e.SetLargeCommunity != "" {
				fmt.Fprintf(b, " set large-community %s\n", strings.Join(strings.Fields(e.SetLargeCommunity), " "))
			}
			if e.SetNextHop != "" {
				if a, err := netip.ParseAddr(e.SetNextHop); err == nil && a.Is6() {
					fmt.Fprintf(b, " set ipv6 next-hop global %s\n", a)
				} else {
					fmt.Fprintf(b, " set ip next-hop %s\n", e.SetNextHop)
				}
			}
			if e.SetOrigin != "" {
				fmt.Fprintf(b, " set origin %s\n", e.SetOrigin)
			}
			if e.OnMatchNext && e.Action == fwconfig.Permit {
				b.WriteString(" on-match next\n")
			}
			b.WriteString("exit\n!\n")
		}
	}
}

func writeBGP(b *strings.Builder, g *fwconfig.BGP) {
	fmt.Fprintf(b, "router bgp %d\n", g.ASN)
	if g.RouterID != "" {
		fmt.Fprintf(b, " bgp router-id %s\n", g.RouterID)
	}
	if g.LogNeighborChanges {
		b.WriteString(" bgp log-neighbor-changes\n")
	} else {
		b.WriteString(" no bgp log-neighbor-changes\n")
	}
	if !g.EBGPRequiresPolicy {
		b.WriteString(" no bgp ebgp-requires-policy\n")
	}
	// Address families are activated per neighbour.
	b.WriteString(" no bgp default ipv4-unicast\n")
	if g.GracefulRestart {
		b.WriteString(" bgp graceful-restart\n")
	}
	if g.MultipathRelax {
		b.WriteString(" bgp bestpath as-path multipath-relax\n")
	}
	if g.Keepalive != 0 {
		fmt.Fprintf(b, " timers bgp %d %d\n", g.Keepalive, holdOf(g.Keepalive, g.Hold))
	}
	for _, p := range g.PeerGroups {
		fmt.Fprintf(b, " neighbor %s peer-group\n", p.Name)
		writePeer(b, p.Name, p, false)
	}
	for _, p := range g.Neighbors {
		ip := canonAddr(p.Address)
		if p.RemoteAS != "" {
			fmt.Fprintf(b, " neighbor %s remote-as %s\n", ip, p.RemoteAS)
		}
		if p.PeerGroup != "" {
			fmt.Fprintf(b, " neighbor %s peer-group %s\n", ip, p.PeerGroup)
		}
		writePeer(b, ip, p, true)
	}
	for _, fam := range []string{"ipv4", "ipv6"} {
		writeAddressFamily(b, g, fam)
	}
	b.WriteString("exit\n!\n")
}

// holdOf is the hold time for a keepalive: three times it when not set.
func holdOf(keepalive, hold int) int {
	if hold == 0 {
		return keepalive * 3
	}
	return hold
}

func canonAddr(s string) string {
	if a, err := fwconfig.ParseAddr(s); err == nil {
		return a.String()
	}
	return s
}

// writePeer writes a neighbour's or peer group's session settings. A peer
// group's remote-as comes after it is declared.
func writePeer(b *strings.Builder, id string, p fwconfig.BGPPeer, neighbor bool) {
	if !neighbor && p.RemoteAS != "" {
		fmt.Fprintf(b, " neighbor %s remote-as %s\n", id, p.RemoteAS)
	}
	if p.Description != "" {
		fmt.Fprintf(b, " neighbor %s description %s\n", id, p.Description)
	}
	if p.Password != "" {
		fmt.Fprintf(b, " neighbor %s%s%s\n", id, frrPasswordWord, p.Password)
	}
	if p.EBGPMultihop > 0 {
		fmt.Fprintf(b, " neighbor %s ebgp-multihop %d\n", id, p.EBGPMultihop)
	}
	if p.UpdateSource != "" {
		fmt.Fprintf(b, " neighbor %s update-source %s\n", id, canonAddr(p.UpdateSource))
	}
	if p.Passive {
		fmt.Fprintf(b, " neighbor %s passive\n", id)
	}
	if p.Keepalive != 0 {
		fmt.Fprintf(b, " neighbor %s timers %d %d\n", id, p.Keepalive, holdOf(p.Keepalive, p.Hold))
	}
	if p.Shutdown {
		fmt.Fprintf(b, " neighbor %s shutdown\n", id)
	}
}

func familyOf(prefix string) string {
	if pfx, err := netip.ParsePrefix(prefix); err == nil && pfx.Addr().Is6() {
		return "ipv6"
	}
	return "ipv4"
}

func writeAddressFamily(b *strings.Builder, g *fwconfig.BGP, fam string) {
	af := &strings.Builder{}
	for _, n := range g.Networks {
		if familyOf(n.Prefix) != fam {
			continue
		}
		fmt.Fprintf(af, "  network %s", n.Prefix)
		if n.RouteMap != "" {
			fmt.Fprintf(af, " route-map %s", n.RouteMap)
		}
		af.WriteString("\n")
	}
	for _, a := range g.Aggregates {
		if familyOf(a.Prefix) != fam {
			continue
		}
		fmt.Fprintf(af, "  aggregate-address %s", a.Prefix)
		if a.ASSet {
			af.WriteString(" as-set")
		}
		if a.SummaryOnly {
			af.WriteString(" summary-only")
		}
		af.WriteString("\n")
	}
	for _, r := range g.Redistribute {
		if r.Family != fam {
			continue
		}
		src := "connected"
		if r.Source == fwconfig.RedistStatic {
			src = "kernel"
		}
		fmt.Fprintf(af, "  redistribute %s", src)
		if r.RouteMap != "" {
			fmt.Fprintf(af, " route-map %s", r.RouteMap)
		}
		af.WriteString("\n")
	}
	if g.MaximumPaths > 0 {
		fmt.Fprintf(af, "  maximum-paths %d\n", g.MaximumPaths)
	}
	for _, p := range g.PeerGroups {
		writePeerFamily(af, p.Name, p, fam)
	}
	for _, p := range g.Neighbors {
		writePeerFamily(af, canonAddr(p.Address), p, fam)
	}
	if af.Len() == 0 {
		return
	}
	fmt.Fprintf(b, " !\n address-family %s unicast\n", fam)
	b.WriteString(af.String())
	b.WriteString(" exit-address-family\n")
}

func writePeerFamily(b *strings.Builder, id string, p fwconfig.BGPPeer, fam string) {
	s := p.IPv4
	if fam == "ipv6" {
		s = p.IPv6
	}
	// Settings of a family that is not active would be refused.
	if !s.Activate {
		return
	}
	fmt.Fprintf(b, "  neighbor %s activate\n", id)
	if s.RouteReflectorClient {
		fmt.Fprintf(b, "  neighbor %s route-reflector-client\n", id)
	}
	if s.NextHopSelf {
		fmt.Fprintf(b, "  neighbor %s next-hop-self\n", id)
	}
	if s.RemovePrivateAS {
		fmt.Fprintf(b, "  neighbor %s remove-private-AS\n", id)
	}
	if s.SoftReconfiguration {
		fmt.Fprintf(b, "  neighbor %s soft-reconfiguration inbound\n", id)
	}
	if s.DefaultOriginate {
		fmt.Fprintf(b, "  neighbor %s default-originate\n", id)
	}
	if s.AllowASIn > 0 {
		fmt.Fprintf(b, "  neighbor %s allowas-in %d\n", id, s.AllowASIn)
	}
	if s.MaximumPrefix > 0 {
		fmt.Fprintf(b, "  neighbor %s maximum-prefix %d\n", id, s.MaximumPrefix)
	}
	if s.PrefixListIn != "" {
		fmt.Fprintf(b, "  neighbor %s prefix-list %s in\n", id, s.PrefixListIn)
	}
	if s.PrefixListOut != "" {
		fmt.Fprintf(b, "  neighbor %s prefix-list %s out\n", id, s.PrefixListOut)
	}
	if s.RouteMapIn != "" {
		fmt.Fprintf(b, "  neighbor %s route-map %s in\n", id, s.RouteMapIn)
	}
	if s.RouteMapOut != "" {
		fmt.Fprintf(b, "  neighbor %s route-map %s out\n", id, s.RouteMapOut)
	}
}

// BGPNeighborAddrs are the addresses of the instance's BGP neighbours that
// are not shut down, for the auto input rule.
func BGPNeighborAddrs(in *fwconfig.Instance) []string {
	if !in.BGPRunning() {
		return nil
	}
	var out []string
	for _, n := range in.BGP.Neighbors {
		if n.Shutdown {
			continue
		}
		if a := canonAddr(n.Address); !slices.Contains(out, a) {
			out = append(out, a)
		}
	}
	sort.Strings(out)
	return out
}
