// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"fmt"
	"net/netip"
	"slices"
	"sort"
	"strings"

	"github.com/abundo/portitor/internal/fwconfig"
)

// FRRDaemons renders FRR's daemons file: zebra and staticd (always on),
// bgpd, ospfd, ospf6d, vrrpd and bfdd as the instance runs them.
func FRRDaemons(in *fwconfig.Instance) string {
	b := &strings.Builder{}
	fmt.Fprintf(b, "# Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	yes := func(on bool) string {
		if on {
			return "yes"
		}
		return "no"
	}
	fmt.Fprintf(b, "bgpd=%s\nospfd=%s\nospf6d=%s\nvrrpd=%s\nbfdd=%s\n", yes(in.BGPRunning()), yes(in.OSPFRunning(2)), yes(in.OSPFRunning(3)), yes(in.VRRPRunning()), yes(in.BFDRunning()))
	b.WriteString("ripd=no\nripngd=no\nisisd=no\npimd=no\npim6d=no\nldpd=no\nnhrpd=no\neigrpd=no\nbabeld=no\nsharpd=no\npbrd=no\nfabricd=no\npathd=no\n")
	b.WriteString("vtysh_enable=yes\n")
	b.WriteString("zebra_options=\"  -A 127.0.0.1 -s 90000000\"\n")
	b.WriteString("mgmtd_options=\"  -A 127.0.0.1\"\n")
	b.WriteString("bgpd_options=\"   -A 127.0.0.1\"\n")
	b.WriteString("ospfd_options=\"  -A 127.0.0.1\"\n")
	b.WriteString("ospf6d_options=\" -A ::1\"\n")
	b.WriteString("staticd_options=\"-A 127.0.0.1\"\n")
	if in.BFDRunning() {
		b.WriteString("bfdd_options=\"   -A 127.0.0.1\"\n")
	}
	return b.String()
}

// FRRVtyshConf renders vtysh.conf: the integrated config (frr.conf), which
// frr-reload.py needs to reload.
func FRRVtyshConf(in *fwconfig.Instance) string {
	return fmt.Sprintf("! Generated by portitor-agent, instance %s. Do not edit.\nservice integrated-vtysh-config\n", in.Name)
}

// frrPasswordWord comes before a neighbour's password in frr.conf, and
// ospfKeyWord before an interface's OSPF MD5 key; Bundle.Redacted masks
// what follows them.
const (
	frrPasswordWord = " password "
	ospfKeyWord     = " md5 "
)

// FRRConf renders FRR's integrated config (frr.conf) for an instance's
// routing policy, BGP, OSPF, VRRP and BFD. Static routes stay the agent's
// (kernel routes, proto 99): "redistribute static" is FRR's redistribute
// kernel; but a route with BFD is staticd's (writeBFDRoutes), so with
// those it is redistribute static as well.
func FRRConf(in *fwconfig.Instance) string {
	b := &strings.Builder{}
	fmt.Fprintf(b, "! Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	b.WriteString("frr defaults traditional\n")
	b.WriteString("log syslog informational\n")
	b.WriteString("!\n")
	writeRoutingPolicy(b, &in.RoutingPolicy)
	writeBFD(b, in)
	writeBFDRoutes(b, in)
	writeInterfaces(b, in)
	if in.BGPRunning() {
		writeBGP(b, in)
	}
	if in.OSPFRunning(2) {
		writeOSPF(b, in, in.OSPF, 2)
	}
	if in.OSPFRunning(3) {
		writeOSPF(b, in, in.OSPF6, 3)
	}
	b.WriteString("end\n")
	return b.String()
}

func writeRoutingPolicy(b *strings.Builder, rp *fwconfig.RoutingPolicy) {
	for _, pl := range rp.PrefixLists {
		kw := "ip"
		if pl.Family == "ipv6" {
			kw = "ipv6"
		}
		if pl.Description != "" {
			fmt.Fprintf(b, "%s prefix-list %s description %s\n", kw, pl.Name, pl.Description)
		}
		entries := slices.Clone(pl.Entries)
		sort.SliceStable(entries, func(i, j int) bool { return entries[i].Seq < entries[j].Seq })
		for _, e := range entries {
			fmt.Fprintf(b, "%s prefix-list %s seq %d %s %s", kw, pl.Name, e.Seq, e.Action, e.Prefix)
			if e.GE != 0 {
				fmt.Fprintf(b, " ge %d", e.GE)
			}
			if e.LE != 0 {
				fmt.Fprintf(b, " le %d", e.LE)
			}
			b.WriteString("\n")
		}
		if len(entries) == 0 {
			// An empty list must exist, and deny everything.
			fmt.Fprintf(b, "%s prefix-list %s seq 65535 deny any\n", kw, pl.Name)
		}
		b.WriteString("!\n")
	}
	for _, l := range rp.ASPathLists {
		for i, e := range l.Entries {
			fmt.Fprintf(b, "bgp as-path access-list %s seq %d %s %s\n", l.Name, (i+1)*5, e.Action, e.Regex)
		}
		if len(l.Entries) == 0 {
			fmt.Fprintf(b, "bgp as-path access-list %s seq 5 deny .*\n", l.Name)
		}
		b.WriteString("!\n")
	}
	for _, l := range rp.CommunityLists {
		kw, kind := "community-list", l.Kind
		if l.Large() {
			kw, kind = "large-community-list", strings.TrimPrefix(l.Kind, "large-")
		}
		for i, e := range l.Entries {
			fmt.Fprintf(b, "bgp %s %s %s seq %d %s %s\n", kw, kind, l.Name, (i+1)*5, e.Action, e.Value)
		}
		if len(l.Entries) == 0 {
			// An expanded list that matches nothing listed, as a list
			// can't be empty.
			fmt.Fprintf(b, "bgp %s expanded %s seq 5 deny .*\n", kw, l.Name)
		}
		b.WriteString("!\n")
	}
	families := map[string]string{}
	for _, pl := range rp.PrefixLists {
		families[pl.Name] = pl.Family
	}
	large := map[string]bool{}
	for _, l := range rp.CommunityLists {
		large[l.Name] = l.Large()
	}
	for _, m := range rp.RouteMaps {
		entries := slices.Clone(m.Entries)
		sort.SliceStable(entries, func(i, j int) bool { return entries[i].Seq < entries[j].Seq })
		if len(entries) == 0 {
			// A route map without entries denies everything.
			fmt.Fprintf(b, "route-map %s deny 65535\n", m.Name)
			if m.Description != "" {
				fmt.Fprintf(b, " description %s\n", m.Description)
			}
			b.WriteString("exit\n!\n")
		}
		for i, e := range entries {
			fmt.Fprintf(b, "route-map %s %s %d\n", m.Name, e.Action, e.Seq)
			desc := e.Description
			if desc == "" && i == 0 {
				desc = m.Description
			}
			if desc != "" {
				fmt.Fprintf(b, " description %s\n", desc)
			}
			ipKw := func(list string) string {
				if families[list] == "ipv6" {
					return "ipv6"
				}
				return "ip"
			}
			if e.MatchPrefixList != "" {
				fmt.Fprintf(b, " match %s address prefix-list %s\n", ipKw(e.MatchPrefixList), e.MatchPrefixList)
			}
			if e.MatchNextHop != "" {
				fmt.Fprintf(b, " match %s next-hop prefix-list %s\n", ipKw(e.MatchNextHop), e.MatchNextHop)
			}
			if e.MatchASPath != "" {
				fmt.Fprintf(b, " match as-path %s\n", e.MatchASPath)
			}
			if e.MatchCommunity != "" {
				if large[e.MatchCommunity] {
					fmt.Fprintf(b, " match large-community %s\n", e.MatchCommunity)
				} else {
					fmt.Fprintf(b, " match community %s\n", e.MatchCommunity)
				}
			}
			if e.MatchMetric != nil {
				fmt.Fprintf(b, " match metric %d\n", *e.MatchMetric)
			}
			if e.MatchTag != nil {
				fmt.Fprintf(b, " match tag %d\n", *e.MatchTag)
			}
			if e.SetLocalPreference != nil {
				fmt.Fprintf(b, " set local-preference %d\n", *e.SetLocalPreference)
			}
			if e.SetMetric != nil {
				fmt.Fprintf(b, " set metric %d\n", *e.SetMetric)
			}
			if e.SetWeight != nil {
				fmt.Fprintf(b, " set weight %d\n", *e.SetWeight)
			}
			if e.SetASPathPrepend != "" {
				fmt.Fprintf(b, " set as-path prepend %s\n", strings.Join(strings.Fields(e.SetASPathPrepend), " "))
			}
			if e.SetCommunity != "" {
				fmt.Fprintf(b, " set community %s", strings.Join(strings.Fields(e.SetCommunity), " "))
				if e.SetCommunityAdditive {
					b.WriteString(" additive")
				}
				b.WriteString("\n")
			}
			if e.SetLargeCommunity != "" {
				fmt.Fprintf(b, " set large-community %s\n", strings.Join(strings.Fields(e.SetLargeCommunity), " "))
			}
			if e.SetNextHop != "" {
				if a, err := netip.ParseAddr(e.SetNextHop); err == nil && a.Is6() {
					fmt.Fprintf(b, " set ipv6 next-hop global %s\n", a)
				} else {
					fmt.Fprintf(b, " set ip next-hop %s\n", e.SetNextHop)
				}
			}
			if e.SetOrigin != "" {
				fmt.Fprintf(b, " set origin %s\n", e.SetOrigin)
			}
			if e.OnMatchNext && e.Action == fwconfig.Permit {
				b.WriteString(" on-match next\n")
			}
			b.WriteString("exit\n!\n")
		}
	}
}

// writeBFD writes bfdd's profiles: one per interface with BFD.
func writeBFD(b *strings.Builder, in *fwconfig.Instance) {
	if !in.BFDRunning() {
		return
	}
	b.WriteString("bfd\n")
	for _, i := range in.BFD {
		fmt.Fprintf(b, " profile %s\n", fwconfig.BFDProfile(i.Name))
		if i.DetectMultiplier > 0 {
			fmt.Fprintf(b, "  detect-multiplier %d\n", i.DetectMultiplier)
		}
		if i.ReceiveInterval > 0 {
			fmt.Fprintf(b, "  receive-interval %d\n", i.ReceiveInterval)
		}
		if i.TransmitInterval > 0 {
			fmt.Fprintf(b, "  transmit-interval %d\n", i.TransmitInterval)
		}
		if i.Passive {
			b.WriteString("  passive-mode\n")
		}
		b.WriteString(" exit\n !\n")
	}
	b.WriteString("exit\n!\n")
}

// writeBFDRoutes writes the static routes with BFD, which staticd installs
// while the session to the gateway is up. The metric is FRR's distance.
func writeBFDRoutes(b *strings.Builder, in *fwconfig.Instance) {
	n := 0
	for _, r := range in.Routes {
		iface := in.RouteBFD(r)
		if iface == "" {
			continue
		}
		kw := "ip"
		gw, _ := fwconfig.ParseAddr(r.Gateway)
		if gw.Is6() {
			kw = "ipv6"
		}
		fmt.Fprintf(b, "%s route %s %s", kw, fwconfig.BFDRouteDest(r), gw)
		if r.Interface != "" {
			fmt.Fprintf(b, " %s", r.Interface)
		}
		if r.Metric > 0 {
			fmt.Fprintf(b, " %d", r.Metric)
		}
		fmt.Fprintf(b, " bfd profile %s\n", fwconfig.BFDProfile(iface))
		n++
	}
	if n > 0 {
		b.WriteString("!\n")
	}
}

func writeBGP(b *strings.Builder, in *fwconfig.Instance) {
	g := in.BGP
	fmt.Fprintf(b, "router bgp %d\n", g.ASN)
	if g.RouterID != "" {
		fmt.Fprintf(b, " bgp router-id %s\n", g.RouterID)
	}
	if g.LogNeighborChanges {
		b.WriteString(" bgp log-neighbor-changes\n")
	} else {
		b.WriteString(" no bgp log-neighbor-changes\n")
	}
	if !g.EBGPRequiresPolicy {
		b.WriteString(" no bgp ebgp-requires-policy\n")
	}
	// Address families are activated per neighbour.
	b.WriteString(" no bgp default ipv4-unicast\n")
	if g.GracefulRestart {
		b.WriteString(" bgp graceful-restart\n")
	}
	if g.MultipathRelax {
		b.WriteString(" bgp bestpath as-path multipath-relax\n")
	}
	if g.Keepalive != 0 {
		fmt.Fprintf(b, " timers bgp %d %d\n", g.Keepalive, holdOf(g.Keepalive, g.Hold))
	}
	for _, p := range g.PeerGroups {
		fmt.Fprintf(b, " neighbor %s peer-group\n", p.Name)
		writePeer(b, p.Name, p, false)
	}
	for _, p := range g.Neighbors {
		ip := canonAddr(p.Address)
		if p.RemoteAS != "" {
			fmt.Fprintf(b, " neighbor %s remote-as %s\n", ip, p.RemoteAS)
		}
		if p.PeerGroup != "" {
			fmt.Fprintf(b, " neighbor %s peer-group %s\n", ip, p.PeerGroup)
		}
		// A link-local neighbour: on its interface, with IPv4 routes over
		// the IPv6 session (RFC 8950).
		if p.Interface != "" {
			fmt.Fprintf(b, " neighbor %s interface %s\n", ip, p.Interface)
			fmt.Fprintf(b, " neighbor %s capability extended-nexthop\n", ip)
		}
		writePeer(b, ip, p, true)
		// BFD is per neighbour, never on a peer group: only the members on
		// an interface with BFD get it.
		if iface := in.NeighborBFD(p); iface != "" {
			fmt.Fprintf(b, " neighbor %s bfd\n", ip)
			fmt.Fprintf(b, " neighbor %s bfd profile %s\n", ip, fwconfig.BFDProfile(iface))
		}
	}
	for _, fam := range []string{"ipv4", "ipv6"} {
		writeAddressFamily(b, g, fam, in.HasBFDRoutes())
	}
	writeEVPNFamily(b, g)
	b.WriteString("exit\n!\n")
}

// holdOf is the hold time for a keepalive: three times it when not set.
func holdOf(keepalive, hold int) int {
	if hold == 0 {
		return keepalive * 3
	}
	return hold
}

func canonAddr(s string) string {
	if a, err := fwconfig.ParseAddr(s); err == nil {
		return a.String()
	}
	return s
}

// writePeer writes a neighbour's or peer group's session settings. A peer
// group's remote-as comes after it is declared.
func writePeer(b *strings.Builder, id string, p fwconfig.BGPPeer, neighbor bool) {
	if !neighbor && p.RemoteAS != "" {
		fmt.Fprintf(b, " neighbor %s remote-as %s\n", id, p.RemoteAS)
	}
	if p.Description != "" {
		fmt.Fprintf(b, " neighbor %s description %s\n", id, p.Description)
	}
	if p.Password != "" {
		fmt.Fprintf(b, " neighbor %s%s%s\n", id, frrPasswordWord, p.Password)
	}
	if p.EBGPMultihop > 0 {
		fmt.Fprintf(b, " neighbor %s ebgp-multihop %d\n", id, p.EBGPMultihop)
	}
	if p.UpdateSource != "" {
		fmt.Fprintf(b, " neighbor %s update-source %s\n", id, canonAddr(p.UpdateSource))
	}
	if p.Passive {
		fmt.Fprintf(b, " neighbor %s passive\n", id)
	}
	if p.Keepalive != 0 {
		fmt.Fprintf(b, " neighbor %s timers %d %d\n", id, p.Keepalive, holdOf(p.Keepalive, p.Hold))
	}
	if p.Shutdown {
		fmt.Fprintf(b, " neighbor %s shutdown\n", id)
	}
}

func familyOf(prefix string) string {
	if pfx, err := netip.ParsePrefix(prefix); err == nil && pfx.Addr().Is6() {
		return "ipv6"
	}
	return "ipv4"
}

// writeAddressFamily writes a BGP address family; staticRoutes: FRR has
// static routes (with BFD) that redistribute static takes too.
func writeAddressFamily(b *strings.Builder, g *fwconfig.BGP, fam string, staticRoutes bool) {
	af := &strings.Builder{}
	for _, n := range g.Networks {
		if familyOf(n.Prefix) != fam {
			continue
		}
		fmt.Fprintf(af, "  network %s", n.Prefix)
		if n.RouteMap != "" {
			fmt.Fprintf(af, " route-map %s", n.RouteMap)
		}
		af.WriteString("\n")
	}
	for _, a := range g.Aggregates {
		if familyOf(a.Prefix) != fam {
			continue
		}
		fmt.Fprintf(af, "  aggregate-address %s", a.Prefix)
		if a.ASSet {
			af.WriteString(" as-set")
		}
		if a.SummaryOnly {
			af.WriteString(" summary-only")
		}
		af.WriteString("\n")
	}
	for _, r := range g.Redistribute {
		if r.Family != fam {
			continue
		}
		for _, src := range frrSources(r.Source, fam, staticRoutes) {
			fmt.Fprintf(af, "  redistribute %s", src)
			if r.RouteMap != "" {
				fmt.Fprintf(af, " route-map %s", r.RouteMap)
			}
			af.WriteString("\n")
		}
	}
	if g.MaximumPaths > 0 {
		fmt.Fprintf(af, "  maximum-paths %d\n", g.MaximumPaths)
	}
	for _, p := range g.PeerGroups {
		writePeerFamily(af, p.Name, p, fam)
	}
	for _, p := range g.Neighbors {
		writePeerFamily(af, canonAddr(p.Address), p, fam)
	}
	if af.Len() == 0 {
		return
	}
	fmt.Fprintf(b, " !\n address-family %s unicast\n", fam)
	b.WriteString(af.String())
	b.WriteString(" exit-address-family\n")
}

// writeEVPNFamily writes the L2VPN EVPN address family: the peers that
// activate it and, with EVPN on, the VNIs of the vxlan devices zebra finds
// as bridge members.
func writeEVPNFamily(b *strings.Builder, g *fwconfig.BGP) {
	af := &strings.Builder{}
	for _, p := range g.PeerGroups {
		writePeerEVPN(af, p.Name, p.EVPN)
	}
	for _, p := range g.Neighbors {
		writePeerEVPN(af, canonAddr(p.Address), p.EVPN)
	}
	if g.EVPN {
		af.WriteString("  advertise-all-vni\n")
	}
	if af.Len() == 0 {
		return
	}
	b.WriteString(" !\n address-family l2vpn evpn\n")
	b.WriteString(af.String())
	b.WriteString(" exit-address-family\n")
}

func writePeerEVPN(b *strings.Builder, id string, s fwconfig.BGPEVPNFamily) {
	if !s.Activate {
		return
	}
	fmt.Fprintf(b, "  neighbor %s activate\n", id)
	if s.RouteReflectorClient {
		fmt.Fprintf(b, "  neighbor %s route-reflector-client\n", id)
	}
}

// frrSource is FRR's name of a redistribute source in an IP version.
func frrSource(src, fam string) string {
	switch src {
	case fwconfig.RedistStatic:
		return "kernel"
	case fwconfig.RedistOSPF:
		if fam == "ipv6" {
			return "ospf6"
		}
	}
	return src
}

// frrSources are FRR's sources of a redistribute source: static routes
// are the kernel's, and staticd's too when it has some (BFD).
func frrSources(src, fam string, staticRoutes bool) []string {
	if src == fwconfig.RedistStatic && staticRoutes {
		return []string{"kernel", "static"}
	}
	return []string{frrSource(src, fam)}
}

func writePeerFamily(b *strings.Builder, id string, p fwconfig.BGPPeer, fam string) {
	s := p.IPv4
	if fam == "ipv6" {
		s = p.IPv6
	}
	// Settings of a family that is not active would be refused.
	if !s.Activate {
		return
	}
	fmt.Fprintf(b, "  neighbor %s activate\n", id)
	if s.RouteReflectorClient {
		fmt.Fprintf(b, "  neighbor %s route-reflector-client\n", id)
	}
	if s.NextHopSelf {
		fmt.Fprintf(b, "  neighbor %s next-hop-self\n", id)
	}
	if s.RemovePrivateAS {
		fmt.Fprintf(b, "  neighbor %s remove-private-AS\n", id)
	}
	if s.SoftReconfiguration {
		fmt.Fprintf(b, "  neighbor %s soft-reconfiguration inbound\n", id)
	}
	if s.DefaultOriginate {
		fmt.Fprintf(b, "  neighbor %s default-originate\n", id)
	}
	if s.AllowASIn > 0 {
		fmt.Fprintf(b, "  neighbor %s allowas-in %d\n", id, s.AllowASIn)
	}
	if s.MaximumPrefix > 0 {
		fmt.Fprintf(b, "  neighbor %s maximum-prefix %d\n", id, s.MaximumPrefix)
	}
	if s.PrefixListIn != "" {
		fmt.Fprintf(b, "  neighbor %s prefix-list %s in\n", id, s.PrefixListIn)
	}
	if s.PrefixListOut != "" {
		fmt.Fprintf(b, "  neighbor %s prefix-list %s out\n", id, s.PrefixListOut)
	}
	if s.RouteMapIn != "" {
		fmt.Fprintf(b, "  neighbor %s route-map %s in\n", id, s.RouteMapIn)
	}
	if s.RouteMapOut != "" {
		fmt.Fprintf(b, "  neighbor %s route-map %s out\n", id, s.RouteMapOut)
	}
}

// BGPNeighborAddrs are the addresses of the instance's BGP neighbours that
// are not shut down, for the auto input rule.
func BGPNeighborAddrs(in *fwconfig.Instance) []string {
	if !in.BGPRunning() {
		return nil
	}
	var out []string
	for _, n := range in.BGP.Neighbors {
		if n.Shutdown {
			continue
		}
		if a := canonAddr(n.Address); !slices.Contains(out, a) {
			out = append(out, a)
		}
	}
	sort.Strings(out)
	return out
}

// ospfInterface is an interface's OSPF settings of one version, or nil.
func ospfInterface(o *fwconfig.OSPF, name string) *fwconfig.OSPFInterface {
	if o == nil || !o.Enabled {
		return nil
	}
	for i := range o.Interfaces {
		if o.Interfaces[i].Name == name {
			return &o.Interfaces[i]
		}
	}
	return nil
}

// writeInterfaces writes one interface block per interface with OSPF
// settings or virtual routers: OSPFv2's, OSPFv3's, then VRRP's.
func writeInterfaces(b *strings.Builder, in *fwconfig.Instance) {
	var names []string
	for _, o := range []*fwconfig.OSPF{in.OSPF, in.OSPF6} {
		if o == nil || !o.Enabled {
			continue
		}
		for _, ifc := range o.Interfaces {
			if !slices.Contains(names, ifc.Name) {
				names = append(names, ifc.Name)
			}
		}
	}
	for _, r := range in.VRRP {
		if !slices.Contains(names, r.Interface) {
			names = append(names, r.Interface)
		}
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(b, "interface %s\n", name)
		if ifc := ospfInterface(in.OSPF, name); ifc != nil {
			writeOSPFInterface(b, in, ifc, "ip ospf")
		}
		if ifc := ospfInterface(in.OSPF6, name); ifc != nil {
			writeOSPFInterface(b, in, ifc, "ipv6 ospf6")
		}
		for _, r := range in.VRRP {
			if r.Interface == name {
				writeVRRP(b, r)
			}
		}
		b.WriteString("exit\n!\n")
	}
}

// writeVRRP writes a virtual router's lines. vrrpd finds its macvlan
// devices (fwconfig.VRRPDevices) by parent and MAC address.
func writeVRRP(b *strings.Builder, r fwconfig.VRRP) {
	fmt.Fprintf(b, " vrrp %d\n", r.VRID)
	if r.Version == 2 {
		fmt.Fprintf(b, " vrrp %d version 2\n", r.VRID)
	}
	if r.Priority > 0 {
		fmt.Fprintf(b, " vrrp %d priority %d\n", r.VRID, r.Priority)
	}
	if r.AdvertisementInterval > 0 {
		fmt.Fprintf(b, " vrrp %d advertisement-interval %d\n", r.VRID, r.AdvertisementInterval)
	}
	if r.NoPreempt {
		fmt.Fprintf(b, " no vrrp %d preempt\n", r.VRID)
	}
	for _, a := range r.IPv4 {
		fmt.Fprintf(b, " vrrp %d ip %s\n", r.VRID, canonAddr(a))
	}
	for _, a := range r.IPv6 {
		fmt.Fprintf(b, " vrrp %d ipv6 %s\n", r.VRID, canonAddr(a))
	}
	if r.Shutdown {
		fmt.Fprintf(b, " vrrp %d shutdown\n", r.VRID)
	}
}

// VRRPInterfaces are the interfaces with virtual routers and their VRRP
// devices, where VRRP advertisements are heard and sent, for the auto
// rules.
func VRRPInterfaces(in *fwconfig.Instance) []string {
	var out []string
	for _, r := range in.VRRP {
		if !slices.Contains(out, r.Interface) {
			out = append(out, r.Interface)
		}
	}
	return in.AddVRRPDevices(out)
}

func writeOSPFInterface(b *strings.Builder, in *fwconfig.Instance, ifc *fwconfig.OSPFInterface, kw string) {
	if ifc.Area != "" {
		fmt.Fprintf(b, " %s area %s\n", kw, ifc.Area)
	}
	if ifc.Cost > 0 {
		fmt.Fprintf(b, " %s cost %d\n", kw, ifc.Cost)
	}
	if ifc.HelloInterval > 0 {
		fmt.Fprintf(b, " %s hello-interval %d\n", kw, ifc.HelloInterval)
	}
	if ifc.DeadInterval > 0 {
		fmt.Fprintf(b, " %s dead-interval %d\n", kw, ifc.DeadInterval)
	}
	if ifc.Priority != nil {
		fmt.Fprintf(b, " %s priority %d\n", kw, *ifc.Priority)
	}
	if ifc.NetworkType != "" {
		fmt.Fprintf(b, " %s network %s\n", kw, ifc.NetworkType)
	}
	if ifc.Passive {
		fmt.Fprintf(b, " %s passive\n", kw)
	}
	if ifc.AuthKey != "" {
		fmt.Fprintf(b, " %s authentication message-digest\n", kw)
		fmt.Fprintf(b, " %s message-digest-key %d%s%s\n", kw, ifc.AuthKeyID, ospfKeyWord, ifc.AuthKey)
	}
	if ifc.BFD && in.BFDOn(ifc.Name) != nil {
		fmt.Fprintf(b, " %s bfd\n", kw)
		fmt.Fprintf(b, " %s bfd profile %s\n", kw, fwconfig.BFDProfile(ifc.Name))
	}
}

// writeOSPF writes router ospf (version 2) or router ospf6 (3).
func writeOSPF(b *strings.Builder, in *fwconfig.Instance, o *fwconfig.OSPF, version int) {
	router, rid := "ospf", "ospf router-id"
	if version == 3 {
		router, rid = "ospf6", "ospf6 router-id"
	}
	fmt.Fprintf(b, "router %s\n", router)
	if o.RouterID != "" {
		fmt.Fprintf(b, " %s %s\n", rid, o.RouterID)
	}
	if o.LogAdjacencyChanges {
		b.WriteString(" log-adjacency-changes\n")
	}
	if o.ReferenceBandwidth > 0 {
		fmt.Fprintf(b, " auto-cost reference-bandwidth %d\n", o.ReferenceBandwidth)
	}
	if o.MaximumPaths > 0 {
		fmt.Fprintf(b, " maximum-paths %d\n", o.MaximumPaths)
	}
	for _, n := range o.Networks {
		fmt.Fprintf(b, " network %s area %s\n", n.Prefix, n.Area)
	}
	for _, a := range o.Areas {
		if a.Type != fwconfig.AreaStub && a.Type != fwconfig.AreaNSSA {
			continue
		}
		fmt.Fprintf(b, " area %s %s", a.ID, a.Type)
		if a.NoSummary {
			b.WriteString(" no-summary")
		}
		b.WriteString("\n")
	}
	for _, r := range o.Ranges {
		fmt.Fprintf(b, " area %s range %s", r.Area, r.Prefix)
		switch {
		case r.NotAdvertise:
			b.WriteString(" not-advertise")
		case r.Cost > 0:
			fmt.Fprintf(b, " cost %d", r.Cost)
		}
		b.WriteString("\n")
	}
	for _, s := range o.Summaries {
		fmt.Fprintf(b, " summary-address %s", s.Prefix)
		if s.NotAdvertise {
			b.WriteString(" no-advertise")
		}
		b.WriteString("\n")
	}
	for _, r := range o.Redistribute {
		srcs := []string{r.Source}
		if r.Source == fwconfig.RedistStatic {
			srcs = frrSources(r.Source, "", in.HasBFDRoutes())
		}
		for _, src := range srcs {
			fmt.Fprintf(b, " redistribute %s", src)
			if r.Metric > 0 {
				fmt.Fprintf(b, " metric %d", r.Metric)
			}
			if r.MetricType > 0 {
				fmt.Fprintf(b, " metric-type %d", r.MetricType)
			}
			if r.RouteMap != "" {
				fmt.Fprintf(b, " route-map %s", r.RouteMap)
			}
			b.WriteString("\n")
		}
	}
	if o.DefaultOriginate {
		b.WriteString(" default-information originate")
		if o.DefaultAlways {
			b.WriteString(" always")
		}
		b.WriteString("\n")
	}
	b.WriteString("exit\n!\n")
}

// OSPFActive returns the interfaces where an OSPF version sends and hears
// hellos (with an area, not passive), and the OSPFv2 network statements'
// prefixes, for the auto rules.
func OSPFActive(in *fwconfig.Instance, version int) (ifaces, networks []string) {
	o := in.OSPF
	if version == 3 {
		o = in.OSPF6
	}
	if o == nil || !o.Enabled {
		return nil, nil
	}
	for _, ifc := range o.Interfaces {
		if ifc.Area != "" && !ifc.Passive {
			ifaces = append(ifaces, ifc.Name)
		}
	}
	for _, n := range o.Networks {
		networks = append(networks, n.Prefix)
	}
	sort.Strings(ifaces)
	sort.Strings(networks)
	return ifaces, networks
}
