// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"strings"
	"testing"

	"github.com/abundo/portitor/internal/fwconfig"
)

func TestFRRConf(t *testing.T) {
	b := sampleBundle(t)
	conf := mustFile(t, b, "/etc/portitor/instances/guest/frr/frr.conf")
	for _, want := range []string{
		"! Generated by portitor-agent, instance guest.",
		"ip prefix-list ours seq 5 permit 192.168.0.0/16 le 24\n",
		"bgp as-path access-list short seq 5 permit ^65000_[0-9]+$\n",
		"bgp community-list standard noexport seq 5 permit 65000:666 no-export\n",
		"route-map from-upstream deny 10\n match community noexport\nexit\n",
		"route-map from-upstream permit 20\n match as-path short\n set local-preference 200\n set community 65010:1 additive\nexit\n",
		"route-map connected permit 10\n match ip address prefix-list ours\n",
		"router bgp 65010\n bgp router-id 10.255.0.2\n bgp log-neighbor-changes\n no bgp ebgp-requires-policy\n no bgp default ipv4-unicast\n",
		" neighbor upstream peer-group\n neighbor upstream remote-as 65000\n neighbor upstream password s3cret\n",
		" neighbor 10.255.0.1 peer-group upstream\n neighbor 10.255.0.1 description main\n",
		" neighbor 2001:db8::1 remote-as 65001\n neighbor 2001:db8::1 ebgp-multihop 2\n neighbor 2001:db8::1 update-source eth2\n",
		" address-family ipv4 unicast\n  network 192.168.50.0/24\n  aggregate-address 192.168.0.0/16 summary-only\n  redistribute connected route-map connected\n",
		"  neighbor upstream activate\n  neighbor upstream soft-reconfiguration inbound\n  neighbor upstream prefix-list ours out\n  neighbor upstream route-map from-upstream in\n",
		" address-family ipv6 unicast\n  neighbor 2001:db8::1 activate\n  neighbor 2001:db8::1 next-hop-self\n  neighbor 2001:db8::1 remove-private-AS\n exit-address-family\n",
	} {
		if !strings.Contains(conf, want) {
			t.Errorf("frr.conf lacks %q:\n%s", want, conf)
		}
	}
	// The neighbour in the group has no IPv4 settings of its own.
	if strings.Contains(conf, "neighbor 10.255.0.1 activate") {
		t.Error("group member activated on its own")
	}
	mustFile(t, b, "/etc/portitor/instances/guest/frr/daemons")
	if v := mustFile(t, b, "/etc/portitor/instances/guest/frr/vtysh.conf"); !strings.Contains(v, "service integrated-vtysh-config\n") {
		t.Errorf("vtysh.conf: %s", v)
	}
	// main has no BGP: FRR's files are not written.
	if b.File("/etc/frr/frr.conf") != nil {
		t.Error("frr.conf for an instance without BGP")
	}
}

// A link-local neighbour peers on its interface, with IPv4 over IPv6.
func TestFRRLinkLocalNeighbor(t *testing.T) {
	doc := fwconfig.SampleDocument()
	g := doc.Instance("guest").BGP
	g.Neighbors = append(g.Neighbors, fwconfig.BGPPeer{
		Address: "fe80::1", Interface: "eth2", RemoteAS: "external",
		IPv4: fwconfig.BGPAddressFamily{Activate: true}, IPv6: fwconfig.BGPAddressFamily{Activate: true},
	})
	b, err := Render(doc, Options{Paths: DefaultPaths(), Units: DefaultUnits()})
	if err != nil {
		t.Fatal(err)
	}
	conf := mustFile(t, b, "/etc/portitor/instances/guest/frr/frr.conf")
	for _, want := range []string{
		" neighbor fe80::1 remote-as external\n neighbor fe80::1 interface eth2\n neighbor fe80::1 capability extended-nexthop\n",
		"  neighbor fe80::1 activate\n",
	} {
		if !strings.Contains(conf, want) {
			t.Errorf("frr.conf lacks %q:\n%s", want, conf)
		}
	}
	if strings.Count(conf, "neighbor fe80::1 activate") != 2 {
		t.Errorf("not activated in both families:\n%s", conf)
	}
}

func TestFRRDefaultInstanceFiles(t *testing.T) {
	doc := fwconfig.SampleDocument()
	doc.Instance("main").BGP = &fwconfig.BGP{Enabled: true, ASN: 65000}
	b, err := Render(doc, Options{Paths: DefaultPaths(), Units: DefaultUnits()})
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range []string{"/etc/frr/frr.conf", "/etc/frr/daemons", "/etc/frr/vtysh.conf"} {
		mustFile(t, b, f)
	}
	conf := mustFile(t, b, "/etc/frr/frr.conf")
	// No neighbours, networks or redistribution: no address families.
	if strings.Contains(conf, "address-family") {
		t.Errorf("empty address family:\n%s", conf)
	}
	if got := DefaultUnits().FRR(doc.Instance("main")); got != "frr.service" {
		t.Errorf("unit %s", got)
	}
	if got := DefaultUnits().FRR(doc.Instance("guest")); got != "portitor-frr@guest.service" {
		t.Errorf("unit %s", got)
	}
}

func TestFRRPasswordsRedacted(t *testing.T) {
	b := sampleBundle(t)
	f := b.File("/etc/portitor/instances/guest/frr/frr.conf")
	if !f.Secret || f.Mode != 0o640 {
		t.Fatalf("frr.conf secret %v mode %o", f.Secret, f.Mode)
	}
	for _, r := range b.Redacted() {
		if r.Path != f.Path {
			continue
		}
		if strings.Contains(r.Content, "s3cret") || !strings.Contains(r.Content, " neighbor upstream password <redacted>\n") {
			t.Errorf("not redacted:\n%s", r.Content)
		}
	}
}

// Empty lists and route maps exist in FRR and match nothing, as an empty
// list's references would otherwise be refused or match everything.
func TestFRREmptyPolicyObjects(t *testing.T) {
	in := &fwconfig.Instance{Name: "x", RoutingPolicy: fwconfig.RoutingPolicy{
		PrefixLists:    []fwconfig.PrefixList{{Name: "p4", Family: "ipv4"}, {Name: "p6", Family: "ipv6"}},
		ASPathLists:    []fwconfig.ASPathList{{Name: "a"}},
		CommunityLists: []fwconfig.CommunityList{{Name: "c", Kind: fwconfig.CommunityStandard}, {Name: "l", Kind: fwconfig.CommunityLargeStandard}},
		RouteMaps:      []fwconfig.RouteMap{{Name: "m", Description: "none yet"}},
	}}
	conf := FRRConf(in)
	for _, want := range []string{
		"ip prefix-list p4 seq 65535 deny any\n",
		"ipv6 prefix-list p6 seq 65535 deny any\n",
		"bgp as-path access-list a seq 5 deny .*\n",
		"bgp community-list expanded c seq 5 deny .*\n",
		"bgp large-community-list expanded l seq 5 deny .*\n",
		"route-map m deny 65535\n description none yet\nexit\n",
	} {
		if !strings.Contains(conf, want) {
			t.Errorf("lacks %q:\n%s", want, conf)
		}
	}
	if strings.Contains(conf, "router bgp") {
		t.Error("router bgp without BGP")
	}
}

func TestFRRRouteMapSets(t *testing.T) {
	five := int64(5)
	in := &fwconfig.Instance{Name: "x", RoutingPolicy: fwconfig.RoutingPolicy{
		PrefixLists:    []fwconfig.PrefixList{{Name: "six", Family: "ipv6"}},
		CommunityLists: []fwconfig.CommunityList{{Name: "lg", Kind: fwconfig.CommunityLargeStandard}},
		RouteMaps: []fwconfig.RouteMap{{Name: "m", Entries: []fwconfig.RouteMapEntry{
			{Seq: 20, Action: fwconfig.Permit, SetNextHop: "192.0.2.1", SetCommunity: "none"},
			{Seq: 10, Action: fwconfig.Permit, MatchPrefixList: "six", MatchNextHop: "six", MatchCommunity: "lg", MatchMetric: &five,
				SetMetric: &five, SetWeight: &five, SetASPathPrepend: "65010  65010", SetLargeCommunity: "1:2:3",
				SetNextHop: "2001:db8::5", SetOrigin: "igp", OnMatchNext: true},
			{Seq: 30, Action: fwconfig.Deny, OnMatchNext: true},
		}}},
	}}
	conf := FRRConf(in)
	want := "route-map m permit 10\n" +
		" match ipv6 address prefix-list six\n match ipv6 next-hop prefix-list six\n match large-community lg\n match metric 5\n" +
		" set metric 5\n set weight 5\n set as-path prepend 65010 65010\n set large-community 1:2:3\n" +
		" set ipv6 next-hop global 2001:db8::5\n set origin igp\n on-match next\nexit\n!\n" +
		"route-map m permit 20\n set community none\n set ip next-hop 192.0.2.1\nexit\n!\n" +
		"route-map m deny 30\nexit\n"
	if !strings.Contains(conf, want) {
		t.Errorf("want\n%s\ngot\n%s", want, conf)
	}
}

func TestBGPAutoRules(t *testing.T) {
	nft := mustFile(t, sampleBundle(t), "/etc/portitor/instances/guest/nftables.nft")
	for _, want := range []string{
		"set AUTO_bgp_neighbours_v4 {\n\t\ttype ipv4_addr\n\t\tflags interval\n\t\tauto-merge\n\t\telements = { 10.255.0.1 }\n\t}",
		"set AUTO_bgp_neighbours_v6 {\n\t\ttype ipv6_addr\n\t\tflags interval\n\t\tauto-merge\n\t\telements = { 2001:db8::1 }\n\t}",
		`ip saddr @AUTO_bgp_neighbours_v4 tcp dport 179 accept comment "auto: bgp"`,
		`ip6 saddr @AUTO_bgp_neighbours_v6 tcp dport 179 accept comment "auto: bgp"`,
		`ip daddr @AUTO_bgp_neighbours_v4 tcp dport 179 accept comment "auto: bgp"`,
		`ip6 daddr @AUTO_bgp_neighbours_v6 tcp dport 179 accept comment "auto: bgp"`,
	} {
		if !strings.Contains(nft, want) {
			t.Errorf("ruleset lacks %q", want)
		}
	}
	// A shut down neighbour gets no rule; with none left, there is none.
	doc := fwconfig.SampleDocument()
	in := doc.Instance("guest")
	for i := range in.BGP.Neighbors {
		in.BGP.Neighbors[i].Shutdown = true
	}
	for _, r := range AutoInputRules(in) {
		if r.Service == BGPService {
			t.Errorf("auto rule for shut down neighbours: %+v", r)
		}
	}
	if strings.Contains(Nftables(in, nil, DefaultPaths()), "dport 179") {
		t.Error("output rule for shut down neighbours")
	}
}

func TestFRREVPN(t *testing.T) {
	// Off and no peer activates it: no address family.
	if conf := mustFile(t, sampleBundle(t), "/etc/portitor/instances/guest/frr/frr.conf"); strings.Contains(conf, "l2vpn evpn") {
		t.Errorf("evpn family without evpn:\n%s", conf)
	}
	doc := fwconfig.SampleDocument()
	g := doc.Instance("guest").BGP
	g.EVPN = true
	g.PeerGroups[0].EVPN = fwconfig.BGPEVPNFamily{Activate: true}
	g.Neighbors = append(g.Neighbors, fwconfig.BGPPeer{Address: "10.255.0.9", RemoteAS: "internal",
		EVPN: fwconfig.BGPEVPNFamily{Activate: true, RouteReflectorClient: true}})
	b, err := Render(doc, Options{Paths: DefaultPaths(), Units: DefaultUnits()})
	if err != nil {
		t.Fatal(err)
	}
	conf := mustFile(t, b, "/etc/portitor/instances/guest/frr/frr.conf")
	want := " !\n address-family l2vpn evpn\n  neighbor upstream activate\n  neighbor 10.255.0.9 activate\n  neighbor 10.255.0.9 route-reflector-client\n  advertise-all-vni\n exit-address-family\n"
	if !strings.Contains(conf, want) {
		t.Errorf("frr.conf lacks %q:\n%s", want, conf)
	}
}

func TestVXLANAutoRules(t *testing.T) {
	nft := mustFile(t, sampleBundle(t), "/etc/portitor/instances/guest/nftables.nft")
	for _, want := range []string{
		`ip saddr { 192.168.50.2, 192.168.50.3 } iifname { "eth2", "vrrp4-50-eth2", "vrrp6-50-eth2" } udp dport 4789 accept comment "auto: vxlan vx200"`,
		`oifname "eth2" ip daddr { 192.168.50.2, 192.168.50.3 } udp dport 4789 accept comment "auto: vxlan vx200"`,
	} {
		if !strings.Contains(nft, want) {
			t.Errorf("ruleset lacks %q:\n%s", want, nft)
		}
	}
	// With EVPN and no remotes, from any VTEP.
	doc := fwconfig.SampleDocument()
	in := doc.Instance("guest")
	x := in.Interface("vx200").VXLAN
	x.Remotes, x.Device, x.Port = nil, "", 8472
	nft = Nftables(in, nil, DefaultPaths())
	for _, want := range []string{
		`udp dport 8472 accept comment "auto: vxlan vx200"`,
	} {
		if strings.Count(nft, want) != 2 {
			t.Errorf("ruleset lacks input and output %q:\n%s", want, nft)
		}
	}
}

func TestFRROSPF(t *testing.T) {
	b := sampleBundle(t)
	conf := mustFile(t, b, "/etc/portitor/instances/guest/frr/frr.conf")
	for _, want := range []string{
		// One interface block holds both versions.
		"interface lk-main\n ip ospf area 0.0.0.0\n ip ospf hello-interval 5\n ip ospf dead-interval 20\n ip ospf network point-to-point\n" +
			" ip ospf authentication message-digest\n ip ospf message-digest-key 1 md5 k3y\n ipv6 ospf6 area 0.0.0.0\nexit\n",
		"interface eth2\n ip ospf area 0.0.0.1\n ip ospf cost 100\n ip ospf priority 0\n ip ospf passive\n vrrp 50\n",
		"router ospf\n ospf router-id 10.255.0.2\n log-adjacency-changes\n auto-cost reference-bandwidth 10000\n" +
			" area 0.0.0.1 stub no-summary\n area 0.0.0.1 range 192.168.50.0/23 cost 10\n summary-address 172.16.0.0/12\n" +
			" redistribute kernel metric 50 metric-type 1 route-map connected\n redistribute bgp\n default-information originate\nexit\n",
		"router ospf6\n ospf6 router-id 10.255.0.2\n redistribute connected\nexit\n",
		// BGP redistributes OSPF.
		"  redistribute ospf\n",
	} {
		if !strings.Contains(conf, want) {
			t.Errorf("frr.conf lacks %q:\n%s", want, conf)
		}
	}
	daemons := mustFile(t, b, "/etc/portitor/instances/guest/frr/daemons")
	if !strings.Contains(daemons, "bgpd=yes\nospfd=yes\nospf6d=yes\n") {
		t.Errorf("daemons:\n%s", daemons)
	}
	for _, r := range b.Redacted() {
		if r.Path == "/etc/portitor/instances/guest/frr/frr.conf" && (strings.Contains(r.Content, "k3y") || !strings.Contains(r.Content, " ip ospf message-digest-key 1 md5 <redacted>\n")) {
			t.Errorf("OSPF key not redacted:\n%s", r.Content)
		}
	}

	// OSPF alone runs FRR, without bgpd; an OSPF key alone makes frr.conf
	// secret.
	doc := fwconfig.SampleDocument()
	in := doc.Instance("guest")
	in.BGP, in.OSPF6 = nil, nil
	in.RoutingPolicy.RouteMaps[0].Entries = nil
	b, err := Render(doc, Options{Paths: DefaultPaths(), Units: DefaultUnits()})
	if err != nil {
		t.Fatal(err)
	}
	if d := mustFile(t, b, "/etc/portitor/instances/guest/frr/daemons"); !strings.Contains(d, "bgpd=no\nospfd=yes\nospf6d=no\n") {
		t.Errorf("daemons:\n%s", d)
	}
	f := b.File("/etc/portitor/instances/guest/frr/frr.conf")
	if !f.Secret || strings.Contains(f.Content, "router bgp") || strings.Contains(f.Content, "ipv6 ospf6") {
		t.Errorf("secret %v:\n%s", f.Secret, f.Content)
	}
}

func TestOSPFAutoRules(t *testing.T) {
	nft := mustFile(t, sampleBundle(t), "/etc/portitor/instances/guest/nftables.nft")
	for _, want := range []string{
		`iifname "lk-main" meta nfproto ipv4 meta l4proto 89 accept comment "auto: ospf"`,
		`iifname "lk-main" meta nfproto ipv6 meta l4proto 89 accept comment "auto: ospfv3"`,
		`oifname "lk-main" meta nfproto ipv4 meta l4proto 89 accept comment "auto: ospf"`,
		`oifname "lk-main" meta nfproto ipv6 meta l4proto 89 accept comment "auto: ospfv3"`,
	} {
		if !strings.Contains(nft, want) {
			t.Errorf("ruleset lacks %q", want)
		}
	}
	// A passive interface sends and hears no hellos.
	if strings.Contains(nft, `"eth2" meta nfproto ipv4 meta l4proto 89`) {
		t.Error("rule for a passive interface")
	}
	// Network statements: from and to their prefixes, and to the OSPF
	// groups.
	doc := fwconfig.SampleDocument()
	in := doc.Instance("guest")
	in.OSPF.Networks = []fwconfig.OSPFNetwork{{Prefix: "10.255.0.0/30", Area: "0.0.0.0"}}
	for i := range in.OSPF.Interfaces {
		in.OSPF.Interfaces[i].Area = ""
	}
	in.OSPF6 = nil
	var rules []string
	for _, r := range AutoInputRules(in) {
		if r.Service == OSPFService {
			rules = append(rules, r.matches(in)...)
		}
	}
	if len(rules) != 1 || rules[0] != "ip saddr @AUTO_ospf_networks_v4 meta nfproto ipv4 meta l4proto 89" {
		t.Errorf("input: %q", rules)
	}
	out := OSPFOutputMatches(in)
	if len(out) != 1 || out[0].match != "ip daddr { 10.255.0.0/30, 224.0.0.5, 224.0.0.6 } meta nfproto ipv4 meta l4proto 89" {
		t.Errorf("output: %+v", out)
	}
}

func TestFRRVRRP(t *testing.T) {
	b := sampleBundle(t)
	conf := mustFile(t, b, "/etc/portitor/instances/guest/frr/frr.conf")
	// The virtual router is in its interface's block, after OSPF's.
	want := " ip ospf passive\n vrrp 50\n vrrp 50 priority 200\n vrrp 50 advertisement-interval 500\n" +
		" vrrp 50 ip 192.168.50.254\n vrrp 50 ipv6 fe80::50\nexit\n"
	if !strings.Contains(conf, want) {
		t.Errorf("frr.conf lacks %q:\n%s", want, conf)
	}
	daemons := mustFile(t, b, "/etc/portitor/instances/guest/frr/daemons")
	if !strings.Contains(daemons, "vrrpd=yes\n") || strings.Count(daemons, "vrrpd=") != 1 {
		t.Errorf("daemons:\n%s", daemons)
	}

	// VRRP alone runs FRR with vrrpd only; version 2, no preempt, shut down.
	doc := fwconfig.SampleDocument()
	in := doc.Instance("guest")
	in.BGP, in.OSPF, in.OSPF6 = nil, nil, nil
	in.VRRP[0] = fwconfig.VRRP{Interface: "eth2", VRID: 7, Version: 2, NoPreempt: true, Shutdown: true, IPv4: []string{"192.168.50.254"}}
	b, err := Render(doc, Options{Paths: DefaultPaths(), Units: DefaultUnits()})
	if err != nil {
		t.Fatal(err)
	}
	conf = mustFile(t, b, "/etc/portitor/instances/guest/frr/frr.conf")
	want = "interface eth2\n vrrp 7\n vrrp 7 version 2\n no vrrp 7 preempt\n vrrp 7 ip 192.168.50.254\n vrrp 7 shutdown\nexit\n"
	if !strings.Contains(conf, want) {
		t.Errorf("frr.conf lacks %q:\n%s", want, conf)
	}
	daemons = mustFile(t, b, "/etc/portitor/instances/guest/frr/daemons")
	if !strings.Contains(daemons, "bgpd=no\nospfd=no\nospf6d=no\nvrrpd=yes\n") {
		t.Errorf("daemons:\n%s", daemons)
	}
}

func TestVRRPAutoRules(t *testing.T) {
	nft := mustFile(t, sampleBundle(t), "/etc/portitor/instances/guest/nftables.nft")
	for _, want := range []string{
		`iifname { "eth2", "vrrp4-50-eth2", "vrrp6-50-eth2" } meta l4proto 112 accept comment "auto: vrrp"`,
		`oifname { "eth2", "vrrp4-50-eth2", "vrrp6-50-eth2" } meta l4proto 112 accept comment "auto: vrrp"`,
		// A rule on the interface also matches what comes to the
		// virtual router's MAC address, on its devices.
		`iifname { "eth2", "vrrp4-50-eth2", "vrrp6-50-eth2" } oifname "lk-main" counter accept`,
	} {
		if !strings.Contains(nft, want) {
			t.Errorf("ruleset lacks %q:\n%s", want, nft)
		}
	}
}

func TestFRRBFD(t *testing.T) {
	doc := fwconfig.SampleDocument()
	in := doc.Instance("guest")
	in.BFD = []fwconfig.BFDInterface{{Name: "lk-main", DetectMultiplier: 5, ReceiveInterval: 100, TransmitInterval: 150, Passive: true}}
	in.Routes[0].BFD = true
	in.BGP.PeerGroups[0].BFD = true
	in.BGP.Neighbors[1].BFD = true // not on an interface with BFD
	in.OSPF.Interfaces[0].BFD = true
	in.OSPF6.Interfaces[0].BFD = true
	in.BGP.Redistribute = append(in.BGP.Redistribute, fwconfig.BGPRedistribute{Family: "ipv4", Source: fwconfig.RedistStatic})
	b, err := Render(doc, Options{Paths: DefaultPaths(), Units: DefaultUnits()})
	if err != nil {
		t.Fatal(err)
	}
	conf := mustFile(t, b, "/etc/portitor/instances/guest/frr/frr.conf")
	for _, want := range []string{
		"bfd\n profile if-lk-main\n  detect-multiplier 5\n  receive-interval 100\n  transmit-interval 150\n  passive-mode\n exit\n !\nexit\n",
		"ip route 0.0.0.0/0 10.255.0.1 bfd profile if-lk-main\n",
		" ip ospf bfd\n ip ospf bfd profile if-lk-main\n",
		" ipv6 ospf6 bfd\n ipv6 ospf6 bfd profile if-lk-main\n",
		" neighbor 10.255.0.1 bfd\n neighbor 10.255.0.1 bfd profile if-lk-main\n",
		"  redistribute kernel\n  redistribute static\n",
		// OSPF's redistribute static takes staticd's routes too.
		" redistribute kernel metric 50 metric-type 1 route-map connected\n redistribute static metric 50 metric-type 1 route-map connected\n",
	} {
		if !strings.Contains(conf, want) {
			t.Errorf("frr.conf lacks %q:\n%s", want, conf)
		}
	}
	if strings.Contains(conf, "2001:db8::1 bfd") || strings.Contains(conf, "upstream bfd") {
		t.Errorf("BFD off its interfaces, or on a peer group:\n%s", conf)
	}
	daemons := mustFile(t, b, "/etc/portitor/instances/guest/frr/daemons")
	if !strings.Contains(daemons, "bfdd=yes\n") || strings.Count(daemons, "bfdd=") != 1 {
		t.Errorf("daemons:\n%s", daemons)
	}
	nft := mustFile(t, b, "/etc/portitor/instances/guest/nftables.nft")
	for _, want := range []string{
		`iifname "lk-main" udp dport 3784 accept comment "auto: bfd"`,
		`oifname "lk-main" udp dport 3784 accept comment "auto: bfd"`,
	} {
		if !strings.Contains(nft, want) {
			t.Errorf("nftables lacks %q", want)
		}
	}

	// Without BFD the same document renders as before.
	plain := mustFile(t, sampleBundle(t), "/etc/portitor/instances/guest/frr/frr.conf")
	if strings.Contains(plain, "bfd") {
		t.Errorf("BFD without BFD interfaces:\n%s", plain)
	}
}
