// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/abundo/portitor/internal/fwconfig"
)

// RadvdConf renders radvd's config for an instance's router
// advertisements.
func RadvdConf(in *fwconfig.Instance) string {
	b := &strings.Builder{}
	fmt.Fprintf(b, "# Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	ras := append([]fwconfig.RAInterface(nil), in.RA...)
	sort.Slice(ras, func(i, j int) bool { return ras[i].Interface < ras[j].Interface })
	onOff := map[bool]string{true: "on", false: "off"}
	for _, ra := range ras {
		fmt.Fprintf(b, "\ninterface %s {\n", ra.Interface)
		b.WriteString("\tAdvSendAdvert on;\n")
		// The interface may come up after radvd starts (VLAN, WireGuard).
		b.WriteString("\tIgnoreIfMissing on;\n")
		fmt.Fprintf(b, "\tAdvManagedFlag %s;\n", onOff[ra.Managed])
		fmt.Fprintf(b, "\tAdvOtherConfigFlag %s;\n", onOff[ra.Other])
		for _, p := range ra.Prefixes {
			fmt.Fprintf(b, "\n\tprefix %s {\n", p.Prefix)
			b.WriteString("\t\tAdvOnLink on;\n")
			fmt.Fprintf(b, "\t\tAdvAutonomous %s;\n", onOff[p.Autonomous])
			b.WriteString("\t};\n")
		}
		if len(ra.RDNSS) > 0 {
			fmt.Fprintf(b, "\n\tRDNSS %s {\n\t};\n", strings.Join(ra.RDNSS, " "))
		}
		if len(ra.DNSSL) > 0 {
			fmt.Fprintf(b, "\n\tDNSSL %s {\n\t};\n", strings.Join(ra.DNSSL, " "))
		}
		if ra.NAT64Prefix != "" {
			fmt.Fprintf(b, "\n\tnat64prefix %s {\n\t};\n", ra.NAT64Prefix)
		}
		b.WriteString("};\n")
	}
	return b.String()
}
