// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"encoding/json"
	"fmt"
	"net/netip"
	"path/filepath"
	"sort"
	"strings"

	"github.com/abundo/portitor/internal/fwconfig"
)

// RadvdConf renders radvd's config for an instance's router
// advertisements.
func RadvdConf(in *fwconfig.Instance) string {
	b := &strings.Builder{}
	fmt.Fprintf(b, "# Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	ras := append([]fwconfig.RAInterface(nil), in.RA...)
	sort.Slice(ras, func(i, j int) bool { return ras[i].Interface < ras[j].Interface })
	onOff := map[bool]string{true: "on", false: "off"}
	for _, ra := range ras {
		fmt.Fprintf(b, "\ninterface %s {\n", ra.Interface)
		b.WriteString("\tAdvSendAdvert on;\n")
		// The interface may come up after radvd starts (VLAN, WireGuard).
		b.WriteString("\tIgnoreIfMissing on;\n")
		fmt.Fprintf(b, "\tAdvManagedFlag %s;\n", onOff[ra.Managed])
		fmt.Fprintf(b, "\tAdvOtherConfigFlag %s;\n", onOff[ra.Other])
		for _, p := range ra.Prefixes {
			fmt.Fprintf(b, "\n\tprefix %s {\n", p.Prefix)
			b.WriteString("\t\tAdvOnLink on;\n")
			fmt.Fprintf(b, "\t\tAdvAutonomous %s;\n", onOff[p.Autonomous])
			b.WriteString("\t};\n")
		}
		if len(ra.RDNSS) > 0 {
			fmt.Fprintf(b, "\n\tRDNSS %s {\n\t};\n", strings.Join(ra.RDNSS, " "))
		}
		if len(ra.DNSSL) > 0 {
			fmt.Fprintf(b, "\n\tDNSSL %s {\n\t};\n", strings.Join(ra.DNSSL, " "))
		}
		b.WriteString("};\n")
	}
	return b.String()
}

// DHCP6Subnets returns the instance's IPv6 DHCP subnets, sorted by prefix.
func DHCP6Subnets(in *fwconfig.Instance) []fwconfig.DHCPSubnet {
	var out []fwconfig.DHCPSubnet
	if !in.DHCP.Enabled {
		return nil
	}
	for _, s := range in.DHCP.Subnets {
		if fwconfig.AddrFamily(s.Prefix) == "ipv6" {
			out = append(out, s)
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Prefix < out[j].Prefix })
	return out
}

func dhcp6Interfaces(in *fwconfig.Instance) []string {
	var ifs []string
	for _, s := range DHCP6Subnets(in) {
		ifs = appendUnique(ifs, s.Interface)
	}
	sort.Strings(ifs)
	return ifs
}

type kea6Subnet struct {
	ID           int               `json:"id"`
	Subnet       string            `json:"subnet"`
	Interface    string            `json:"interface"`
	Pools        []kea6Pool        `json:"pools,omitempty"`
	OptionData   []kea6Option      `json:"option-data,omitempty"`
	Reservations []kea6Reservation `json:"reservations,omitempty"`
}

type kea6Pool struct {
	Pool string `json:"pool"`
}

type kea6Option struct {
	Name string `json:"name"`
	Data string `json:"data"`
}

type kea6Reservation struct {
	HWAddress   string   `json:"hw-address"`
	IPAddresses []string `json:"ip-addresses"`
	Hostname    string   `json:"hostname,omitempty"`
}

// KeaDhcp6Conf renders Kea's DHCPv6 config. Unlike DHCPv4 it is rendered
// here, reservations included (from AAAA records with a MAC), because
// Kea needs each subnet's interface to serve directly connected clients
// on more than one subnet.
func KeaDhcp6Conf(in *fwconfig.Instance, p Paths) string {
	type res struct {
		addr netip.Addr
		r    kea6Reservation
	}
	var reservations []res
	for _, z := range in.DNS.Zones {
		for _, r := range z.Records {
			a, err := netip.ParseAddr(r.Value)
			if r.Type != "AAAA" || r.MAC == "" || err != nil {
				continue
			}
			host := z.Name
			if r.Name != "@" {
				host = r.Name + "." + z.Name
			}
			reservations = append(reservations, res{a, kea6Reservation{
				HWAddress: strings.ToLower(strings.ReplaceAll(r.MAC, "-", ":")), IPAddresses: []string{a.String()}, Hostname: host,
			}})
		}
	}
	sort.SliceStable(reservations, func(i, j int) bool { return reservations[i].addr.Less(reservations[j].addr) })

	subnets := []kea6Subnet{}
	for i, s := range DHCP6Subnets(in) {
		pfx, err := netip.ParsePrefix(s.Prefix)
		if err != nil {
			continue
		}
		sub := kea6Subnet{ID: i + 1, Subnet: pfx.Masked().String(), Interface: s.Interface}
		if s.RangeStart != "" {
			sub.Pools = []kea6Pool{{Pool: s.RangeStart + " - " + s.RangeEnd}}
		}
		if len(s.DNSServers) > 0 {
			sub.OptionData = append(sub.OptionData, kea6Option{Name: "dns-servers", Data: strings.Join(s.DNSServers, ", ")})
		}
		if in.DHCP.DomainName != "" {
			sub.OptionData = append(sub.OptionData, kea6Option{Name: "domain-search", Data: in.DHCP.DomainName})
		}
		for _, r := range reservations {
			if pfx.Contains(r.addr) {
				sub.Reservations = append(sub.Reservations, r.r)
			}
		}
		subnets = append(subnets, sub)
	}

	lease := in.DHCP.LeaseTime
	if lease <= 0 {
		lease = 86400
	}
	ifJSON, _ := json.Marshal(dhcp6Interfaces(in))
	subJSON, _ := json.MarshalIndent(subnets, "    ", "  ")
	b := &strings.Builder{}
	fmt.Fprintf(b, "// Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	fmt.Fprintf(b, `{
  "Dhcp6": {
    "interfaces-config": { "interfaces": %s },
    "control-socket": { "socket-type": "unix", "socket-name": %q },
    "lease-database": { "type": "memfile", "persist": true, "lfc-interval": 3600, "name": %q },
    "preferred-lifetime": %d,
    "valid-lifetime": %d,
    "renew-timer": %d,
    "rebind-timer": %d,
    "subnet6": %s,
    "loggers": [ { "name": "kea-dhcp6", "output-options": [ { "output": "stdout" } ], "severity": "INFO" } ]
  }
}
`, ifJSON,
		filepath.Join(p.KeaSocketDir, "kea6-"+in.Name+".sock"),
		KeaLease6File(in.Name, p),
		lease*3/4, lease, lease/2, lease*4/5,
		subJSON)
	return b.String()
}

// KeaLease6File is where Kea keeps an instance's v6 leases.
func KeaLease6File(instance string, p Paths) string {
	return filepath.Join(p.KeaDataDir, "kea-leases6-"+instance+".csv")
}
