// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"

	"github.com/abundo/portitor/internal/fwconfig"
)

// TableName is the one nftables table portitor-agent owns in each
// namespace. Other tables (docker, libvirt, ...) are left alone.
const TableName = "firewall"

// AntiLockout keeps the agent's management port reachable in the default
// instance no matter what the rules say.
type AntiLockout struct {
	Port      int      `json:"port"`
	AllowFrom []string `json:"allow_from"` // CIDRs; empty disables the rule
}

// Rule describes the anti-lockout rule for the GUI's read-only list.
func (l *AntiLockout) Rule() AutoRule {
	return AutoRule{Service: "anti-lockout", Protocol: "tcp", DstPort: l.Port, Source: l.AllowFrom}
}

// Nftables renders the complete ruleset for one instance. The output is fed
// to `nft -f` as one transaction: the table is (re)created atomically, so a
// syntax error leaves the previous ruleset in place.
//
// The output does not include the generation, so a ruleset that did not
// change renders byte-identical and is not rewritten or shown as a diff.
// in must come from an expanded document (link ends as interfaces).
func Nftables(in *fwconfig.Instance, lockout *AntiLockout) string {
	b := &strings.Builder{}

	fmt.Fprintf(b, "# Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	fmt.Fprintf(b, "table inet %s\ndelete table inet %s\n\n", TableName, TableName)
	fmt.Fprintf(b, "table inet %s {\n", TableName)

	b.WriteString("\tchain reject_pkt {\n")
	b.WriteString("\t\tmeta l4proto tcp reject with tcp reset\n")
	b.WriteString("\t\treject with icmpx port-unreachable\n")
	b.WriteString("\t}\n\n")

	// ----- input -----
	b.WriteString("\tchain input {\n")
	b.WriteString("\t\ttype filter hook input priority filter; policy drop;\n")
	b.WriteString("\t\tct state established,related accept\n")
	b.WriteString("\t\tct state invalid drop\n")
	b.WriteString("\t\tiif \"lo\" accept\n")
	b.WriteString("\t\tmeta l4proto ipv6-icmp icmpv6 type { nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert, destination-unreachable, packet-too-big, time-exceeded, parameter-problem } accept\n")
	b.WriteString("\t\tmeta l4proto icmp icmp type { destination-unreachable, time-exceeded, parameter-problem } accept\n")
	if lockout != nil && in.Default && lockout.Port > 0 {
		v4, v6 := splitFamilies(lockout.AllowFrom)
		if len(v4) > 0 {
			fmt.Fprintf(b, "\t\tip saddr %s tcp dport %d accept comment \"anti-lockout\"\n", set(v4), lockout.Port)
		}
		if len(v6) > 0 {
			fmt.Fprintf(b, "\t\tip6 saddr %s tcp dport %d accept comment \"anti-lockout\"\n", set(v6), lockout.Port)
		}
	}
	for _, r := range AutoInputRules(in) {
		b.WriteString("\t\t" + r.nft() + "\n")
	}
	writeRules(b, in, fwconfig.ChainInput)
	b.WriteString("\t}\n\n")

	// ----- forward -----
	b.WriteString("\tchain forward {\n")
	b.WriteString("\t\ttype filter hook forward priority filter; policy drop;\n")
	b.WriteString("\t\tct state established,related accept\n")
	b.WriteString("\t\tct state invalid drop\n")
	b.WriteString("\t\tct status dnat accept comment \"port forwards\"\n")
	b.WriteString("\t\tmeta l4proto ipv6-icmp icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem } accept\n")
	writeRules(b, in, fwconfig.ChainForward)
	b.WriteString("\t}\n\n")

	// ----- output -----
	b.WriteString("\tchain output {\n")
	b.WriteString("\t\ttype filter hook output priority filter; policy accept;\n")
	writeRules(b, in, fwconfig.ChainOutput)
	b.WriteString("\t}\n\n")

	// ----- NAT -----
	b.WriteString("\tchain prerouting_nat {\n")
	b.WriteString("\t\ttype nat hook prerouting priority dstnat; policy accept;\n")
	for i, n := range in.NAT {
		if n.Kind == fwconfig.NATDNAT {
			writeNAT(b, i, n, in)
		}
	}
	b.WriteString("\t}\n\n")

	b.WriteString("\tchain postrouting_nat {\n")
	b.WriteString("\t\ttype nat hook postrouting priority srcnat; policy accept;\n")
	for i, n := range in.NAT {
		if n.Kind != fwconfig.NATDNAT {
			writeNAT(b, i, n, in)
		}
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// AutoRule is an input accept rule for a configured service, added in
// front of the user's input rules. The GUI lists them read-only.
type AutoRule struct {
	Service string `json:"service"`
	// InInterfaces limits the rule to these interfaces; empty is any.
	InInterfaces []string `json:"in_interfaces"`
	Protocol     string   `json:"protocol"` // tcp, udp, or "tcp,udp"
	SrcPort      int      `json:"src_port,omitempty"`
	DstPort      int      `json:"dst_port"`
	// Source limits the source addresses. Only the anti-lockout rule
	// (AntiLockout.Rule) sets it; AutoInputRules never does, and nft()
	// does not render it.
	Source []string `json:"source,omitempty"`
}

// AutoInputRules opens what the configured services need, so a user who
// enables the DHCP server on lan doesn't also have to write the rule.
func AutoInputRules(in *fwconfig.Instance) []AutoRule {
	out := []AutoRule{}
	var dhcpClient []string
	for _, ifc := range in.Interfaces {
		if ifc.Enabled && ifc.IPv4Mode == fwconfig.ModeDHCP {
			dhcpClient = append(dhcpClient, ifc.Name)
		}
	}
	if len(dhcpClient) > 0 {
		out = append(out, AutoRule{Service: "dhcp client", InInterfaces: dhcpClient, Protocol: "udp", SrcPort: 67, DstPort: 68})
	}
	if in.DHCP.Enabled {
		var ifs []string
		for _, s := range in.DHCP.Subnets {
			if fwconfig.AddrFamily(s.Prefix) == "ipv4" {
				ifs = appendUnique(ifs, s.Interface)
			}
		}
		sort.Strings(ifs)
		if len(ifs) > 0 {
			out = append(out, AutoRule{Service: "dhcp server", InInterfaces: ifs, Protocol: "udp", DstPort: 67})
		}
		if ifs6 := dhcp6Interfaces(in); len(ifs6) > 0 {
			out = append(out, AutoRule{Service: "dhcpv6 server", InInterfaces: ifs6, Protocol: "udp", DstPort: 547})
		}
	}
	if in.DNS.Enabled && len(in.DNS.ListenInterfaces) > 0 {
		ifs := append([]string(nil), in.DNS.ListenInterfaces...)
		sort.Strings(ifs)
		out = append(out, AutoRule{Service: "dns server", InInterfaces: ifs, Protocol: "tcp,udp", DstPort: 53})
	}
	for _, ifc := range in.Interfaces {
		if ifc.Enabled && ifc.Kind == fwconfig.KindWireGuard && ifc.WireGuard != nil && ifc.WireGuard.ListenPort > 0 {
			out = append(out, AutoRule{Service: "wireguard " + ifc.Name, Protocol: "udp", DstPort: ifc.WireGuard.ListenPort})
		}
	}
	return out
}

// nft renders an auto rule as one nft rule.
func (r AutoRule) nft() string {
	var parts []string
	if len(r.InInterfaces) > 0 {
		parts = append(parts, "iifname "+quotedSet(r.InInterfaces))
	}
	if r.Protocol == "tcp,udp" {
		parts = append(parts, fmt.Sprintf("meta l4proto { tcp, udp } th dport %d", r.DstPort))
	} else {
		if r.SrcPort > 0 {
			parts = append(parts, fmt.Sprintf("%s sport %d", r.Protocol, r.SrcPort))
		}
		parts = append(parts, fmt.Sprintf("%s dport %d", r.Protocol, r.DstPort))
	}
	parts = append(parts, "accept", comment("auto", r.Service))
	return strings.Join(parts, " ")
}

// ifaceMatch renders the iifname/oifname matches of a rule. ok is false
// when a non-empty interface list matches no enabled interface: the rule
// is then skipped (with a comment saying so), since dropping the match
// would widen it to every interface.
func ifaceMatch(b *strings.Builder, what string, in *fwconfig.Instance, inList, outList []string) (parts []string, ok bool) {
	for _, m := range []struct {
		key  string
		list []string
	}{{"iifname", inList}, {"oifname", outList}} {
		if len(m.list) == 0 {
			continue
		}
		ifs := in.MatchInterfaces(m.list)
		if len(ifs) == 0 {
			fmt.Fprintf(b, "\t\t# %s skipped: %s has no enabled interfaces\n", what, strings.Join(m.list, ", "))
			return nil, false
		}
		parts = append(parts, m.key+" "+quotedSet(ifs))
	}
	return parts, true
}

// writeRules renders the rules of one chain. Rules are numbered without
// the comment rows, which become rules holding only a comment: nft keeps
// those in the kernel ruleset, unlike # lines.
func writeRules(b *strings.Builder, in *fwconfig.Instance, chain string) {
	idx := 0
	for _, r := range in.Rules {
		if r.Kind == fwconfig.RuleKindComment {
			if r.Chain == chain && r.Description != "" {
				b.WriteString("\t\t" + comment("", r.Description) + "\n")
			}
			continue
		}
		if r.Chain == chain {
			writeRule(b, idx, r, in)
		}
		idx++
	}
}

func writeRule(b *strings.Builder, idx int, r fwconfig.Rule, in *fwconfig.Instance) {
	parts, ok := ifaceMatch(b, fmt.Sprintf("rule %d", idx+1), in, r.InInterfaces, r.OutInterfaces)
	if !ok {
		return
	}
	var tail []string
	tail = append(tail, "counter")
	if r.Log {
		tail = append(tail, fmt.Sprintf("log prefix \"fw rule %d %s: \"", idx+1, r.Action))
	}
	switch r.Action {
	case fwconfig.ActionAccept:
		tail = append(tail, "accept")
	case fwconfig.ActionDrop:
		tail = append(tail, "drop")
	case fwconfig.ActionReject:
		tail = append(tail, "jump reject_pkt")
	}
	tail = append(tail, comment(fmt.Sprintf("rule %d", idx+1), r.Description))
	// One nft rule per IP version when the addresses mix them.
	for _, m := range fwconfig.MatchFamilies(r.Family, r.Protocol, r.SrcAddrs, r.DstAddrs) {
		line := append(append(append([]string(nil), parts...), matchExpr(m, r.Protocol, r.DstPorts)...), tail...)
		b.WriteString("\t\t" + strings.Join(line, " ") + "\n")
	}
}

func writeNAT(b *strings.Builder, idx int, n fwconfig.NATRule, in *fwconfig.Instance) {
	parts, ok := ifaceMatch(b, fmt.Sprintf("nat rule %d", idx+1), in, n.InInterfaces, n.OutInterfaces)
	if !ok {
		return
	}
	// snat/dnat match the target's IP version; masquerade the versions of
	// its addresses, IPv4 without any.
	family := fwconfig.AddrFamily(n.ToAddr)
	if n.Kind == fwconfig.NATMasquerade && len(n.SrcAddrs) == 0 && len(n.DstAddrs) == 0 {
		family = "ipv4"
	}
	var tail []string
	tail = append(tail, "counter")
	switch n.Kind {
	case fwconfig.NATMasquerade:
		tail = append(tail, "masquerade")
	case fwconfig.NATSNAT, fwconfig.NATDNAT:
		target, _ := netip.ParseAddr(n.ToAddr)
		verb, fam := "snat", "ip"
		if n.Kind == fwconfig.NATDNAT {
			verb = "dnat"
		}
		if target.Is6() {
			fam = "ip6"
		}
		to := target.String()
		if n.ToPort != 0 {
			if target.Is6() {
				to = "[" + to + "]"
			}
			to = fmt.Sprintf("%s:%d", to, n.ToPort)
		}
		tail = append(tail, fmt.Sprintf("%s %s to %s", verb, fam, to))
	}
	tail = append(tail, comment(fmt.Sprintf("nat %d", idx+1), n.Description))
	for _, m := range fwconfig.MatchFamilies(family, n.Protocol, n.SrcAddrs, n.DstAddrs) {
		line := append(append(append([]string(nil), parts...), matchExpr(m, n.Protocol, n.DstPorts)...), tail...)
		b.WriteString("\t\t" + strings.Join(line, " ") + "\n")
	}
}

// matchExpr renders family / protocol / address / port matches for one
// IP version of a rule.
func matchExpr(m fwconfig.FamilyMatch, proto string, ports string) []string {
	var parts []string
	if len(m.Src) == 0 && len(m.Dst) == 0 && m.Family != "" {
		parts = append(parts, "meta nfproto "+m.Family)
	}
	fam := "ip"
	if m.Family == "ipv6" {
		fam = "ip6"
	}
	if len(m.Src) > 0 {
		parts = append(parts, fmt.Sprintf("%s saddr %s", fam, set(m.Src)))
	}
	if len(m.Dst) > 0 {
		parts = append(parts, fmt.Sprintf("%s daddr %s", fam, set(m.Dst)))
	}
	switch proto {
	case "tcp", "udp":
		if ports != "" {
			parts = append(parts, fmt.Sprintf("%s dport %s", proto, portSet(ports)))
		} else {
			parts = append(parts, "meta l4proto "+proto)
		}
	case "icmp":
		parts = append(parts, "meta l4proto icmp")
	case "icmpv6":
		parts = append(parts, "meta l4proto ipv6-icmp")
	}
	return parts
}

func splitFamilies(list []string) (v4, v6 []string) {
	for _, a := range list {
		p, err := fwconfig.ParseAddrOrPrefix(a)
		if err != nil {
			continue
		}
		if p.Addr().Is4() {
			v4 = append(v4, p.String())
		} else {
			v6 = append(v6, p.String())
		}
	}
	return v4, v6
}

// set renders validated addresses; single-address prefixes are written
// without /32 for readability.
func set(list []string) string {
	out := make([]string, 0, len(list))
	for _, a := range list {
		p, err := fwconfig.ParseAddrOrPrefix(a)
		if err != nil {
			continue
		}
		if p.IsSingleIP() {
			out = append(out, p.Addr().String())
		} else {
			out = append(out, p.String())
		}
	}
	if len(out) == 1 {
		return out[0]
	}
	return "{ " + strings.Join(out, ", ") + " }"
}

func portSet(s string) string {
	ranges, _ := fwconfig.ParsePorts(s)
	out := make([]string, 0, len(ranges))
	for _, r := range ranges {
		if r.Lo == r.Hi {
			out = append(out, fmt.Sprint(r.Lo))
		} else {
			out = append(out, fmt.Sprintf("%d-%d", r.Lo, r.Hi))
		}
	}
	if len(out) == 1 {
		return out[0]
	}
	return "{ " + strings.Join(out, ", ") + " }"
}

func quotedSet(names []string) string {
	q := make([]string, len(names))
	for i, n := range names {
		q[i] = fmt.Sprintf("%q", n)
	}
	if len(q) == 1 {
		return q[0]
	}
	return "{ " + strings.Join(q, ", ") + " }"
}

// comment renders an nft comment. nft strings cannot escape quotes, so
// they are replaced; control characters were rejected by validation. An
// empty prefix renders desc alone.
func comment(prefix, desc string) string {
	s := prefix
	if s == "" {
		s = desc
	} else if desc != "" {
		s += ": " + desc
	}
	s = strings.NewReplacer(`"`, "'", `\`, "/").Replace(s)
	if r := []rune(s); len(r) > 120 {
		s = string(r[:120])
	}
	return `comment "` + s + `"`
}

func appendUnique(list []string, s string) []string {
	for _, x := range list {
		if x == s {
			return list
		}
	}
	return append(list, s)
}
