// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/netip"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"

	"github.com/abundo/portitor/internal/fwconfig"
)

// TableName is the one nftables table portitor-agent owns in each
// namespace. Other tables (docker, libvirt, ...) are left alone.
const TableName = "firewall"

// AntiLockout keeps the agent's management port, and SSH, reachable in the
// default instance no matter what the rules say.
type AntiLockout struct {
	Port      int      `json:"port"`
	SSHPort   int      `json:"ssh_port,omitempty"` // 0 leaves SSH out
	AllowFrom []string `json:"allow_from"`         // CIDRs; empty disables the rule
}

// AntiLockoutService is the anti-lockout rule's service, as the other auto
// input rules have (AutoRule.Service); LogAuto names it to log the rule.
const AntiLockoutService = "anti-lockout"

// Ports are the TCP ports the anti-lockout rule accepts: SSH, then the API.
func (l *AntiLockout) Ports() []int {
	var out []int
	if l.SSHPort > 0 && l.SSHPort != l.Port {
		out = append(out, l.SSHPort)
	}
	if l.Port > 0 {
		out = append(out, l.Port)
	}
	return out
}

// Rules describe the anti-lockout rule for the GUI's read-only list, one
// row per port.
func (l *AntiLockout) Rules() []AutoRule {
	var out []AutoRule
	for _, p := range l.Ports() {
		out = append(out, AutoRule{Service: AntiLockoutService, Protocol: "tcp", DstPort: p, Source: l.AllowFrom})
	}
	return out
}

// Nftables renders the complete ruleset for one instance. The output is fed
// to `nft -f` as one transaction: the table is (re)created atomically, so a
// syntax error leaves the previous ruleset in place.
//
// The output does not include the generation, so a ruleset that did not
// change renders byte-identical and is not rewritten or shown as a diff.
// in must come from an expanded document (link ends as interfaces).
//
// Each IP list the rules use gets a named set per IP version, filled by an
// include of the list's elements file (paths.IPListFile), which the agent
// writes when it downloads the list. The sets are thus loaded in the same
// transaction as the rules that use them, never empty in between.
func Nftables(in *fwconfig.Instance, lockout *AntiLockout, paths Paths) string {
	b := &strings.Builder{}

	fmt.Fprintf(b, "# Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	fmt.Fprintf(b, "table inet %s\ndelete table inet %s\n\n", TableName, TableName)
	fmt.Fprintf(b, "table inet %s {\n", TableName)

	lists := in.UsedIPLists()
	for _, name := range lists {
		for _, fam := range []string{"ipv4", "ipv6"} {
			fmt.Fprintf(b, "\tset %s {\n\t\ttype %s_addr\n\t\tflags interval\n\t\tauto-merge\n\t}\n\n", SetName(name, fam), fam)
		}
	}

	if len(in.Certificates) > 0 {
		fmt.Fprintf(b, "\tset %s {\n\t\ttype inet_service\n\t}\n\n", ACMEHTTPSet)
	}

	counted := writeRuleCounters(b, in.Rules)
	writeDropCounters(b)

	b.WriteString("\tchain reject_pkt {\n")
	b.WriteString("\t\tmeta l4proto tcp reject with tcp reset\n")
	b.WriteString("\t\treject with icmpx port-unreachable\n")
	b.WriteString("\t}\n\n")

	// ----- input -----
	b.WriteString("\tchain input {\n")
	b.WriteString("\t\ttype filter hook input priority filter; policy drop;\n")
	if counted {
		b.WriteString(connCountRules)
	}
	b.WriteString("\t\tct state established,related accept\n")
	writeInvalidDrop(b, in, fwconfig.ChainInput)
	b.WriteString("\t\tiif \"lo\" accept\n")
	b.WriteString("\t\tmeta l4proto ipv6-icmp icmpv6 type { nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert, destination-unreachable, packet-too-big, time-exceeded, parameter-problem } accept\n")
	b.WriteString("\t\tmeta l4proto icmp icmp type { destination-unreachable, time-exceeded, parameter-problem } accept\n")
	if lockout != nil && in.Default && lockout.Port > 0 {
		ports := lockout.Ports()
		dport := strconv.Itoa(ports[0])
		if len(ports) > 1 {
			strs := make([]string, len(ports))
			for i, p := range ports {
				strs[i] = strconv.Itoa(p)
			}
			dport = "{ " + strings.Join(strs, ", ") + " }"
		}
		v4, v6 := splitFamilies(lockout.AllowFrom)
		for _, m := range []struct {
			key   string
			addrs []string
		}{{"ip", v4}, {"ip6", v6}} {
			if len(m.addrs) > 0 {
				match := fmt.Sprintf("%s saddr %s tcp dport %s", m.key, set(m.addrs), dport)
				writeAutoLog(b, in, AntiLockoutService, match)
				fmt.Fprintf(b, "\t\t%s accept comment %q\n", match, AntiLockoutService)
			}
		}
	}
	// What the enabled services need comes before the rules, so a rule
	// that closes an interface to the firewall doesn't take DHCP or DNS
	// away from it.
	for _, r := range AutoInputRules(in) {
		for _, match := range r.matches() {
			writeAutoLog(b, in, r.Service, match)
			b.WriteString("\t\t" + match + " accept " + comment("auto", r.Service) + "\n")
		}
	}
	writeRules(b, in, fwconfig.ChainInput)
	writePolicyCount(b, in, fwconfig.ChainInput)
	b.WriteString("\t}\n\n")

	// ----- forward -----
	b.WriteString("\tchain forward {\n")
	b.WriteString("\t\ttype filter hook forward priority filter; policy drop;\n")
	if counted {
		b.WriteString(connCountRules)
	}
	b.WriteString("\t\tct state established,related accept\n")
	writeInvalidDrop(b, in, fwconfig.ChainForward)
	b.WriteString("\t\tmeta l4proto ipv6-icmp icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem } accept\n")
	// Port forwards are accepted after the rules, so a rule can drop
	// what a DNAT would let in.
	writeRules(b, in, fwconfig.ChainForward)
	b.WriteString("\t\tct status dnat accept comment \"port forwards\"\n")
	writePolicyCount(b, in, fwconfig.ChainForward)
	b.WriteString("\t}\n\n")

	// ----- output -----
	b.WriteString("\tchain output {\n")
	b.WriteString("\t\ttype filter hook output priority filter; policy drop;\n")
	if counted {
		b.WriteString(connCountRules)
	}
	b.WriteString("\t\tct state established,related accept\n")
	writeInvalidDrop(b, in, fwconfig.ChainOutput)
	b.WriteString("\t\toif \"lo\" accept\n")
	b.WriteString("\t\tmeta l4proto ipv6-icmp icmpv6 type { nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert, destination-unreachable, packet-too-big, time-exceeded, parameter-problem } accept\n")
	b.WriteString("\t\tmeta l4proto icmp icmp type { destination-unreachable, time-exceeded, parameter-problem } accept\n")
	// What OSPF sends: on its interfaces, or to its networks' neighbours
	// and the OSPF multicast groups.
	for _, m := range OSPFOutputMatches(in) {
		fmt.Fprintf(b, "\t\t%s accept %s\n", m.match, comment("auto", m.service))
	}
	// The BGP sessions FRR opens to its neighbours.
	if addrs := BGPNeighborAddrs(in); len(addrs) > 0 {
		v4, v6 := splitFamilies(addrs)
		for _, m := range []struct {
			key   string
			addrs []string
		}{{"ip", v4}, {"ip6", v6}} {
			if len(m.addrs) > 0 {
				fmt.Fprintf(b, "\t\t%s daddr %s tcp dport 179 accept %s\n", m.key, set(m.addrs), comment("auto", BGPService))
			}
		}
	}
	writeRules(b, in, fwconfig.ChainOutput)
	writePolicyCount(b, in, fwconfig.ChainOutput)
	b.WriteString("\t}\n\n")

	// ----- NAT -----
	b.WriteString("\tchain prerouting_nat {\n")
	b.WriteString("\t\ttype nat hook prerouting priority dstnat; policy accept;\n")
	for i, n := range in.NAT {
		if n.Kind == fwconfig.NATDNAT {
			writeNAT(b, i, n, in)
			if n.Hairpin {
				writeHairpin(b, i, n, in)
			}
		}
	}
	b.WriteString("\t}\n\n")

	b.WriteString("\tchain postrouting_nat {\n")
	b.WriteString("\t\ttype nat hook postrouting priority srcnat; policy accept;\n")
	for _, n := range in.NAT {
		if n.Hairpin {
			fmt.Fprintf(b, "\t\tmeta mark %#x counter masquerade comment \"hairpin\"\n", HairpinMark)
			break
		}
	}
	for i, n := range in.NAT {
		if n.Kind != fwconfig.NATDNAT {
			writeNAT(b, i, n, in)
		}
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	for _, name := range lists {
		fmt.Fprintf(b, "include %q\n", paths.IPListFile(name))
	}
	return b.String()
}

// Rule counters. A rule with an ID counts the packets it matches in a
// named counter, and an accept rule marks the connection (ct mark) with the
// ID, so the rest of the connection is counted under the rule too: the
// connCountRules at the top of each filter chain look the mark up in the
// rule_orig/rule_reply maps, before established packets are accepted. The
// kernel ruleset is replaced on apply, so the counters restart from zero.
const (
	CounterOrig  = "orig"  // sent by the side that opened the connection
	CounterReply = "reply" // the replies
)

// RuleCounter is the name of a rule's counter for one direction.
func RuleCounter(id uint32, dir string) string {
	return fmt.Sprintf("rule_%d_%s", id, dir)
}

// ParseRuleCounter is the inverse of RuleCounter.
func ParseRuleCounter(name string) (id uint32, dir string, ok bool) {
	rest, found := strings.CutPrefix(name, "rule_")
	if !found {
		return 0, "", false
	}
	num, dir, found := strings.Cut(rest, "_")
	n, err := strconv.ParseUint(num, 10, 32)
	if !found || err != nil || n == 0 || (dir != CounterOrig && dir != CounterReply) {
		return 0, "", false
	}
	return uint32(n), dir, true
}

const connCountRules = "\t\tct direction original counter name ct mark map @rule_orig\n" +
	"\t\tct direction reply counter name ct mark map @rule_reply\n"

// writeRuleCounters declares the counters of the rules with an ID, and the
// maps from connection mark to counter for the accept rules. It reports
// whether there are any maps (and so connCountRules to write).
func writeRuleCounters(b *strings.Builder, rules []fwconfig.Rule) bool {
	var orig, reply []string
	for _, r := range rules {
		if r.Kind == fwconfig.RuleKindComment || r.ID == 0 {
			continue
		}
		for _, dir := range []string{CounterOrig, CounterReply} {
			fmt.Fprintf(b, "\tcounter %s {\n\t}\n\n", RuleCounter(r.ID, dir))
		}
		if r.Action == fwconfig.ActionAccept {
			orig = append(orig, fmt.Sprintf("%d : %q", r.ID, RuleCounter(r.ID, CounterOrig)))
			reply = append(reply, fmt.Sprintf("%d : %q", r.ID, RuleCounter(r.ID, CounterReply)))
		}
	}
	if len(orig) == 0 {
		return false
	}
	for _, m := range []struct {
		dir   string
		elems []string
	}{{CounterOrig, orig}, {CounterReply, reply}} {
		fmt.Fprintf(b, "\tmap rule_%s {\n\t\ttype mark : counter\n\t\telements = { %s }\n\t}\n\n", m.dir, strings.Join(m.elems, ", "))
	}
	return true
}

// Drop counters. Each filter chain counts, apart from the rules, the
// packets it drops by itself: DropInvalid those of no known connection
// (ct state invalid), DropPolicy those no rule decided on, which fall
// through to the chain's drop policy. They restart from zero on apply, like
// the rule counters.
const (
	DropInvalid = "invalid"
	DropPolicy  = "policy"
)

var filterChains = []string{fwconfig.ChainInput, fwconfig.ChainForward, fwconfig.ChainOutput}

// DropCounter is the name of a chain's drop counter for one reason.
func DropCounter(chain, reason string) string {
	return "drop_" + chain + "_" + reason
}

// ParseDropCounter is the inverse of DropCounter.
func ParseDropCounter(name string) (chain, reason string, ok bool) {
	rest, found := strings.CutPrefix(name, "drop_")
	if !found {
		return "", "", false
	}
	chain, reason, found = strings.Cut(rest, "_")
	if !found || !slices.Contains(filterChains, chain) || (reason != DropInvalid && reason != DropPolicy) {
		return "", "", false
	}
	return chain, reason, true
}

func writeDropCounters(b *strings.Builder) {
	for _, chain := range filterChains {
		for _, reason := range []string{DropInvalid, DropPolicy} {
			fmt.Fprintf(b, "\tcounter %s {\n\t}\n\n", DropCounter(chain, reason))
		}
	}
}

// writeInvalidDrop drops a chain's invalid packets, after logging them
// if the instance says so (LogInvalid). The log is a rule of its own: over
// the rate limit, a rule with the limit would not reach its drop.
func writeInvalidDrop(b *strings.Builder, in *fwconfig.Instance, chain string) {
	if slices.Contains(in.LogInvalid, chain) {
		fmt.Fprintf(b, "\t\tct state invalid %s %s\n", builtinLogLimit,
			logStmt(LogSource{Chain: chain, Builtin: BuiltinInvalid, Action: fwconfig.ActionDrop}))
	}
	fmt.Fprintf(b, "\t\tct state invalid counter name %q drop\n", DropCounter(chain, DropInvalid))
}

// builtinLogLimit rate limits the log of the built-in rules (a chain's
// invalid and policy drops, the auto input rules), so a scan or a busy
// service does not flood the agent's packet log.
const builtinLogLimit = "limit rate 10/second burst 20 packets"

// writePolicyCount ends a chain with a rule that counts and, if the
// instance says so (LogDrops), logs: what reaches it is dropped by the
// chain's policy, so the limit can share the rule.
func writePolicyCount(b *strings.Builder, in *fwconfig.Instance, chain string) {
	fmt.Fprintf(b, "\t\tcounter name %q ", DropCounter(chain, DropPolicy))
	if slices.Contains(in.LogDrops, chain) {
		fmt.Fprintf(b, "%s %s ", builtinLogLimit,
			logStmt(LogSource{Chain: chain, Builtin: BuiltinPolicy, Action: fwconfig.ActionDrop}))
	}
	b.WriteString("comment \"no rule matched: policy drop\"\n")
}

// LogGroup is the nflog group every log statement sends its packets to,
// not the kernel log: the agent listens on it in each namespace whose
// ruleset logs (see agent.packetLog). A namespace has groups of its own,
// so one number serves every instance.
const LogGroup = 64

// Built-in rows of a chain that can log (LogSource.Builtin).
const (
	BuiltinPolicy  = "policy"  // what no rule matched
	BuiltinInvalid = "invalid" // packets of no known connection
	BuiltinAuto    = "auto"    // an auto input rule; LogSource.Service says which
)

// LogSource is the rule of a chain that logged a packet: rule Rule
// (numbered as in the ruleset's comments) or, with Rule 0, a built-in one.
type LogSource struct {
	Chain   string
	Rule    int
	Builtin string
	Service string // of an auto input rule
	Action  string
}

func logStmt(s LogSource) string {
	return fmt.Sprintf("log prefix %q group %d", LogPrefix(s), LogGroup)
}

// LogPrefix is the log prefix of a rule, for the agent (ParseLogPrefix):
// "forward rule 8 drop", "forward policy drop", "input invalid drop",
// "input auto accept dhcp server" (the service last, as it has spaces).
func LogPrefix(s LogSource) string {
	switch {
	case s.Rule > 0:
		return fmt.Sprintf("%s rule %d %s", s.Chain, s.Rule, s.Action)
	case s.Builtin == BuiltinAuto:
		return fmt.Sprintf("%s auto %s %s", s.Chain, s.Action, s.Service)
	}
	return fmt.Sprintf("%s %s %s", s.Chain, s.Builtin, s.Action)
}

// ParseLogPrefix is the inverse of LogPrefix.
func ParseLogPrefix(prefix string) (s LogSource, ok bool) {
	f := strings.Fields(prefix)
	if len(f) < 3 {
		return s, false
	}
	s.Chain = f[0]
	switch f[1] {
	case "rule":
		n, err := strconv.Atoi(f[2])
		if len(f) != 4 || err != nil || n < 1 {
			return s, false
		}
		s.Rule, s.Action = n, f[3]
	case BuiltinPolicy, BuiltinInvalid:
		if len(f) != 3 {
			return s, false
		}
		s.Builtin, s.Action = f[1], f[2]
	case BuiltinAuto:
		if len(f) < 4 {
			return s, false
		}
		s.Builtin, s.Action, s.Service = f[1], f[2], strings.Join(f[3:], " ")
	default:
		return s, false
	}
	if !slices.Contains(filterChains, s.Chain) ||
		(s.Action != fwconfig.ActionAccept && s.Action != fwconfig.ActionDrop && s.Action != fwconfig.ActionReject) {
		return LogSource{}, false
	}
	return s, true
}

// SetName is the nftables set holding one IP version of an IP list.
func SetName(list, family string) string {
	if family == "ipv6" {
		return IPListKey(list) + "_v6"
	}
	return IPListKey(list) + "_v4"
}

// ipListKeyRe are the names an IP list kept as its key, from when they
// were all a list could be called.
var ipListKeyRe = regexp.MustCompile(`^[a-z][a-z0-9_]{0,23}$`)

// IPListKey is what names an IP list's sets and files. An IP list may be
// called anything, but nft identifiers and file names may not hold
// everything: a name that isn't a plain one is replaced by a hash of it
// ("L" and hex; upper case, so never a plain name).
func IPListKey(name string) string {
	if ipListKeyRe.MatchString(name) {
		return name
	}
	sum := sha256.Sum256([]byte(name))
	return "L" + hex.EncodeToString(sum[:12])
}

// AutoRule is an input accept rule for a configured service, added in
// front of the user's input rules. The GUI lists them read-only.
type AutoRule struct {
	Service string `json:"service"`
	// InInterfaces limits the rule to these interfaces; empty is any.
	InInterfaces []string `json:"in_interfaces"`
	Protocol     string   `json:"protocol"` // tcp, udp, "tcp,udp", or OSPF's (OSPFService, OSPF6Service: IPv4 or IPv6, no port)
	SrcPort      int      `json:"src_port,omitempty"`
	DstPort      int      `json:"dst_port"`
	// Source limits the source addresses: the anti-lockout rule's
	// (AntiLockout.Rule, rendered on its own) and the BGP neighbours'.
	Source []string `json:"source,omitempty"`
	// PortSet, when set, matches the destination port by this set instead
	// of DstPort: the rule opens DstPort only while the agent puts it in
	// the set (ACMEHTTPSet).
	PortSet string `json:"port_set,omitempty"`
}

// ACMEHTTPSet is the port set of the HTTP-01 auto rule: empty, except for
// port 80 while the agent answers an ACME challenge in the instance.
const ACMEHTTPSet = "acme_http"

// ACMEHTTPService is the HTTP-01 auto rule's service.
const ACMEHTTPService = "acme http-01"

// ACMEHTTPOpen and ACMEHTTPClose are the nft scripts that open and close
// port 80 for HTTP-01 challenges.
var (
	ACMEHTTPOpen  = fmt.Sprintf("add element inet %s %s { 80 }\n", TableName, ACMEHTTPSet)
	ACMEHTTPClose = fmt.Sprintf("flush set inet %s %s\n", TableName, ACMEHTTPSet)
)

// AutoInputRules opens what the configured services need, so a user who
// enables the DHCP server on lan doesn't also have to write the rule.
func AutoInputRules(in *fwconfig.Instance) []AutoRule {
	out := []AutoRule{}
	var dhcpClient []string
	for _, ifc := range in.Interfaces {
		if ifc.Enabled && ifc.IPv4Mode == fwconfig.ModeDHCP {
			dhcpClient = append(dhcpClient, ifc.Name)
		}
	}
	if len(dhcpClient) > 0 {
		out = append(out, AutoRule{Service: "dhcp client", InInterfaces: dhcpClient, Protocol: "udp", SrcPort: 67, DstPort: 68})
	}
	// A DHCPv6 server answers the multicast solicit from its own address,
	// which conntrack does not see as a reply.
	var dhcp6Client []string
	for _, ifc := range in.Interfaces {
		if ifc.Enabled && ifc.DHCPv6 {
			dhcp6Client = append(dhcp6Client, ifc.Name)
		}
	}
	if len(dhcp6Client) > 0 {
		out = append(out, AutoRule{Service: "dhcpv6 client", InInterfaces: dhcp6Client, Protocol: "udp", SrcPort: 547, DstPort: 546})
	}
	if in.DHCP.Enabled {
		if ifs := subnetInterfaces(DHCP4Subnets(in)); len(ifs) > 0 {
			out = append(out, AutoRule{Service: "dhcp server", InInterfaces: ifs, Protocol: "udp", DstPort: 67})
		}
		if ifs6 := subnetInterfaces(DHCP6Subnets(in)); len(ifs6) > 0 {
			out = append(out, AutoRule{Service: "dhcpv6 server", InInterfaces: ifs6, Protocol: "udp", DstPort: 547})
		}
	}
	if in.DNS.Enabled && len(in.DNS.ListenInterfaces) > 0 {
		ifs := append([]string(nil), in.DNS.ListenInterfaces...)
		sort.Strings(ifs)
		out = append(out, AutoRule{Service: "dns server", InInterfaces: ifs, Protocol: "tcp,udp", DstPort: 53})
	}
	// HTTP-01 challenges come in on the certificates' interfaces; the
	// rule matches only while one is being answered.
	var acme []string
	for _, c := range in.Certificates {
		if !slices.Contains(acme, c.Interface) {
			acme = append(acme, c.Interface)
		}
	}
	if len(acme) > 0 {
		sort.Strings(acme)
		out = append(out, AutoRule{Service: ACMEHTTPService, InInterfaces: acme, Protocol: "tcp", DstPort: 80, PortSet: ACMEHTTPSet})
	}
	for _, ifc := range in.Interfaces {
		if ifc.Enabled && ifc.Kind == fwconfig.KindWireGuard && ifc.WireGuard != nil && ifc.WireGuard.ListenPort > 0 {
			out = append(out, AutoRule{Service: "wireguard " + ifc.Name, Protocol: "udp", DstPort: ifc.WireGuard.ListenPort})
		}
	}
	// BGP sessions from the neighbours; the ones FRR opens are replies.
	if addrs := BGPNeighborAddrs(in); len(addrs) > 0 {
		out = append(out, AutoRule{Service: BGPService, Protocol: "tcp", DstPort: 179, Source: addrs})
	}
	// OSPF on its interfaces, and (OSPFv2) from its networks.
	for _, o := range []struct {
		version int
		service string
	}{{2, OSPFService}, {3, OSPF6Service}} {
		ifs, nets := OSPFActive(in, o.version)
		if len(ifs) > 0 {
			out = append(out, AutoRule{Service: o.service, InInterfaces: ifs, Protocol: o.service})
		}
		if len(nets) > 0 {
			out = append(out, AutoRule{Service: o.service, Protocol: o.service, Source: nets})
		}
	}
	return out
}

// BGPService is the BGP auto rule's service.
const BGPService = "bgp"

// OSPFService and OSPF6Service are the OSPF auto rules' services and
// protocols: IP protocol 89 of IPv4 (OSPFv2) or IPv6 (OSPFv3).
const (
	OSPFService  = "ospf"
	OSPF6Service = "ospfv3"
)

// ospfProto matches an OSPF version's packets.
func ospfProto(service string) string {
	if service == OSPF6Service {
		return "meta nfproto ipv6 meta l4proto 89"
	}
	return "meta nfproto ipv4 meta l4proto 89"
}

// OSPFOutput is an output chain accept of what OSPF sends.
type OSPFOutput struct{ service, match string }

// OSPFOutputMatches are the output chain's accepts for OSPF: on its
// interfaces, and for OSPFv2's network statements to their prefixes and
// the AllSPFRouters and AllDRouters groups.
func OSPFOutputMatches(in *fwconfig.Instance) []OSPFOutput {
	var out []OSPFOutput
	for _, o := range []struct {
		version int
		service string
	}{{2, OSPFService}, {3, OSPF6Service}} {
		ifs, nets := OSPFActive(in, o.version)
		if len(ifs) > 0 {
			out = append(out, OSPFOutput{o.service, "oifname " + quotedSet(ifs) + " " + ospfProto(o.service)})
		}
		if len(nets) > 0 {
			out = append(out, OSPFOutput{o.service, "ip daddr " + set(append(nets, "224.0.0.5", "224.0.0.6")) + " " + ospfProto(o.service)})
		}
	}
	return out
}

// matches renders an auto rule's matches: one, or with Source one per IP
// version of its addresses.
func (r AutoRule) matches() []string {
	if len(r.Source) == 0 {
		return []string{r.match()}
	}
	var out []string
	v4, v6 := splitFamilies(r.Source)
	for _, m := range []struct {
		key   string
		addrs []string
	}{{"ip", v4}, {"ip6", v6}} {
		if len(m.addrs) > 0 {
			out = append(out, fmt.Sprintf("%s saddr %s %s", m.key, set(m.addrs), r.match()))
		}
	}
	return out
}

// writeAutoLog logs, if the instance says so (LogAuto), what an auto input
// rule with this match accepts. The log is a rule of its own, before the
// accept: over the rate limit, a rule with the limit would not accept.
func writeAutoLog(b *strings.Builder, in *fwconfig.Instance, service, match string) {
	if slices.Contains(in.LogAuto, service) {
		fmt.Fprintf(b, "\t\t%s %s %s\n", match, builtinLogLimit,
			logStmt(LogSource{Chain: fwconfig.ChainInput, Builtin: BuiltinAuto, Service: service, Action: fwconfig.ActionAccept}))
	}
}

// match renders the matches of an auto rule.
func (r AutoRule) match() string {
	var parts []string
	if len(r.InInterfaces) > 0 {
		parts = append(parts, "iifname "+quotedSet(r.InInterfaces))
	}
	switch r.Protocol {
	case OSPFService, OSPF6Service:
		parts = append(parts, ospfProto(r.Protocol))
	case "tcp,udp":
		parts = append(parts, fmt.Sprintf("meta l4proto { tcp, udp } th dport %d", r.DstPort))
	default:
		if r.SrcPort > 0 {
			parts = append(parts, fmt.Sprintf("%s sport %d", r.Protocol, r.SrcPort))
		}
		if r.PortSet != "" {
			parts = append(parts, fmt.Sprintf("%s dport @%s", r.Protocol, r.PortSet))
		} else {
			parts = append(parts, fmt.Sprintf("%s dport %d", r.Protocol, r.DstPort))
		}
	}
	return strings.Join(parts, " ")
}

// ifaceMatch renders the iifname/oifname matches of a rule. ok is false
// when a non-empty interface list matches no enabled interface: the rule
// is then skipped (with a comment saying so), since dropping the match
// would widen it to every interface.
func ifaceMatch(b *strings.Builder, what string, in *fwconfig.Instance, inList, outList []string) (parts []string, ok bool) {
	for _, m := range []struct {
		key  string
		list []string
	}{{"iifname", inList}, {"oifname", outList}} {
		if len(m.list) == 0 {
			continue
		}
		ifs := in.MatchInterfaces(m.list)
		if len(ifs) == 0 {
			fmt.Fprintf(b, "\t\t# %s skipped: %s has no enabled interfaces\n", what, strings.Join(m.list, ", "))
			return nil, false
		}
		parts = append(parts, m.key+" "+quotedSet(ifs))
	}
	return parts, true
}

// writeRules renders the rules of one chain. Rules are numbered without
// the comment rows, which become rules that only continue to the next one
// and hold the comment: nft keeps those in the kernel ruleset, unlike #
// lines. A bare comment line would be the chain's own comment, of which
// there can be only one.
func writeRules(b *strings.Builder, in *fwconfig.Instance, chain string) {
	idx := 0
	for _, r := range in.Rules {
		if r.Kind == fwconfig.RuleKindComment {
			if r.Chain == chain && r.Description != "" {
				b.WriteString("\t\tcontinue " + comment("", r.Description) + "\n")
			}
			continue
		}
		if r.Chain == chain {
			writeRule(b, idx, r, in)
		}
		idx++
	}
}

func writeRule(b *strings.Builder, idx int, r fwconfig.Rule, in *fwconfig.Instance) {
	parts, ok := ifaceMatch(b, fmt.Sprintf("rule %d", idx+1), in, r.InInterfaces, r.OutInterfaces)
	if !ok {
		return
	}
	var tail []string
	if r.ID != 0 {
		tail = append(tail, fmt.Sprintf("counter name %q", RuleCounter(r.ID, CounterOrig)))
	} else {
		tail = append(tail, "counter")
	}
	if r.Log {
		tail = append(tail, logStmt(LogSource{Chain: r.Chain, Rule: idx + 1, Action: r.Action}))
	}
	switch r.Action {
	case fwconfig.ActionAccept:
		if r.ID != 0 {
			tail = append(tail, fmt.Sprintf("ct mark set %d", r.ID))
		}
		tail = append(tail, "accept")
	case fwconfig.ActionDrop:
		tail = append(tail, "drop")
	case fwconfig.ActionReject:
		tail = append(tail, "jump reject_pkt")
	}
	tail = append(tail, comment(fmt.Sprintf("rule %d", idx+1), r.Description))
	// One nft rule per service match and IP version (fwconfig.Rule.Matches),
	// and per address operand (see addrOperands).
	for _, m := range r.Matches() {
		for _, match := range matchExprs(m.FamilyMatch, serviceExpr(m.Service)) {
			line := append(append(append([]string(nil), parts...), match...), tail...)
			b.WriteString("\t\t" + strings.Join(line, " ") + "\n")
		}
	}
}

// HairpinMark is the packet mark a hairpin port forward sets (in
// prerouting) for postrouting to masquerade it; NAT sees only a
// connection's first packet, which carries it through both chains.
const HairpinMark = 0x4870

// writeHairpin renders a port forward's hairpin: the same match from the
// other interfaces, to an address of the firewall's own, marked so
// postrouting masquerades it and the target replies through the firewall.
func writeHairpin(b *strings.Builder, idx int, n fwconfig.NATRule, in *fwconfig.Instance) {
	ifs := in.MatchInterfaces(n.InInterfaces)
	if len(ifs) == 0 {
		return // writeNAT says why
	}
	h := n
	h.InInterfaces = nil
	h.Hairpin = false
	h.Description = strings.TrimSpace("hairpin " + n.Description)
	var sub strings.Builder
	writeNAT(&sub, idx, h, in)
	prefix := fmt.Sprintf("iifname != %s fib daddr type local ", quotedSet(ifs))
	for _, line := range strings.SplitAfter(sub.String(), "\n") {
		if line == "" {
			continue
		}
		line = strings.TrimPrefix(line, "\t\t")
		line = strings.Replace(line, " counter dnat ", fmt.Sprintf(" counter meta mark set %#x dnat ", HairpinMark), 1)
		b.WriteString("\t\t" + prefix + line)
	}
}

func writeNAT(b *strings.Builder, idx int, n fwconfig.NATRule, in *fwconfig.Instance) {
	parts, ok := ifaceMatch(b, fmt.Sprintf("nat rule %d", idx+1), in, n.InInterfaces, n.OutInterfaces)
	if !ok {
		return
	}
	// snat/dnat match the target's IP version; masquerade the versions of
	// its addresses, IPv4 without any.
	family := fwconfig.AddrFamily(n.ToAddr)
	if n.Kind == fwconfig.NATMasquerade && len(n.SrcAddrs) == 0 && len(n.DstAddrs) == 0 {
		family = "ipv4"
	}
	var tail []string
	tail = append(tail, "counter")
	switch n.Kind {
	case fwconfig.NATMasquerade:
		tail = append(tail, "masquerade")
	case fwconfig.NATSNAT, fwconfig.NATDNAT:
		target, _ := netip.ParseAddr(n.ToAddr)
		verb, fam := "snat", "ip"
		if n.Kind == fwconfig.NATDNAT {
			verb = "dnat"
		}
		if target.Is6() {
			fam = "ip6"
		}
		to := target.String()
		if n.ToPort != 0 {
			if target.Is6() {
				to = "[" + to + "]"
			}
			to = fmt.Sprintf("%s:%d", to, n.ToPort)
		}
		tail = append(tail, fmt.Sprintf("%s %s to %s", verb, fam, to))
	}
	tail = append(tail, comment(fmt.Sprintf("nat %d", idx+1), n.Description))
	for _, m := range fwconfig.MatchFamilies(family, n.Protocol, n.SrcAddrs, n.DstAddrs) {
		for _, match := range matchExprs(m, protoExpr(n.Protocol, n.DstPorts)) {
			line := append(append(append([]string(nil), parts...), match...), tail...)
			b.WriteString("\t\t" + strings.Join(line, " ") + "\n")
		}
	}
}

// matchExprs renders family / address matches for one IP version of a
// rule, followed by its protocol matches (proto): one match per
// combination of source and destination operand.
func matchExprs(m fwconfig.FamilyMatch, proto []string) [][]string {
	var out [][]string
	for _, src := range addrOperands(m.Src, m.Family) {
		for _, dst := range addrOperands(m.Dst, m.Family) {
			out = append(out, append(addrExpr(m.Family, src, dst), proto...))
		}
	}
	return out
}

// addrOperands renders an address list of one IP version as the operands
// of an saddr/daddr match: an anonymous set of the literal addresses, and
// each IP list's named set. One nft match takes one operand, so a list
// with several is rendered as one rule per operand (same verdict). An
// empty list is one empty operand: no match.
func addrOperands(list []string, family string) []string {
	if len(list) == 0 {
		return []string{""}
	}
	var lits, sets []string
	for _, a := range list {
		if name, ok := fwconfig.IPListName(a); ok {
			sets = append(sets, "@"+SetName(name, family))
		} else {
			lits = append(lits, a)
		}
	}
	if len(lits) > 0 {
		return append([]string{set(lits)}, sets...)
	}
	return sets
}

func addrExpr(family, src, dst string) []string {
	var parts []string
	if src == "" && dst == "" && family != "" {
		parts = append(parts, "meta nfproto "+family)
	}
	fam := "ip"
	if family == "ipv6" {
		fam = "ip6"
	}
	if src != "" {
		parts = append(parts, fmt.Sprintf("%s saddr %s", fam, src))
	}
	if dst != "" {
		parts = append(parts, fmt.Sprintf("%s daddr %s", fam, dst))
	}
	return parts
}

// serviceExpr renders a rule's service match; the empty match (any
// protocol) and ip without a number render nothing.
func serviceExpr(s fwconfig.ServiceMatch) []string {
	var parts []string
	switch s.Protocol {
	case fwconfig.ProtoTCP, fwconfig.ProtoUDP, fwconfig.ProtoSCTP:
		if s.SrcPorts != "" {
			parts = append(parts, fmt.Sprintf("%s sport %s", s.Protocol, portSet(s.SrcPorts)))
		}
		if s.DstPorts != "" {
			parts = append(parts, fmt.Sprintf("%s dport %s", s.Protocol, portSet(s.DstPorts)))
		}
		if len(parts) == 0 {
			parts = append(parts, "meta l4proto "+s.Protocol)
		}
	case fwconfig.ProtoICMP, fwconfig.ProtoICMPv6:
		if s.ICMPType != "" {
			parts = append(parts, fmt.Sprintf("%s type %s", s.Protocol, s.ICMPType))
		}
		if s.ICMPCode != nil {
			parts = append(parts, fmt.Sprintf("%s code %d", s.Protocol, *s.ICMPCode))
		}
		if len(parts) == 0 {
			l4 := s.Protocol
			if l4 == fwconfig.ProtoICMPv6 {
				l4 = "ipv6-icmp"
			}
			parts = append(parts, "meta l4proto "+l4)
		}
	case fwconfig.ProtoIP:
		if s.IPProtocol != 0 {
			parts = append(parts, fmt.Sprintf("meta l4proto %d", s.IPProtocol))
		}
	}
	return parts
}

// protoExpr renders a NAT rule's protocol and destination port matches.
func protoExpr(proto, ports string) []string {
	var parts []string
	switch proto {
	case "tcp", "udp":
		if ports != "" {
			parts = append(parts, fmt.Sprintf("%s dport %s", proto, portSet(ports)))
		} else {
			parts = append(parts, "meta l4proto "+proto)
		}
	case "tcp,udp":
		parts = append(parts, "meta l4proto { tcp, udp }")
		if ports != "" {
			parts = append(parts, "th dport "+portSet(ports))
		}
	}
	return parts
}

func splitFamilies(list []string) (v4, v6 []string) {
	for _, a := range list {
		p, err := fwconfig.ParseAddrOrPrefix(a)
		if err != nil {
			continue
		}
		if p.Addr().Is4() {
			v4 = append(v4, p.String())
		} else {
			v6 = append(v6, p.String())
		}
	}
	return v4, v6
}

// set renders validated addresses; single-address prefixes are written
// without /32 for readability.
func set(list []string) string {
	out := make([]string, 0, len(list))
	for _, a := range list {
		p, err := fwconfig.ParseAddrOrPrefix(a)
		if err != nil {
			continue
		}
		if p.IsSingleIP() {
			out = append(out, p.Addr().String())
		} else {
			out = append(out, p.String())
		}
	}
	if len(out) == 1 {
		return out[0]
	}
	return "{ " + strings.Join(out, ", ") + " }"
}

func portSet(s string) string {
	ranges, _ := fwconfig.ParsePorts(s)
	out := make([]string, 0, len(ranges))
	for _, r := range ranges {
		if r.Lo == r.Hi {
			out = append(out, fmt.Sprint(r.Lo))
		} else {
			out = append(out, fmt.Sprintf("%d-%d", r.Lo, r.Hi))
		}
	}
	if len(out) == 1 {
		return out[0]
	}
	return "{ " + strings.Join(out, ", ") + " }"
}

func quotedSet(names []string) string {
	q := make([]string, len(names))
	for i, n := range names {
		q[i] = fmt.Sprintf("%q", n)
	}
	if len(q) == 1 {
		return q[0]
	}
	return "{ " + strings.Join(q, ", ") + " }"
}

// comment renders an nft comment. nft strings cannot escape quotes, so
// they are replaced; control characters were rejected by validation. An
// empty prefix renders desc alone.
func comment(prefix, desc string) string {
	s := prefix
	if s == "" {
		s = desc
	} else if desc != "" {
		s += ": " + desc
	}
	s = strings.NewReplacer(`"`, "'", `\`, "/").Replace(s)
	if r := []rune(s); len(r) > 120 {
		s = string(r[:120])
	}
	return `comment "` + s + `"`
}

func appendUnique(list []string, s string) []string {
	for _, x := range list {
		if x == s {
			return list
		}
	}
	return append(list, s)
}
