// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"

	"github.com/abundo/portitor/internal/fwconfig"
)

// TableName is the one nftables table portitor-agent owns in each
// namespace. Other tables (docker, libvirt, ...) are left alone.
const TableName = "firewall"

// AntiLockout keeps the agent's management port reachable in the default
// instance no matter what the rules say.
type AntiLockout struct {
	Port      int
	AllowFrom []string // CIDRs; empty disables the rule
}

// Nftables renders the complete ruleset for one instance. The output is fed
// to `nft -f` as one transaction: the table is (re)created atomically, so a
// syntax error leaves the previous ruleset in place.
//
// The output does not include the generation, so a ruleset that did not
// change renders byte-identical and is not rewritten or shown as a diff.
func Nftables(in *fwconfig.Instance, lockout *AntiLockout) string {
	b := &strings.Builder{}
	zoneIfaces := zoneInterfaces(in)

	fmt.Fprintf(b, "# Generated by portitor-agent, instance %s. Do not edit.\n", in.Name)
	fmt.Fprintf(b, "table inet %s\ndelete table inet %s\n\n", TableName, TableName)
	fmt.Fprintf(b, "table inet %s {\n", TableName)

	b.WriteString("\tchain reject_pkt {\n")
	b.WriteString("\t\tmeta l4proto tcp reject with tcp reset\n")
	b.WriteString("\t\treject with icmpx port-unreachable\n")
	b.WriteString("\t}\n\n")

	// ----- input -----
	b.WriteString("\tchain input {\n")
	b.WriteString("\t\ttype filter hook input priority filter; policy drop;\n")
	b.WriteString("\t\tct state established,related accept\n")
	b.WriteString("\t\tct state invalid drop\n")
	b.WriteString("\t\tiif \"lo\" accept\n")
	b.WriteString("\t\tmeta l4proto ipv6-icmp icmpv6 type { nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert, destination-unreachable, packet-too-big, time-exceeded, parameter-problem } accept\n")
	b.WriteString("\t\tmeta l4proto icmp icmp type { destination-unreachable, time-exceeded, parameter-problem } accept\n")
	if lockout != nil && in.Default && lockout.Port > 0 {
		v4, v6 := splitFamilies(lockout.AllowFrom)
		if len(v4) > 0 {
			fmt.Fprintf(b, "\t\tip saddr %s tcp dport %d accept comment \"anti-lockout\"\n", set(v4), lockout.Port)
		}
		if len(v6) > 0 {
			fmt.Fprintf(b, "\t\tip6 saddr %s tcp dport %d accept comment \"anti-lockout\"\n", set(v6), lockout.Port)
		}
	}
	for _, line := range autoInputRules(in) {
		b.WriteString("\t\t" + line + "\n")
	}
	for i, r := range in.Rules {
		if r.Chain == fwconfig.ChainInput {
			writeRule(b, i, r, zoneIfaces)
		}
	}
	writePolicyVmap(b, in, zoneIfaces)
	b.WriteString("\t}\n\n")

	// ----- forward -----
	b.WriteString("\tchain forward {\n")
	b.WriteString("\t\ttype filter hook forward priority filter; policy drop;\n")
	b.WriteString("\t\tct state established,related accept\n")
	b.WriteString("\t\tct state invalid drop\n")
	b.WriteString("\t\tct status dnat accept comment \"port forwards\"\n")
	b.WriteString("\t\tmeta l4proto ipv6-icmp icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem } accept\n")
	for i, r := range in.Rules {
		if r.Chain == fwconfig.ChainForward {
			writeRule(b, i, r, zoneIfaces)
		}
	}
	b.WriteString("\t}\n\n")

	// ----- output -----
	b.WriteString("\tchain output {\n")
	b.WriteString("\t\ttype filter hook output priority filter; policy accept;\n")
	for i, r := range in.Rules {
		if r.Chain == fwconfig.ChainOutput {
			writeRule(b, i, r, zoneIfaces)
		}
	}
	b.WriteString("\t}\n\n")

	// ----- NAT -----
	b.WriteString("\tchain prerouting_nat {\n")
	b.WriteString("\t\ttype nat hook prerouting priority dstnat; policy accept;\n")
	for i, n := range in.NAT {
		if n.Kind == fwconfig.NATDNAT {
			writeNAT(b, i, n, zoneIfaces)
		}
	}
	b.WriteString("\t}\n\n")

	b.WriteString("\tchain postrouting_nat {\n")
	b.WriteString("\t\ttype nat hook postrouting priority srcnat; policy accept;\n")
	for i, n := range in.NAT {
		if n.Kind != fwconfig.NATDNAT {
			writeNAT(b, i, n, zoneIfaces)
		}
	}
	for _, z := range in.Zones {
		if !z.Masquerade {
			continue
		}
		if ifs := zoneIfaces[z.Name]; len(ifs) > 0 {
			// IPv4 only: IPv6 is routed, not NATed.
			fmt.Fprintf(b, "\t\toifname %s meta nfproto ipv4 counter masquerade comment \"zone %s\"\n", quotedSet(ifs), z.Name)
		}
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// zoneInterfaces maps zone name to its interface names (sorted).
func zoneInterfaces(in *fwconfig.Instance) map[string][]string {
	m := map[string][]string{}
	for _, ifc := range in.Interfaces {
		if ifc.Zone != "" && ifc.Enabled {
			m[ifc.Zone] = append(m[ifc.Zone], ifc.Name)
		}
	}
	for _, v := range m {
		sort.Strings(v)
	}
	return m
}

// autoInputRules opens what the configured services need, so a user who
// enables the DHCP server on lan doesn't also have to write the rule.
func autoInputRules(in *fwconfig.Instance) []string {
	var out []string
	var dhcpClient []string
	for _, ifc := range in.Interfaces {
		if ifc.Enabled && ifc.IPv4Mode == fwconfig.ModeDHCP {
			dhcpClient = append(dhcpClient, ifc.Name)
		}
	}
	if len(dhcpClient) > 0 {
		out = append(out, fmt.Sprintf("iifname %s udp sport 67 udp dport 68 accept comment \"auto: dhcp client\"", quotedSet(dhcpClient)))
	}
	if in.DHCP.Enabled {
		var ifs []string
		for _, s := range in.DHCP.Subnets {
			if fwconfig.AddrFamily(s.Prefix) == "ipv4" {
				ifs = appendUnique(ifs, s.Interface)
			}
		}
		sort.Strings(ifs)
		if len(ifs) > 0 {
			out = append(out, fmt.Sprintf("iifname %s udp dport 67 accept comment \"auto: dhcp server\"", quotedSet(ifs)))
		}
		if ifs6 := dhcp6Interfaces(in); len(ifs6) > 0 {
			out = append(out, fmt.Sprintf("iifname %s udp dport 547 accept comment \"auto: dhcpv6 server\"", quotedSet(ifs6)))
		}
	}
	if in.DNS.Enabled && len(in.DNS.ListenInterfaces) > 0 {
		ifs := append([]string(nil), in.DNS.ListenInterfaces...)
		sort.Strings(ifs)
		out = append(out, fmt.Sprintf("iifname %s meta l4proto { tcp, udp } th dport 53 accept comment \"auto: dns server\"", quotedSet(ifs)))
	}
	for _, ifc := range in.Interfaces {
		if ifc.Enabled && ifc.Kind == fwconfig.KindWireGuard && ifc.WireGuard != nil && ifc.WireGuard.ListenPort > 0 {
			out = append(out, fmt.Sprintf("udp dport %d accept comment \"auto: wireguard %s\"", ifc.WireGuard.ListenPort, ifc.Name))
		}
	}
	return out
}

// writePolicyVmap sends traffic that no rule matched to its zone's input
// policy. Interfaces without a zone fall through to the chain policy (drop).
func writePolicyVmap(b *strings.Builder, in *fwconfig.Instance, zoneIfaces map[string][]string) {
	var entries []string
	for _, z := range in.Zones {
		verdict := "drop"
		switch z.InputPolicy {
		case fwconfig.ActionAccept:
			verdict = "accept"
		case fwconfig.ActionReject:
			verdict = "jump reject_pkt"
		}
		for _, ifc := range zoneIfaces[z.Name] {
			entries = append(entries, fmt.Sprintf("%q : %s", ifc, verdict))
		}
	}
	if len(entries) > 0 {
		sort.Strings(entries)
		fmt.Fprintf(b, "\t\tiifname vmap { %s }\n", strings.Join(entries, ", "))
	}
}

func writeRule(b *strings.Builder, idx int, r fwconfig.Rule, zoneIfaces map[string][]string) {
	var parts []string
	if r.SrcZone != "" {
		ifs := zoneIfaces[r.SrcZone]
		if len(ifs) == 0 {
			fmt.Fprintf(b, "\t\t# rule %d skipped: zone %s has no interfaces\n", idx+1, r.SrcZone)
			return
		}
		parts = append(parts, "iifname "+quotedSet(ifs))
	}
	if r.DstZone != "" {
		ifs := zoneIfaces[r.DstZone]
		if len(ifs) == 0 {
			fmt.Fprintf(b, "\t\t# rule %d skipped: zone %s has no interfaces\n", idx+1, r.DstZone)
			return
		}
		parts = append(parts, "oifname "+quotedSet(ifs))
	}
	var tail []string
	tail = append(tail, "counter")
	if r.Log {
		tail = append(tail, fmt.Sprintf("log prefix \"fw rule %d %s: \"", idx+1, r.Action))
	}
	switch r.Action {
	case fwconfig.ActionAccept:
		tail = append(tail, "accept")
	case fwconfig.ActionDrop:
		tail = append(tail, "drop")
	case fwconfig.ActionReject:
		tail = append(tail, "jump reject_pkt")
	}
	tail = append(tail, comment(fmt.Sprintf("rule %d", idx+1), r.Description))
	// One nft rule per IP version when the addresses mix them.
	for _, m := range fwconfig.MatchFamilies(r.Family, r.Protocol, r.SrcAddrs, r.DstAddrs) {
		line := append(append(append([]string(nil), parts...), matchExpr(m, r.Protocol, r.DstPorts)...), tail...)
		b.WriteString("\t\t" + strings.Join(line, " ") + "\n")
	}
}

func writeNAT(b *strings.Builder, idx int, n fwconfig.NATRule, zoneIfaces map[string][]string) {
	var parts []string
	if n.InZone != "" {
		ifs := zoneIfaces[n.InZone]
		if len(ifs) == 0 {
			fmt.Fprintf(b, "\t\t# nat rule %d skipped: zone %s has no interfaces\n", idx+1, n.InZone)
			return
		}
		parts = append(parts, "iifname "+quotedSet(ifs))
	}
	if n.OutZone != "" {
		ifs := zoneIfaces[n.OutZone]
		if len(ifs) == 0 {
			fmt.Fprintf(b, "\t\t# nat rule %d skipped: zone %s has no interfaces\n", idx+1, n.OutZone)
			return
		}
		parts = append(parts, "oifname "+quotedSet(ifs))
	}
	// snat/dnat match the target's IP version; masquerade the versions of
	// its addresses, IPv4 without any.
	family := fwconfig.AddrFamily(n.ToAddr)
	if n.Kind == fwconfig.NATMasquerade && len(n.SrcAddrs) == 0 && len(n.DstAddrs) == 0 {
		family = "ipv4"
	}
	var tail []string
	tail = append(tail, "counter")
	switch n.Kind {
	case fwconfig.NATMasquerade:
		tail = append(tail, "masquerade")
	case fwconfig.NATSNAT, fwconfig.NATDNAT:
		target, _ := netip.ParseAddr(n.ToAddr)
		verb, fam := "snat", "ip"
		if n.Kind == fwconfig.NATDNAT {
			verb = "dnat"
		}
		if target.Is6() {
			fam = "ip6"
		}
		to := target.String()
		if n.ToPort != 0 {
			if target.Is6() {
				to = "[" + to + "]"
			}
			to = fmt.Sprintf("%s:%d", to, n.ToPort)
		}
		tail = append(tail, fmt.Sprintf("%s %s to %s", verb, fam, to))
	}
	tail = append(tail, comment(fmt.Sprintf("nat %d", idx+1), n.Description))
	for _, m := range fwconfig.MatchFamilies(family, n.Protocol, n.SrcAddrs, n.DstAddrs) {
		line := append(append(append([]string(nil), parts...), matchExpr(m, n.Protocol, n.DstPorts)...), tail...)
		b.WriteString("\t\t" + strings.Join(line, " ") + "\n")
	}
}

// matchExpr renders family / protocol / address / port matches for one
// IP version of a rule.
func matchExpr(m fwconfig.FamilyMatch, proto string, ports string) []string {
	var parts []string
	if len(m.Src) == 0 && len(m.Dst) == 0 && m.Family != "" {
		parts = append(parts, "meta nfproto "+m.Family)
	}
	fam := "ip"
	if m.Family == "ipv6" {
		fam = "ip6"
	}
	if len(m.Src) > 0 {
		parts = append(parts, fmt.Sprintf("%s saddr %s", fam, set(m.Src)))
	}
	if len(m.Dst) > 0 {
		parts = append(parts, fmt.Sprintf("%s daddr %s", fam, set(m.Dst)))
	}
	switch proto {
	case "tcp", "udp":
		if ports != "" {
			parts = append(parts, fmt.Sprintf("%s dport %s", proto, portSet(ports)))
		} else {
			parts = append(parts, "meta l4proto "+proto)
		}
	case "icmp":
		parts = append(parts, "meta l4proto icmp")
	case "icmpv6":
		parts = append(parts, "meta l4proto ipv6-icmp")
	}
	return parts
}

func splitFamilies(list []string) (v4, v6 []string) {
	for _, a := range list {
		p, err := fwconfig.ParseAddrOrPrefix(a)
		if err != nil {
			continue
		}
		if p.Addr().Is4() {
			v4 = append(v4, p.String())
		} else {
			v6 = append(v6, p.String())
		}
	}
	return v4, v6
}

// set renders validated addresses; single-address prefixes are written
// without /32 for readability.
func set(list []string) string {
	out := make([]string, 0, len(list))
	for _, a := range list {
		p, err := fwconfig.ParseAddrOrPrefix(a)
		if err != nil {
			continue
		}
		if p.IsSingleIP() {
			out = append(out, p.Addr().String())
		} else {
			out = append(out, p.String())
		}
	}
	if len(out) == 1 {
		return out[0]
	}
	return "{ " + strings.Join(out, ", ") + " }"
}

func portSet(s string) string {
	ranges, _ := fwconfig.ParsePorts(s)
	out := make([]string, 0, len(ranges))
	for _, r := range ranges {
		if r.Lo == r.Hi {
			out = append(out, fmt.Sprint(r.Lo))
		} else {
			out = append(out, fmt.Sprintf("%d-%d", r.Lo, r.Hi))
		}
	}
	if len(out) == 1 {
		return out[0]
	}
	return "{ " + strings.Join(out, ", ") + " }"
}

func quotedSet(names []string) string {
	q := make([]string, len(names))
	for i, n := range names {
		q[i] = fmt.Sprintf("%q", n)
	}
	if len(q) == 1 {
		return q[0]
	}
	return "{ " + strings.Join(q, ", ") + " }"
}

// comment renders an nft comment. nft strings cannot escape quotes, so
// they are replaced; control characters were rejected by validation.
func comment(prefix, desc string) string {
	s := prefix
	if desc != "" {
		s += ": " + desc
	}
	s = strings.NewReplacer(`"`, "'", `\`, "/").Replace(s)
	if r := []rune(s); len(r) > 120 {
		s = string(r[:120])
	}
	return `comment "` + s + `"`
}

func appendUnique(list []string, s string) []string {
	for _, x := range list {
		if x == s {
			return list
		}
	}
	return append(list, s)
}
