// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

// Package render turns a validated fwconfig.Document into the files the
// firewall runs from: one nftables ruleset, BIND/Kea/radvd configs and a
// dnsmgr2 config per instance, and one wg(8) config per WireGuard interface.
//
// Rendering is pure (no filesystem, no commands) so the same code serves
// the agent's apply path and the GUI's preview/diff.
package render

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"

	dnsmgr "github.com/abundo/dnsmgr2/dnsmgr"
	"gopkg.in/yaml.v3"

	"github.com/abundo/portitor/internal/fwconfig"
)

type Paths struct {
	EtcDir       string `yaml:"etc_dir" json:"etc_dir"`
	StateDir     string `yaml:"state_dir" json:"state_dir"`
	RunDir       string `yaml:"run_dir" json:"run_dir"`
	KeaDataDir   string `yaml:"kea_data_dir" json:"kea_data_dir"`
	KeaSocketDir string `yaml:"kea_socket_dir" json:"kea_socket_dir"`
	BindCacheDir string `yaml:"bind_cache_dir" json:"bind_cache_dir"`
	BindZonesDir string `yaml:"bind_zones_dir" json:"bind_zones_dir"`
	BindRunDir   string `yaml:"bind_run_dir" json:"bind_run_dir"`
	// The default instance is the host itself (root namespace): its files
	// are in the distribution's standard places, read by the
	// distribution's own units (Units.Default*), so a firewall without
	// virtual firewalls looks like an ordinary host. The other instances'
	// are under EtcDir/instances (InstanceEtc).
	NftablesFile string `yaml:"nftables_file" json:"nftables_file"`
	WireGuardDir string `yaml:"wireguard_dir" json:"wireguard_dir"`
	NamedConf    string `yaml:"named_conf" json:"named_conf"`
	KeaConfDir   string `yaml:"kea_conf_dir" json:"kea_conf_dir"`
	RadvdConf    string `yaml:"radvd_conf" json:"radvd_conf"`
	// FRRDir is FRR's config directory: the default instance's frr.conf
	// and daemons are in it, and a virtual firewall's unit mounts the
	// instance's over FRRDir/<instance> (FRR's pathspace).
	FRRDir string `yaml:"frr_dir" json:"frr_dir"`
	// FRR's run (sockets, PID files) and state directories; a virtual
	// firewall's FRR has <instance> directories in them.
	FRRRunDir   string `yaml:"frr_run_dir" json:"frr_run_dir"`
	FRRStateDir string `yaml:"frr_state_dir" json:"frr_state_dir"`
}

func DefaultPaths() Paths {
	return Paths{
		EtcDir:       "/etc/portitor",
		StateDir:     "/var/lib/portitor",
		RunDir:       "/run/portitor",
		KeaDataDir:   "/var/lib/kea",
		KeaSocketDir: "/run/kea",
		BindCacheDir: "/var/cache/bind",
		BindZonesDir: "/var/lib/bind",
		BindRunDir:   "/run/named",
		NftablesFile: "/etc/nftables.d/portitor.nft",
		WireGuardDir: "/etc/wireguard",
		NamedConf:    "/etc/bind/named.conf",
		KeaConfDir:   "/etc/kea",
		RadvdConf:    "/etc/radvd.conf",
		FRRDir:       "/etc/frr",
		FRRRunDir:    "/run/frr",
		FRRStateDir:  "/var/lib/frr",
	}
}

// Generated reports whether a file's content is one of ours (every
// rendered file starts with this mark). The default instance's files are
// in the distribution's places, where the sysadmin's own may be.
func Generated(content []byte) bool {
	line, _, _ := strings.Cut(string(content), "\n")
	return strings.Contains(line, "Generated by portitor-agent")
}

// InstanceFiles is where an instance's files are (Paths.Files).
type InstanceFiles struct {
	Nftables     string
	WireGuardDir string
	NamedConf    string
	// NamedInclude is the zones file dnsmgr2 writes, which named.conf
	// includes.
	NamedInclude string
	// DnsmgrDir holds dnsmgr2.yaml and records.json.
	DnsmgrDir string
	Kea4      string
	Kea6      string
	Radvd     string
	// FRR's integrated config, daemons file and vtysh.conf. A virtual
	// firewall's unit mounts their directory as FRR's pathspace
	// Paths.FRRDir/<instance> (portitor-frr@.service).
	FRRConf    string
	FRRDaemons string
	FRRVtysh   string
	// FRR's run and state directories (the pathspace's, for a virtual
	// firewall), which the agent makes for the frr user before the unit
	// mounts them.
	FRRRun   string
	FRRState string
	// The host's directories of Kea's leases and sockets and named's
	// working, run and zones directories. A virtual firewall's units mount
	// its own over the standard ones (portitor-kea4@.service,
	// portitor-named@.service), so one instance's daemons can't reach
	// another's files; the zones directory keeps its host path, as dnsmgr2
	// writes it into NamedInclude on the host.
	KeaData   string
	KeaSocket string
	BindCache string
	BindRun   string
	BindZones string
	// Kea's lease files and control sockets as Kea sees them. Kea 2.6+
	// refuses them outside its own directories, hence KeaDataDir and
	// KeaSocketDir.
	Kea4Lease  string
	Kea6Lease  string
	Kea4Socket string
	Kea6Socket string
}

// Files returns where an instance's files are: the distribution's places
// for the default instance, the instance's own directories for the others.
func (p Paths) Files(in *fwconfig.Instance) InstanceFiles {
	if in.Default {
		return InstanceFiles{
			Nftables:     p.NftablesFile,
			WireGuardDir: p.WireGuardDir,
			NamedConf:    p.NamedConf,
			NamedInclude: filepath.Join(filepath.Dir(p.NamedConf), "named.conf.dnsmgr2"),
			DnsmgrDir:    p.EtcDir,
			Kea4:         filepath.Join(p.KeaConfDir, "kea-dhcp4.conf"),
			Kea6:         filepath.Join(p.KeaConfDir, "kea-dhcp6.conf"),
			Radvd:        p.RadvdConf,
			FRRConf:      filepath.Join(p.FRRDir, "frr.conf"),
			FRRDaemons:   filepath.Join(p.FRRDir, "daemons"),
			FRRVtysh:     filepath.Join(p.FRRDir, "vtysh.conf"),
			FRRRun:       p.FRRRunDir,
			FRRState:     p.FRRStateDir,
			KeaData:      p.KeaDataDir,
			KeaSocket:    p.KeaSocketDir,
			BindCache:    p.BindCacheDir,
			BindRun:      p.BindRunDir,
			BindZones:    p.BindZonesDir,
			Kea4Lease:    filepath.Join(p.KeaDataDir, "kea-leases4.csv"),
			Kea6Lease:    filepath.Join(p.KeaDataDir, "kea-leases6.csv"),
			Kea4Socket:   filepath.Join(p.KeaSocketDir, "kea4-ctrl-socket"),
			Kea6Socket:   filepath.Join(p.KeaSocketDir, "kea6-ctrl-socket"),
		}
	}
	etc := p.InstanceEtc(in.Name)
	return InstanceFiles{
		Nftables:     filepath.Join(etc, "nftables.nft"),
		WireGuardDir: filepath.Join(etc, "wireguard"),
		NamedConf:    filepath.Join(etc, "named.conf"),
		NamedInclude: filepath.Join(etc, "named.conf.dnsmgr2"),
		DnsmgrDir:    etc,
		Kea4:         filepath.Join(etc, "kea-dhcp4.conf"),
		Kea6:         filepath.Join(etc, "kea-dhcp6.conf"),
		Radvd:        filepath.Join(etc, "radvd.conf"),
		FRRConf:      filepath.Join(etc, "frr", "frr.conf"),
		FRRDaemons:   filepath.Join(etc, "frr", "daemons"),
		FRRVtysh:     filepath.Join(etc, "frr", "vtysh.conf"),
		FRRRun:       filepath.Join(p.FRRRunDir, in.Name),
		FRRState:     filepath.Join(p.FRRStateDir, in.Name),
		KeaData:      filepath.Join(p.KeaDataDir, in.Name),
		KeaSocket:    filepath.Join(p.KeaSocketDir, in.Name),
		BindCache:    filepath.Join(p.BindCacheDir, in.Name),
		BindRun:      filepath.Join(p.BindRunDir, in.Name),
		BindZones:    filepath.Join(p.BindZonesDir, in.Name),
		Kea4Lease:    filepath.Join(p.KeaDataDir, "kea-leases4-"+in.Name+".csv"),
		Kea6Lease:    filepath.Join(p.KeaDataDir, "kea-leases6-"+in.Name+".csv"),
		Kea4Socket:   filepath.Join(p.KeaSocketDir, "kea4-"+in.Name+".sock"),
		Kea6Socket:   filepath.Join(p.KeaSocketDir, "kea6-"+in.Name+".sock"),
	}
}

func (p Paths) InstanceEtc(name string) string {
	return filepath.Join(p.EtcDir, "instances", name)
}

func (p Paths) InstanceState(name string) string {
	return filepath.Join(p.StateDir, "instances", name)
}

// IPListFile holds the nft commands that fill an IP list's sets (see
// IPListElements). The agent writes it; rulesets include it.
func (p Paths) IPListFile(name string) string {
	return filepath.Join(p.StateDir, "iplists", name+".nft")
}

// CertificateDir holds an ACME certificate of an instance: the agent
// writes its chain and key there (acme.FullChainFile, acme.PrivKeyFile).
func (p Paths) CertificateDir(instance, name string) string {
	return filepath.Join(p.StateDir, "certificates", instance, name)
}

// ACMEAccountsDir holds the ACME accounts, one per CA and email.
func (p Paths) ACMEAccountsDir() string {
	return filepath.Join(p.StateDir, "acme")
}

// Units names the systemd units that run an instance's services. %s is
// the instance name (see deploy/systemd for the template units). The
// default instance's run under the distribution's own units (Default*),
// which read the standard files (Paths.Files).
type Units struct {
	NamedFmt     string `yaml:"named" json:"named"`
	Kea4Fmt      string `yaml:"kea4" json:"kea4"`
	Kea6Fmt      string `yaml:"kea6" json:"kea6"`
	RadvdFmt     string `yaml:"radvd" json:"radvd"`
	FRRFmt       string `yaml:"frr" json:"frr"`
	DefaultNamed string `yaml:"default_named" json:"default_named"`
	DefaultKea4  string `yaml:"default_kea4" json:"default_kea4"`
	DefaultKea6  string `yaml:"default_kea6" json:"default_kea6"`
	DefaultRadvd string `yaml:"default_radvd" json:"default_radvd"`
	DefaultFRR   string `yaml:"default_frr" json:"default_frr"`
}

func DefaultUnits() Units {
	return Units{
		NamedFmt: "portitor-named@%s.service",
		Kea4Fmt:  "portitor-kea4@%s.service",
		Kea6Fmt:  "portitor-kea6@%s.service",
		RadvdFmt: "portitor-radvd@%s.service",
		FRRFmt:   "portitor-frr@%s.service",
		// Debian/Ubuntu's names (Fedora: kea-dhcp4.service, kea-dhcp6.service).
		DefaultNamed: "named.service",
		DefaultKea4:  "kea-dhcp4-server.service",
		DefaultKea6:  "kea-dhcp6-server.service",
		DefaultRadvd: "radvd.service",
		DefaultFRR:   "frr.service",
	}
}

func (u Units) pick(in *fwconfig.Instance, def, format string) string {
	if in.Default {
		return def
	}
	return fmt.Sprintf(format, in.Name)
}

func (u Units) Named(in *fwconfig.Instance) string { return u.pick(in, u.DefaultNamed, u.NamedFmt) }
func (u Units) Kea4(in *fwconfig.Instance) string  { return u.pick(in, u.DefaultKea4, u.Kea4Fmt) }
func (u Units) Kea6(in *fwconfig.Instance) string  { return u.pick(in, u.DefaultKea6, u.Kea6Fmt) }
func (u Units) Radvd(in *fwconfig.Instance) string { return u.pick(in, u.DefaultRadvd, u.RadvdFmt) }
func (u Units) FRR(in *fwconfig.Instance) string   { return u.pick(in, u.DefaultFRR, u.FRRFmt) }

// All lists the instance's units: named, Kea4, Kea6, radvd, FRR.
func (u Units) All(in *fwconfig.Instance) []string {
	return []string{u.Named(in), u.Kea4(in), u.Kea6(in), u.Radvd(in), u.FRR(in)}
}

type Options struct {
	Paths       Paths
	Units       Units
	AntiLockout *AntiLockout
	// DHCPDNS holds DNS servers learned by the DHCP client, per instance
	// and interface, for DNSServer.Upstream UpstreamDHCP.
	DHCPDNS map[string]map[string][]string
	// Delegated holds the prefixes delegated to the DHCPv6 clients, which
	// the document's delegated addresses are resolved from
	// (fwconfig.Document.ResolveDelegated).
	Delegated fwconfig.DelegatedPrefixes
}

type File struct {
	Path    string      `json:"path"`
	Content string      `json:"content"`
	Mode    os.FileMode `json:"mode"`
	// Secret files hold private keys; Redacted() masks them for display.
	Secret bool `json:"secret,omitempty"`
}

// Bundle is everything rendered for one document.
type Bundle struct {
	Files []File `json:"files"`
	// Dnsmgr is the dnsmgr2 config per instance, which the agent syncs
	// from. It is also written as dnsmgr2.yaml: one complete file (host,
	// SOA and zone templates, zones and DHCP prefixes; no zones.yaml
	// include, since Portitor owns all of it), so `dnsmgr2 -c` run by hand
	// does exactly what the agent does.
	Dnsmgr map[string]dnsmgr.ConfigRoot `json:"-"`
}

// Render validates doc and renders every file.
func Render(doc fwconfig.Document, opt Options) (*Bundle, error) {
	if err := doc.Validate(); err != nil {
		return nil, err
	}
	doc = doc.ResolveDelegated(opt.Delegated).Expand()
	b := &Bundle{Dnsmgr: map[string]dnsmgr.ConfigRoot{}}
	add := func(path, content string, mode os.FileMode, secret bool) {
		b.Files = append(b.Files, File{Path: path, Content: content, Mode: mode, Secret: secret})
	}

	for i := range doc.Instances {
		in := &doc.Instances[i]
		f := opt.Paths.Files(in)
		add(f.Nftables, Nftables(in, opt.AntiLockout, opt.Paths), 0o644, false)

		for j := range in.Interfaces {
			ifc := &in.Interfaces[j]
			if ifc.Kind == fwconfig.KindWireGuard && ifc.WireGuard != nil {
				add(filepath.Join(f.WireGuardDir, ifc.Name+".conf"), WireGuardConf(ifc), 0o600, true)
			}
		}

		if cfg, ok := DnsmgrConfig(in, opt.Paths, opt.Units); ok {
			b.Dnsmgr[in.Name] = cfg
			y, err := yaml.Marshal(cfg)
			if err != nil {
				return nil, err
			}
			add(filepath.Join(f.DnsmgrDir, "dnsmgr2.yaml"), "# Generated by portitor-agent. Do not edit.\n"+string(y), 0o644, false)
			add(filepath.Join(f.DnsmgrDir, "records.json"), RecordsJSON(in), 0o644, false)
		}
		if in.DNS.Enabled {
			add(f.NamedConf, NamedConf(in, opt.Paths, opt.DHCPDNS[in.Name]), 0o644, false)
		}
		if in.DHCP.Enabled {
			add(f.Kea4, KeaDhcp4Conf(in, opt.Paths), 0o644, false)
		}
		if len(DHCP6Subnets(in)) > 0 {
			add(f.Kea6, KeaDhcp6Conf(in, opt.Paths), 0o644, false)
		}
		if len(in.RA) > 0 {
			add(f.Radvd, RadvdConf(in), 0o644, false)
		}
		if in.FRRRunning() {
			add(f.FRRDaemons, FRRDaemons(in), 0o640, false)
			add(f.FRRVtysh, FRRVtyshConf(in), 0o644, false)
			add(f.FRRConf, FRRConf(in), 0o640, hasFRRSecret(in))
		}
	}
	sort.SliceStable(b.Files, func(i, j int) bool { return b.Files[i].Path < b.Files[j].Path })
	return b, nil
}

// File returns the file at path, or nil.
func (b *Bundle) File(path string) *File {
	for i := range b.Files {
		if b.Files[i].Path == path {
			return &b.Files[i]
		}
	}
	return nil
}

var (
	wgKeyLine       = regexp.MustCompile(`(?m)^(PrivateKey|PresharedKey) = .*$`)
	frrPasswordLine = regexp.MustCompile(`(?m)^( neighbor \S+` + frrPasswordWord + `).*$`)
	ospfKeyLine     = regexp.MustCompile(`(?m)^( ip ospf message-digest-key \d+` + ospfKeyWord + `).*$`)
)

// hasFRRSecret reports whether frr.conf holds a BGP password or an OSPF
// key.
func hasFRRSecret(in *fwconfig.Instance) bool {
	if g := in.BGP; in.BGPRunning() {
		for _, p := range append(slices.Clone(g.PeerGroups), g.Neighbors...) {
			if p.Password != "" {
				return true
			}
		}
	}
	if in.OSPFRunning(2) {
		for _, ifc := range in.OSPF.Interfaces {
			if ifc.AuthKey != "" {
				return true
			}
		}
	}
	return false
}

// Redacted returns the files with key material masked, for display.
func (b *Bundle) Redacted() []File {
	out := make([]File, len(b.Files))
	for i, f := range b.Files {
		out[i] = f
		if f.Secret {
			out[i].Content = wgKeyLine.ReplaceAllString(f.Content, "$1 = <redacted>")
			out[i].Content = frrPasswordLine.ReplaceAllString(out[i].Content, "${1}<redacted>")
			out[i].Content = ospfKeyLine.ReplaceAllString(out[i].Content, "${1}<redacted>")
		}
	}
	return out
}
