// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"fmt"
	"net/netip"
	"regexp"
	"strings"

	"github.com/abundo/portitor/internal/fwconfig"
)

// SNMPService is the SNMP auto rule's service, and its source set's name.
const (
	SNMPService = "snmp"
	SNMPSet     = "snmp_clients"
)

// SnmpdConf renders snmpd.conf for an instance with SNMP: read-only, the
// whole tree. snmpd listens on every address of the instance's namespace;
// the ruleset lets requests in on the SNMP interfaces from the allowed
// clients only, and the SNMPv2c community is limited to them too. A
// virtual firewall's snmpd keeps its engine id and the like in its own
// persistent directory (portitor-snmpd@.service).
func SnmpdConf(in *fwconfig.Instance) string {
	s := in.SNMP
	b := &strings.Builder{}
	b.WriteString("# Generated by portitor-agent. Do not edit.\n\n")
	fmt.Fprintf(b, "agentAddress udp:%d,udp6:%d\n", fwconfig.SNMPPort, fwconfig.SNMPPort)
	if s.Location != "" {
		fmt.Fprintf(b, "sysLocation %s\n", s.Location)
	}
	if s.Contact != "" {
		fmt.Fprintf(b, "sysContact %s\n", s.Contact)
	}
	// Layers 3 (internet) and 4 (end-to-end): a router and a host.
	b.WriteString("sysServices 76\n")
	if s.Community != "" {
		b.WriteString("\n")
		v4, v6 := splitFamilies(maskAll(s.Allow))
		if len(s.Allow) == 0 {
			v4, v6 = []string{"default"}, []string{"default"}
		}
		for _, a := range v4 {
			fmt.Fprintf(b, "rocommunity %s %s\n", s.Community, a)
		}
		for _, a := range v6 {
			fmt.Fprintf(b, "rocommunity6 %s %s\n", s.Community, a)
		}
	}
	if len(s.Users) > 0 {
		b.WriteString("\n")
	}
	for _, u := range s.Users {
		fmt.Fprintf(b, "createUser %s %s %s", u.Name, u.AuthProtocol, u.AuthPassword)
		level := "auth"
		if u.PrivProtocol != "" {
			fmt.Fprintf(b, " %s %s", u.PrivProtocol, u.PrivPassword)
			level = "priv"
		}
		fmt.Fprintf(b, "\nrouser -s usm %s %s\n", u.Name, level)
	}
	return b.String()
}

// SNMPClients are the instance's SNMP allowed clients, masked, for the
// auto rule's source set.
func SNMPClients(in *fwconfig.Instance) []string {
	return maskAll(in.SNMP.Allow)
}

func maskAll(prefixes []string) []string {
	var out []string
	for _, a := range prefixes {
		if p, err := netip.ParsePrefix(a); err == nil {
			out = append(out, p.Masked().String())
		}
	}
	return out
}

// hasSNMPSecret reports whether snmpd.conf holds a community or password.
func hasSNMPSecret(in *fwconfig.Instance) bool {
	return in.SNMP.Community != "" || len(in.SNMP.Users) > 0
}

var (
	snmpCommunityLine = regexp.MustCompile(`(?m)^(rocommunity6? )\S+`)
	snmpUserLine      = regexp.MustCompile(`(?m)^(createUser \S+ \S+ )\S+(?: (\S+) \S+)?$`)
)

// redactSnmpd masks the community and the passwords in snmpd.conf.
func redactSnmpd(s string) string {
	s = snmpCommunityLine.ReplaceAllString(s, "${1}<redacted>")
	return snmpUserLine.ReplaceAllStringFunc(s, func(line string) string {
		m := snmpUserLine.FindStringSubmatch(line)
		out := m[1] + "<redacted>"
		if m[2] != "" {
			out += " " + m[2] + " <redacted>"
		}
		return out
	})
}
