// SPDX-FileCopyrightText: 2026 The Portitor contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

package render

import (
	"fmt"
	"strings"

	"github.com/abundo/portitor/internal/fwconfig"
)

// WireGuardConf renders the `wg setconf` file for one interface. Addresses
// and MTU are not part of this format; the agent sets them with ip(8).
func WireGuardConf(ifc *fwconfig.Interface) string {
	wg := ifc.WireGuard
	b := &strings.Builder{}
	fmt.Fprintf(b, "# Generated by portitor-agent. Interface %s. Do not edit.\n", ifc.Name)
	b.WriteString("[Interface]\n")
	fmt.Fprintf(b, "PrivateKey = %s\n", wg.PrivateKey)
	if wg.ListenPort > 0 {
		fmt.Fprintf(b, "ListenPort = %d\n", wg.ListenPort)
	}
	for _, p := range wg.Peers {
		fmt.Fprintf(b, "\n# %s\n[Peer]\n", p.Name)
		fmt.Fprintf(b, "PublicKey = %s\n", p.PublicKey)
		if p.PresharedKey != "" {
			fmt.Fprintf(b, "PresharedKey = %s\n", p.PresharedKey)
		}
		if p.Endpoint != "" {
			fmt.Fprintf(b, "Endpoint = %s\n", p.Endpoint)
		}
		if len(p.AllowedIPs) > 0 {
			fmt.Fprintf(b, "AllowedIPs = %s\n", strings.Join(p.AllowedIPs, ", "))
		}
		if p.Keepalive > 0 {
			fmt.Fprintf(b, "PersistentKeepalive = %d\n", p.Keepalive)
		}
	}
	return b.String()
}

// WGClientConfig is a wg-quick config for the remote end of a peer, for the
// GUI to hand out (road-warrior phones and laptops).
type WGClientConfig struct {
	PrivateKey      string
	Addresses       []string
	DNS             []string
	ServerPublicKey string
	PresharedKey    string
	Endpoint        string
	AllowedIPs      []string
	Keepalive       int
}

func WireGuardClientConf(c WGClientConfig) string {
	b := &strings.Builder{}
	b.WriteString("[Interface]\n")
	pk := c.PrivateKey
	if pk == "" {
		pk = "<client private key>"
	}
	fmt.Fprintf(b, "PrivateKey = %s\n", pk)
	if len(c.Addresses) > 0 {
		fmt.Fprintf(b, "Address = %s\n", strings.Join(c.Addresses, ", "))
	}
	if len(c.DNS) > 0 {
		fmt.Fprintf(b, "DNS = %s\n", strings.Join(c.DNS, ", "))
	}
	b.WriteString("\n[Peer]\n")
	fmt.Fprintf(b, "PublicKey = %s\n", c.ServerPublicKey)
	if c.PresharedKey != "" {
		fmt.Fprintf(b, "PresharedKey = %s\n", c.PresharedKey)
	}
	if c.Endpoint != "" {
		fmt.Fprintf(b, "Endpoint = %s\n", c.Endpoint)
	}
	fmt.Fprintf(b, "AllowedIPs = %s\n", strings.Join(c.AllowedIPs, ", "))
	if c.Keepalive > 0 {
		fmt.Fprintf(b, "PersistentKeepalive = %d\n", c.Keepalive)
	}
	return b.String()
}
